DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'basket') THEN
        CREATE SCHEMA basket;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS basket."__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM basket."__EFMigrationsHistory" WHERE "migration_id" = '20260425100509_InitializeBasketOutboxAndInbox') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'basket') THEN
            CREATE SCHEMA basket;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM basket."__EFMigrationsHistory" WHERE "migration_id" = '20260425100509_InitializeBasketOutboxAndInbox') THEN
    CREATE TABLE basket."InboxMessages" (
        message_id uuid NOT NULL,
        processed_at_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_inbox_messages PRIMARY KEY (message_id)
    );
    COMMENT ON TABLE basket."InboxMessages" IS 'Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.';
    COMMENT ON COLUMN basket."InboxMessages".message_id IS 'Unique message identifier (Primary Key).';
    COMMENT ON COLUMN basket."InboxMessages".processed_at_utc IS 'UTC timestamp when the message was processed.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM basket."__EFMigrationsHistory" WHERE "migration_id" = '20260425100509_InitializeBasketOutboxAndInbox') THEN
    CREATE TABLE basket."OutboxMessages" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        topic_name character varying(249) NOT NULL,
        kafka_key character varying(128),
        avro_payload bytea NOT NULL,
        type character varying(255) NOT NULL,
        headers character varying(8192),
        created_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
    );
    COMMENT ON TABLE basket."OutboxMessages" IS 'Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.';
    COMMENT ON COLUMN basket."OutboxMessages".id IS 'PK, Identity';
    COMMENT ON COLUMN basket."OutboxMessages".topic_name IS 'The Kafka topic where this message will be published. Set by the message producer.';
    COMMENT ON COLUMN basket."OutboxMessages".kafka_key IS 'Kafka Key - typically the Aggregate ID for proper event ordering and partitioning';
    COMMENT ON COLUMN basket."OutboxMessages".avro_payload IS 'Avro-serialized domain event payload';
    COMMENT ON COLUMN basket."OutboxMessages".type IS 'Avro type name of the serialized event (e.g., ''FeedbackChangedEvent'') for deserialization and observability';
    COMMENT ON COLUMN basket."OutboxMessages".headers IS 'JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.';
    COMMENT ON COLUMN basket."OutboxMessages".created_utc IS 'Creation timestamp (UTC).';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM basket."__EFMigrationsHistory" WHERE "migration_id" = '20260425100509_InitializeBasketOutboxAndInbox') THEN
    CREATE INDEX "IX_InboxMessages_ProcessedAtUtc" ON basket."InboxMessages" (processed_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM basket."__EFMigrationsHistory" WHERE "migration_id" = '20260425100509_InitializeBasketOutboxAndInbox') THEN
    INSERT INTO basket."__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260425100509_InitializeBasketOutboxAndInbox', '10.0.8');
    END IF;
END $EF$;

