// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Payments.Transactions
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Imperative command from the Checkout saga to PaymentProcessingSaga (the sub-saga) aborting a previously-authorized payment because the Checkout saga's confirmation step (stock + order) failed (ADR-0026). On receipt the sub-saga leaves its AwaitingCaptureApproval wait-state and issues VoidPaymentCommand to the Payments service — a free pre-capture void, never a refund. Correlated by OrderId per ADR-0029.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class AbortCaptureCommand : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""AbortCaptureCommand"",""doc"":""Imperative command from the Checkout saga to PaymentProcessingSaga (the sub-saga) aborting a previously-authorized payment because the Checkout saga's confirmation step (stock + order) failed (ADR-0026). On receipt the sub-saga leaves its AwaitingCaptureApproval wait-state and issues VoidPaymentCommand to the Payments service — a free pre-capture void, never a refund. Correlated by OrderId per ADR-0029."",""namespace"":""Payments.Transactions"",""fields"":[{""name"":""OrderId"",""doc"":""Order this payment is for; the PaymentProcessingSaga correlation key (ADR-0029)."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""UserId"",""doc"":""User whose payment authorization is being aborted. Carried for log/audit context (the sub-saga authoritatively holds it in state)."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Reason"",""doc"":""Reason the Checkout saga aborted the capture (e.g. order-confirmation failure / timeout). Flows onto the sub-saga's VoidPaymentCommand.Reason for the gateway-void audit trail."",""type"":""string""},{""name"":""RequestedAtUtc"",""doc"":""UTC timestamp when the Checkout saga aborted the capture."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Order this payment is for; the PaymentProcessingSaga correlation key (ADR-0029).
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// User whose payment authorization is being aborted. Carried for log/audit context (the sub-saga authoritatively holds it in state).
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Reason the Checkout saga aborted the capture (e.g. order-confirmation failure / timeout). Flows onto the sub-saga's VoidPaymentCommand.Reason for the gateway-void audit trail.
		/// </summary>
		private string _Reason;
		/// <summary>
		/// UTC timestamp when the Checkout saga aborted the capture.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AbortCaptureCommand._SCHEMA;
			}
		}
		/// <summary>
		/// Order this payment is for; the PaymentProcessingSaga correlation key (ADR-0029).
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// User whose payment authorization is being aborted. Carried for log/audit context (the sub-saga authoritatively holds it in state).
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Reason the Checkout saga aborted the capture (e.g. order-confirmation failure / timeout). Flows onto the sub-saga's VoidPaymentCommand.Reason for the gateway-void audit trail.
		/// </summary>
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				this._Reason = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the Checkout saga aborted the capture.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.UserId;
			case 2: return this.Reason;
			case 3: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.Reason = (System.String)fieldValue; break;
			case 3: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
