// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Payments.Transactions
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Command sent by Payment Saga to request payment authorization from the Payment Service.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class AuthorizePaymentCommand : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"AuthorizePaymentCommand\",\"doc\":\"Command sent by Payment " +
				"Saga to request payment authorization from the Payment Service.\",\"namespace\":\"Pa" +
				"yments.Transactions\",\"fields\":[{\"name\":\"PaymentTransactionId\",\"doc\":\"Saga-minted" +
				" UUID v7 that becomes the Payments aggregate\'s primary key. The saga emits a fre" +
				"sh value at initial state and reuses it on every retry. One-payment-per-order is" +
				" enforced by the unique index on payment_transactions.order_id (ADR-0029).\",\"typ" +
				"e\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"OrderId\",\"doc\":\"Ordering agg" +
				"regate id this payment is attached to. The Checkout saga creates the order befor" +
				"e requesting payment, so OrderId is always present at authorize time. Persisted " +
				"on the PaymentTransaction aggregate as the durable cross-BC business key backing" +
				" the unique one-payment-per-order index (ADR-0029).\",\"type\":{\"type\":\"string\",\"lo" +
				"gicalType\":\"uuid\"}},{\"name\":\"UserId\",\"doc\":\"User to authorize payment for.\",\"typ" +
				"e\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"PaymentMethodId\",\"doc\":\"Gate" +
				"way-issued opaque payment-method token (e.g. Stripe \'pm_*\', Adyen alphanumeric);" +
				" 1-64 chars. BREAKING change in the Wave-1 closeout C-2 fix: previously typed as" +
				" logicalType:uuid which blocked any real-PSP adapter swap because no real gatewa" +
				"y issues UUID-shaped payment-method ids.\",\"type\":\"string\"},{\"name\":\"Amount\",\"doc" +
				"\":\"Amount to authorize.\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precisi" +
				"on\":19,\"scale\":4}},{\"name\":\"Currency\",\"doc\":\"ISO 4217 currency code.\",\"type\":\"st" +
				"ring\"},{\"name\":\"IdempotencyKey\",\"doc\":\"Idempotency key to prevent duplicate auth" +
				"orizations.\",\"type\":\"string\"},{\"name\":\"RequestedAtUtc\",\"doc\":\"UTC timestamp when" +
				" authorization was requested.\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-mi" +
				"llis\"}}]}");
		/// <summary>
		/// Saga-minted UUID v7 that becomes the Payments aggregate's primary key. The saga emits a fresh value at initial state and reuses it on every retry. One-payment-per-order is enforced by the unique index on payment_transactions.order_id (ADR-0029).
		/// </summary>
		private System.Guid _PaymentTransactionId;
		/// <summary>
		/// Ordering aggregate id this payment is attached to. The Checkout saga creates the order before requesting payment, so OrderId is always present at authorize time. Persisted on the PaymentTransaction aggregate as the durable cross-BC business key backing the unique one-payment-per-order index (ADR-0029).
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// User to authorize payment for.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Gateway-issued opaque payment-method token (e.g. Stripe 'pm_*', Adyen alphanumeric); 1-64 chars. BREAKING change in the Wave-1 closeout C-2 fix: previously typed as logicalType:uuid which blocked any real-PSP adapter swap because no real gateway issues UUID-shaped payment-method ids.
		/// </summary>
		private string _PaymentMethodId;
		/// <summary>
		/// Amount to authorize.
		/// </summary>
		private Avro.AvroDecimal _Amount;
		/// <summary>
		/// ISO 4217 currency code.
		/// </summary>
		private string _Currency;
		/// <summary>
		/// Idempotency key to prevent duplicate authorizations.
		/// </summary>
		private string _IdempotencyKey;
		/// <summary>
		/// UTC timestamp when authorization was requested.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AuthorizePaymentCommand._SCHEMA;
			}
		}
		/// <summary>
		/// Saga-minted UUID v7 that becomes the Payments aggregate's primary key. The saga emits a fresh value at initial state and reuses it on every retry. One-payment-per-order is enforced by the unique index on payment_transactions.order_id (ADR-0029).
		/// </summary>
		public System.Guid PaymentTransactionId
		{
			get
			{
				return this._PaymentTransactionId;
			}
			set
			{
				this._PaymentTransactionId = value;
			}
		}
		/// <summary>
		/// Ordering aggregate id this payment is attached to. The Checkout saga creates the order before requesting payment, so OrderId is always present at authorize time. Persisted on the PaymentTransaction aggregate as the durable cross-BC business key backing the unique one-payment-per-order index (ADR-0029).
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// User to authorize payment for.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Gateway-issued opaque payment-method token (e.g. Stripe 'pm_*', Adyen alphanumeric); 1-64 chars. BREAKING change in the Wave-1 closeout C-2 fix: previously typed as logicalType:uuid which blocked any real-PSP adapter swap because no real gateway issues UUID-shaped payment-method ids.
		/// </summary>
		public string PaymentMethodId
		{
			get
			{
				return this._PaymentMethodId;
			}
			set
			{
				this._PaymentMethodId = value;
			}
		}
		/// <summary>
		/// Amount to authorize.
		/// </summary>
		public Avro.AvroDecimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				this._Amount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code.
		/// </summary>
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		/// <summary>
		/// Idempotency key to prevent duplicate authorizations.
		/// </summary>
		public string IdempotencyKey
		{
			get
			{
				return this._IdempotencyKey;
			}
			set
			{
				this._IdempotencyKey = value;
			}
		}
		/// <summary>
		/// UTC timestamp when authorization was requested.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.PaymentTransactionId;
			case 1: return this.OrderId;
			case 2: return this.UserId;
			case 3: return this.PaymentMethodId;
			case 4: return this.Amount;
			case 5: return this.Currency;
			case 6: return this.IdempotencyKey;
			case 7: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.PaymentTransactionId = (System.Guid)fieldValue; break;
			case 1: this.OrderId = (System.Guid)fieldValue; break;
			case 2: this.UserId = (System.Guid)fieldValue; break;
			case 3: this.PaymentMethodId = (System.String)fieldValue; break;
			case 4: this.Amount = (Avro.AvroDecimal)fieldValue; break;
			case 5: this.Currency = (System.String)fieldValue; break;
			case 6: this.IdempotencyKey = (System.String)fieldValue; break;
			case 7: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
