// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Payments.Transactions
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Command sent by Payment Saga to capture an authorized payment.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class CapturePaymentCommand : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""CapturePaymentCommand"",""doc"":""Command sent by Payment Saga to capture an authorized payment."",""namespace"":""Payments.Transactions"",""fields"":[{""name"":""UserId"",""doc"":""User whose payment to capture."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""AuthorizationId"",""doc"":""Authorization ID from the payment provider to capture."",""type"":""string""},{""name"":""Amount"",""doc"":""Amount to capture (may be less than or equal to authorized amount)."",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":19,""scale"":4}},{""name"":""RequestedAtUtc"",""doc"":""UTC timestamp when capture was requested."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// User whose payment to capture.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Authorization ID from the payment provider to capture.
		/// </summary>
		private string _AuthorizationId;
		/// <summary>
		/// Amount to capture (may be less than or equal to authorized amount).
		/// </summary>
		private Avro.AvroDecimal _Amount;
		/// <summary>
		/// UTC timestamp when capture was requested.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return CapturePaymentCommand._SCHEMA;
			}
		}
		/// <summary>
		/// User whose payment to capture.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Authorization ID from the payment provider to capture.
		/// </summary>
		public string AuthorizationId
		{
			get
			{
				return this._AuthorizationId;
			}
			set
			{
				this._AuthorizationId = value;
			}
		}
		/// <summary>
		/// Amount to capture (may be less than or equal to authorized amount).
		/// </summary>
		public Avro.AvroDecimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				this._Amount = value;
			}
		}
		/// <summary>
		/// UTC timestamp when capture was requested.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.UserId;
			case 1: return this.AuthorizationId;
			case 2: return this.Amount;
			case 3: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.UserId = (System.Guid)fieldValue; break;
			case 1: this.AuthorizationId = (System.String)fieldValue; break;
			case 2: this.Amount = (Avro.AvroDecimal)fieldValue; break;
			case 3: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
