// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Payments.Transactions
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted when a captured payment has been refunded. Used for compensation when business operation fails after capture.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class PaymentRefundedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PaymentRefundedEvent"",""doc"":""Event emitted when a captured payment has been refunded. Used for compensation when business operation fails after capture."",""namespace"":""Payments.Transactions"",""fields"":[{""name"":""OrderId"",""doc"":""Order this refund is attached to; the durable business key Invoicing keys its credit-note projection on (ADR-0029)."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""UserId"",""doc"":""User who received the refund."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""PaymentTransactionId"",""doc"":""Original payment transaction ID that was refunded."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""RefundTransactionId"",""doc"":""New transaction ID for the refund."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""RefundedAmount"",""doc"":""Amount refunded."",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":19,""scale"":4}},{""name"":""Currency"",""doc"":""ISO 4217 currency code."",""type"":""string""},{""name"":""RefundedAtUtc"",""doc"":""UTC timestamp when refund was completed."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Order this refund is attached to; the durable business key Invoicing keys its credit-note projection on (ADR-0029).
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// User who received the refund.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Original payment transaction ID that was refunded.
		/// </summary>
		private System.Guid _PaymentTransactionId;
		/// <summary>
		/// New transaction ID for the refund.
		/// </summary>
		private System.Guid _RefundTransactionId;
		/// <summary>
		/// Amount refunded.
		/// </summary>
		private Avro.AvroDecimal _RefundedAmount;
		/// <summary>
		/// ISO 4217 currency code.
		/// </summary>
		private string _Currency;
		/// <summary>
		/// UTC timestamp when refund was completed.
		/// </summary>
		private System.DateTime _RefundedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PaymentRefundedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Order this refund is attached to; the durable business key Invoicing keys its credit-note projection on (ADR-0029).
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// User who received the refund.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Original payment transaction ID that was refunded.
		/// </summary>
		public System.Guid PaymentTransactionId
		{
			get
			{
				return this._PaymentTransactionId;
			}
			set
			{
				this._PaymentTransactionId = value;
			}
		}
		/// <summary>
		/// New transaction ID for the refund.
		/// </summary>
		public System.Guid RefundTransactionId
		{
			get
			{
				return this._RefundTransactionId;
			}
			set
			{
				this._RefundTransactionId = value;
			}
		}
		/// <summary>
		/// Amount refunded.
		/// </summary>
		public Avro.AvroDecimal RefundedAmount
		{
			get
			{
				return this._RefundedAmount;
			}
			set
			{
				this._RefundedAmount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code.
		/// </summary>
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		/// <summary>
		/// UTC timestamp when refund was completed.
		/// </summary>
		public System.DateTime RefundedAtUtc
		{
			get
			{
				return this._RefundedAtUtc;
			}
			set
			{
				this._RefundedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.UserId;
			case 2: return this.PaymentTransactionId;
			case 3: return this.RefundTransactionId;
			case 4: return this.RefundedAmount;
			case 5: return this.Currency;
			case 6: return this.RefundedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.PaymentTransactionId = (System.Guid)fieldValue; break;
			case 3: this.RefundTransactionId = (System.Guid)fieldValue; break;
			case 4: this.RefundedAmount = (Avro.AvroDecimal)fieldValue; break;
			case 5: this.Currency = (System.String)fieldValue; break;
			case 6: this.RefundedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
