// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Payments.Transactions
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Imperative command from the Checkout saga to PaymentProcessingSaga (the sub-saga) asking it to drive a payment through authorize → capture for the supplied order. The Checkout saga's state machine awaits the matching PaymentCompletedEvent or PaymentFailedEvent (correlated by CorrelationId) to advance. Renamed from PaymentRequestedEvent and moved to payments.payment-commands per ADR-0023; the wire shape is identical.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class RequestPaymentCommand : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"RequestPaymentCommand\",\"doc\":\"Imperative command from th" +
				"e Checkout saga to PaymentProcessingSaga (the sub-saga) asking it to drive a pay" +
				"ment through authorize → capture for the supplied order. The Checkout saga\'s sta" +
				"te machine awaits the matching PaymentCompletedEvent or PaymentFailedEvent (corr" +
				"elated by CorrelationId) to advance. Renamed from PaymentRequestedEvent and move" +
				"d to payments.payment-commands per ADR-0023; the wire shape is identical.\",\"name" +
				"space\":\"Payments.Transactions\",\"fields\":[{\"name\":\"CorrelationId\",\"doc\":\"Correlat" +
				"ion ID shared across the entire business flow (e.g., checkout → order → payment " +
				"→ invoice). Also the Kafka message key for payments.payment-commands partitionin" +
				"g.\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"OrderId\",\"doc\":\"Orde" +
				"ring aggregate id this payment is attached to. Persisted on the Payments-side ag" +
				"gregate as a debugging/admin-lookup convenience; downstream Payments events drop" +
				" it (cross-BC linkage stays CorrelationId).\",\"default\":\"00000000-0000-0000-0000-" +
				"000000000000\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"UserId\",\"d" +
				"oc\":\"User initiating the payment.\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}" +
				"},{\"name\":\"PaymentMethodId\",\"doc\":\"Gateway-issued opaque payment-method token (e" +
				".g. Stripe \'pm_*\', Adyen alphanumeric); 1-64 chars. BREAKING change in the Wave-" +
				"1 closeout C-2 fix: previously typed as logicalType:uuid which blocked any real-" +
				"PSP adapter swap because no real gateway issues UUID-shaped payment-method ids.\"" +
				",\"type\":\"string\"},{\"name\":\"Amount\",\"doc\":\"Payment amount.\",\"type\":{\"type\":\"bytes" +
				"\",\"logicalType\":\"decimal\",\"precision\":19,\"scale\":4}},{\"name\":\"Currency\",\"doc\":\"I" +
				"SO 4217 currency code (e.g., \'USD\', \'EUR\').\",\"type\":\"string\"},{\"name\":\"Idempoten" +
				"cyKey\",\"doc\":\"Idempotency key for preventing duplicate payment processing.\",\"typ" +
				"e\":\"string\"},{\"name\":\"RequestedAtUtc\",\"doc\":\"UTC timestamp when payment was requ" +
				"ested.\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
		/// <summary>
		/// Correlation ID shared across the entire business flow (e.g., checkout → order → payment → invoice). Also the Kafka message key for payments.payment-commands partitioning.
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// Ordering aggregate id this payment is attached to. Persisted on the Payments-side aggregate as a debugging/admin-lookup convenience; downstream Payments events drop it (cross-BC linkage stays CorrelationId).
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// User initiating the payment.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Gateway-issued opaque payment-method token (e.g. Stripe 'pm_*', Adyen alphanumeric); 1-64 chars. BREAKING change in the Wave-1 closeout C-2 fix: previously typed as logicalType:uuid which blocked any real-PSP adapter swap because no real gateway issues UUID-shaped payment-method ids.
		/// </summary>
		private string _PaymentMethodId;
		/// <summary>
		/// Payment amount.
		/// </summary>
		private Avro.AvroDecimal _Amount;
		/// <summary>
		/// ISO 4217 currency code (e.g., 'USD', 'EUR').
		/// </summary>
		private string _Currency;
		/// <summary>
		/// Idempotency key for preventing duplicate payment processing.
		/// </summary>
		private string _IdempotencyKey;
		/// <summary>
		/// UTC timestamp when payment was requested.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return RequestPaymentCommand._SCHEMA;
			}
		}
		/// <summary>
		/// Correlation ID shared across the entire business flow (e.g., checkout → order → payment → invoice). Also the Kafka message key for payments.payment-commands partitioning.
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// Ordering aggregate id this payment is attached to. Persisted on the Payments-side aggregate as a debugging/admin-lookup convenience; downstream Payments events drop it (cross-BC linkage stays CorrelationId).
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// User initiating the payment.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Gateway-issued opaque payment-method token (e.g. Stripe 'pm_*', Adyen alphanumeric); 1-64 chars. BREAKING change in the Wave-1 closeout C-2 fix: previously typed as logicalType:uuid which blocked any real-PSP adapter swap because no real gateway issues UUID-shaped payment-method ids.
		/// </summary>
		public string PaymentMethodId
		{
			get
			{
				return this._PaymentMethodId;
			}
			set
			{
				this._PaymentMethodId = value;
			}
		}
		/// <summary>
		/// Payment amount.
		/// </summary>
		public Avro.AvroDecimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				this._Amount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code (e.g., 'USD', 'EUR').
		/// </summary>
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		/// <summary>
		/// Idempotency key for preventing duplicate payment processing.
		/// </summary>
		public string IdempotencyKey
		{
			get
			{
				return this._IdempotencyKey;
			}
			set
			{
				this._IdempotencyKey = value;
			}
		}
		/// <summary>
		/// UTC timestamp when payment was requested.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CorrelationId;
			case 1: return this.OrderId;
			case 2: return this.UserId;
			case 3: return this.PaymentMethodId;
			case 4: return this.Amount;
			case 5: return this.Currency;
			case 6: return this.IdempotencyKey;
			case 7: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CorrelationId = (System.Guid)fieldValue; break;
			case 1: this.OrderId = (System.Guid)fieldValue; break;
			case 2: this.UserId = (System.Guid)fieldValue; break;
			case 3: this.PaymentMethodId = (System.String)fieldValue; break;
			case 4: this.Amount = (Avro.AvroDecimal)fieldValue; break;
			case 5: this.Currency = (System.String)fieldValue; break;
			case 6: this.IdempotencyKey = (System.String)fieldValue; break;
			case 7: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
