// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Payments.Transactions
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Imperative command from the Checkout saga to PaymentProcessingSaga (the sub-saga) asking it to drive a payment through authorize → capture for the supplied order. The Checkout saga's state machine awaits the matching PaymentCompletedEvent or PaymentFailedEvent (correlated by OrderId per ADR-0029) to advance. Renamed from PaymentRequestedEvent and moved to payments.payment-commands per ADR-0023; the wire shape is identical.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class RequestPaymentCommand : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"RequestPaymentCommand\",\"doc\":\"Imperative command from th" +
				"e Checkout saga to PaymentProcessingSaga (the sub-saga) asking it to drive a pay" +
				"ment through authorize → capture for the supplied order. The Checkout saga\'s sta" +
				"te machine awaits the matching PaymentCompletedEvent or PaymentFailedEvent (corr" +
				"elated by OrderId per ADR-0029) to advance. Renamed from PaymentRequestedEvent a" +
				"nd moved to payments.payment-commands per ADR-0023; the wire shape is identical." +
				"\",\"namespace\":\"Payments.Transactions\",\"fields\":[{\"name\":\"OrderId\",\"doc\":\"Orderin" +
				"g aggregate id this payment is attached to. The durable cross-BC business key, c" +
				"arried through to the Payments aggregate and its downstream events (ADR-0029).\"," +
				"\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"UserId\",\"doc\":\"User init" +
				"iating the payment.\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"Pay" +
				"mentMethodId\",\"doc\":\"Gateway-issued opaque payment-method token (e.g. Stripe \'pm" +
				"_*\', Adyen alphanumeric); 1-64 chars. BREAKING change in the Wave-1 closeout C-2" +
				" fix: previously typed as logicalType:uuid which blocked any real-PSP adapter sw" +
				"ap because no real gateway issues UUID-shaped payment-method ids.\",\"type\":\"strin" +
				"g\"},{\"name\":\"Amount\",\"doc\":\"Payment amount.\",\"type\":{\"type\":\"bytes\",\"logicalType" +
				"\":\"decimal\",\"precision\":19,\"scale\":4}},{\"name\":\"Currency\",\"doc\":\"ISO 4217 curren" +
				"cy code (e.g., \'USD\', \'EUR\').\",\"type\":\"string\"},{\"name\":\"IdempotencyKey\",\"doc\":\"" +
				"Idempotency key for preventing duplicate payment processing.\",\"type\":\"string\"},{" +
				"\"name\":\"RequestedAtUtc\",\"doc\":\"UTC timestamp when payment was requested.\",\"type\"" +
				":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
		/// <summary>
		/// Ordering aggregate id this payment is attached to. The durable cross-BC business key, carried through to the Payments aggregate and its downstream events (ADR-0029).
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// User initiating the payment.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Gateway-issued opaque payment-method token (e.g. Stripe 'pm_*', Adyen alphanumeric); 1-64 chars. BREAKING change in the Wave-1 closeout C-2 fix: previously typed as logicalType:uuid which blocked any real-PSP adapter swap because no real gateway issues UUID-shaped payment-method ids.
		/// </summary>
		private string _PaymentMethodId;
		/// <summary>
		/// Payment amount.
		/// </summary>
		private Avro.AvroDecimal _Amount;
		/// <summary>
		/// ISO 4217 currency code (e.g., 'USD', 'EUR').
		/// </summary>
		private string _Currency;
		/// <summary>
		/// Idempotency key for preventing duplicate payment processing.
		/// </summary>
		private string _IdempotencyKey;
		/// <summary>
		/// UTC timestamp when payment was requested.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return RequestPaymentCommand._SCHEMA;
			}
		}
		/// <summary>
		/// Ordering aggregate id this payment is attached to. The durable cross-BC business key, carried through to the Payments aggregate and its downstream events (ADR-0029).
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// User initiating the payment.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Gateway-issued opaque payment-method token (e.g. Stripe 'pm_*', Adyen alphanumeric); 1-64 chars. BREAKING change in the Wave-1 closeout C-2 fix: previously typed as logicalType:uuid which blocked any real-PSP adapter swap because no real gateway issues UUID-shaped payment-method ids.
		/// </summary>
		public string PaymentMethodId
		{
			get
			{
				return this._PaymentMethodId;
			}
			set
			{
				this._PaymentMethodId = value;
			}
		}
		/// <summary>
		/// Payment amount.
		/// </summary>
		public Avro.AvroDecimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				this._Amount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code (e.g., 'USD', 'EUR').
		/// </summary>
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		/// <summary>
		/// Idempotency key for preventing duplicate payment processing.
		/// </summary>
		public string IdempotencyKey
		{
			get
			{
				return this._IdempotencyKey;
			}
			set
			{
				this._IdempotencyKey = value;
			}
		}
		/// <summary>
		/// UTC timestamp when payment was requested.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.UserId;
			case 2: return this.PaymentMethodId;
			case 3: return this.Amount;
			case 4: return this.Currency;
			case 5: return this.IdempotencyKey;
			case 6: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.PaymentMethodId = (System.String)fieldValue; break;
			case 3: this.Amount = (Avro.AvroDecimal)fieldValue; break;
			case 4: this.Currency = (System.String)fieldValue; break;
			case 5: this.IdempotencyKey = (System.String)fieldValue; break;
			case 6: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
