using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Platform.ReliableMessaging.Outbox.Core;

namespace Platform.ReliableMessaging.Outbox.EFCore;

/// <summary>
/// EF Core configuration for the OutboxMessage entity.
/// </summary>
public class OutboxMessageConfiguration : IEntityTypeConfiguration<OutboxMessage>
{
    private readonly string _schemaName;
    private readonly string _tableName;

    /// <summary>
    /// Initializes a new instance of the <see cref="OutboxMessageConfiguration"/> class.
    /// </summary>
    /// <param name="schemaName">The database schema name.</param>
    /// <param name="tableName">The table name. Defaults to "OutboxMessages".</param>
    public OutboxMessageConfiguration(string schemaName, string tableName = "OutboxMessages")
    {
        _schemaName = schemaName;
        _tableName = tableName;
    }

    /// <inheritdoc/>
    public void Configure(EntityTypeBuilder<OutboxMessage> builder)
    {
        builder.HasKey(om => om.Id);
        builder.Property(om => om.Id)
            .HasComment("PK, Identity")
            .ValueGeneratedOnAdd();

        builder.ToTable(_tableName, _schemaName,
            table => table.HasComment(
                "Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing."));

        builder.Property(om => om.TopicName)
            .HasComment("The Kafka topic where this message will be published. Set by the message producer.")
            .HasMaxLength(249)
            .IsUnicode(false)
            .IsRequired();

        builder.Property(om => om.KafkaKey)
            .HasComment(
                "Kafka Key - typically the Aggregate ID for proper event ordering and partitioning")
            .HasMaxLength(128);

        builder.Property(om => om.AvroPayload)
            .HasComment("Avro-serialized domain event payload")
            .HasColumnType("varbinary(max)");

        builder.Property(om => om.Type)
            .HasComment(
                "Avro type name of the serialized event (e.g., 'FeedbackChangedEvent') for deserialization and observability")
            .HasMaxLength(255)
            .IsUnicode(false);

        builder.Property(om => om.Headers)
            .HasComment(
                "JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. " +
                "Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.")
            .HasMaxLength(8192)
            .IsUnicode();

        builder.Property(om => om.CreatedUtc)
            .HasComment("Creation timestamp (UTC).");
    }
}
