<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Ardalis.SmartEnum"/>
        <PackageReference Include="Ardalis.Specification.EntityFrameworkCore"/>

        <PackageReference Include="StyleCop.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\platform\Platform.SharedKernel\Platform.SharedKernel.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Ordering.Application"/>
        <InternalsVisibleTo Include="Ordering.Infrastructure"/>
        <InternalsVisibleTo Include="Ordering.UnitTests"/>
    </ItemGroup>
</Project>
