DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'catalog') THEN
        CREATE SCHEMA catalog;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS catalog."__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'catalog') THEN
            CREATE SCHEMA catalog;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE TABLE catalog.categories (
        id uuid NOT NULL,
        name character varying(100) NOT NULL,
        parent_category_id uuid,
        path character varying(256) NOT NULL,
        created_utc timestamp with time zone NOT NULL,
        last_modified_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_categories PRIMARY KEY (id)
    );
    COMMENT ON TABLE catalog.categories IS 'Category aggregate — taxonomy node with materialized path.';
    COMMENT ON COLUMN catalog.categories.id IS 'Primary key (Guid v7 — time-ordered).';
    COMMENT ON COLUMN catalog.categories.name IS 'Display name (1..100).';
    COMMENT ON COLUMN catalog.categories.parent_category_id IS 'Parent category id (null for roots) — referenced by id only, no navigation.';
    COMMENT ON COLUMN catalog.categories.path IS 'Materialized closure (max depth 5).';
    COMMENT ON COLUMN catalog.categories.created_utc IS 'Row-level audit: created timestamp (UTC). Set by interceptor.';
    COMMENT ON COLUMN catalog.categories.last_modified_utc IS 'Row-level audit: last-modified timestamp (UTC). Set by interceptor.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE TABLE catalog.inbox_messages (
        message_id uuid NOT NULL,
        processed_at_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_inbox_messages PRIMARY KEY (message_id)
    );
    COMMENT ON TABLE catalog.inbox_messages IS 'Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.';
    COMMENT ON COLUMN catalog.inbox_messages.message_id IS 'Unique message identifier (Primary Key).';
    COMMENT ON COLUMN catalog.inbox_messages.processed_at_utc IS 'UTC timestamp when the message was processed.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE TABLE catalog.outbox_messages (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        topic_name character varying(249) NOT NULL,
        kafka_key character varying(128),
        avro_payload bytea NOT NULL,
        type character varying(255) NOT NULL,
        headers character varying(8192),
        created_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
    );
    COMMENT ON TABLE catalog.outbox_messages IS 'Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.';
    COMMENT ON COLUMN catalog.outbox_messages.id IS 'PK, Identity';
    COMMENT ON COLUMN catalog.outbox_messages.topic_name IS 'The Kafka topic where this message will be published. Set by the message producer.';
    COMMENT ON COLUMN catalog.outbox_messages.kafka_key IS 'Kafka Key - typically the Aggregate ID for proper event ordering and partitioning';
    COMMENT ON COLUMN catalog.outbox_messages.avro_payload IS 'Avro-serialized domain event payload';
    COMMENT ON COLUMN catalog.outbox_messages.type IS 'Avro type name of the serialized event (e.g., ''OrderConfirmedEvent'') for deserialization and observability';
    COMMENT ON COLUMN catalog.outbox_messages.headers IS 'JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.';
    COMMENT ON COLUMN catalog.outbox_messages.created_utc IS 'Creation timestamp (UTC).';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE TABLE catalog.products (
        id uuid NOT NULL,
        sku character varying(32) NOT NULL,
        name character varying(200) NOT NULL,
        description text NOT NULL,
        category_id uuid NOT NULL,
        brand_name character varying(100) NOT NULL,
        price_amount numeric(19,4) NOT NULL,
        price_currency character varying(3) NOT NULL,
        status integer NOT NULL,
        dimensions_length numeric(10,2),
        dimensions_width numeric(10,2),
        dimensions_height numeric(10,2),
        dimensions_unit character varying(8),
        created_utc timestamp with time zone NOT NULL,
        last_modified_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_products PRIMARY KEY (id)
    );
    COMMENT ON TABLE catalog.products IS 'Product aggregate — write-side state for a sellable item.';
    COMMENT ON COLUMN catalog.products.id IS 'Primary key (Guid v7 — time-ordered).';
    COMMENT ON COLUMN catalog.products.sku IS 'Business key — unique per Catalog.';
    COMMENT ON COLUMN catalog.products.name IS 'Display name (1..200).';
    COMMENT ON COLUMN catalog.products.description IS 'Long-form description; truncated to 4000 chars at write time.';
    COMMENT ON COLUMN catalog.products.category_id IS 'Catalog category identifier — referenced by id only, no navigation per arch test.';
    COMMENT ON COLUMN catalog.products.brand_name IS 'Brand name (1..100).';
    COMMENT ON COLUMN catalog.products.price_amount IS 'Price amount.';
    COMMENT ON COLUMN catalog.products.price_currency IS 'ISO 4217 currency code.';
    COMMENT ON COLUMN catalog.products.status IS 'Lifecycle status (Active|Discontinued); SmartEnum integer Value.';
    COMMENT ON COLUMN catalog.products.created_utc IS 'Row-level audit: created timestamp (UTC). Set by interceptor.';
    COMMENT ON COLUMN catalog.products.last_modified_utc IS 'Row-level audit: last-modified timestamp (UTC). Set by interceptor.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE TABLE catalog.product_search_view (
        product_id uuid NOT NULL,
        sku character varying(32) NOT NULL,
        name character varying(200) NOT NULL,
        description text NOT NULL,
        category_id uuid NOT NULL,
        category_path character varying(256) NOT NULL,
        category_breadcrumb character varying(512) NOT NULL,
        brand_name character varying(100) NOT NULL,
        price_amount numeric(19,4) NOT NULL,
        price_currency character varying(3) NOT NULL,
        status character varying(32) NOT NULL,
        dimensions_length numeric(10,2),
        dimensions_width numeric(10,2),
        dimensions_height numeric(10,2),
        dimensions_unit character varying(8),
        images_json jsonb NOT NULL DEFAULT '[]',
        is_sellable boolean NOT NULL DEFAULT FALSE,
        created_at_utc timestamp with time zone NOT NULL,
        last_updated_at_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_product_search_view PRIMARY KEY (product_id),
        CONSTRAINT ck_product_search_view_dimensions_all_or_none CHECK (num_nonnulls(dimensions_length, dimensions_width, dimensions_height, dimensions_unit) IN (0, 4)),
        CONSTRAINT fk_product_search_view_categories_category_id FOREIGN KEY (category_id) REFERENCES catalog.categories (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE catalog.product_search_view IS 'Denormalized read view of Product (catalog.md § 9). Upserted in-process by domain-event handlers in the same transaction as write-model saves.';
    COMMENT ON COLUMN catalog.product_search_view.product_id IS 'Mirrors Product.Id.';
    COMMENT ON COLUMN catalog.product_search_view.category_id IS 'Mirrors Product.CategoryId.';
    COMMENT ON COLUMN catalog.product_search_view.category_path IS 'Materialized category path; rewritten on Reparent by CategoryPathService.';
    COMMENT ON COLUMN catalog.product_search_view.category_breadcrumb IS 'Denormalized human-readable breadcrumb — may temporarily lag after Reparent.';
    COMMENT ON COLUMN catalog.product_search_view.status IS 'Lifecycle status name (Active|Discontinued).';
    COMMENT ON COLUMN catalog.product_search_view.dimensions_length IS 'Dimensions VO, flattened; all four are set together or all four are null (digital/service products).';
    COMMENT ON COLUMN catalog.product_search_view.dimensions_width IS 'Dimensions VO, flattened; all four are set together or all four are null (digital/service products).';
    COMMENT ON COLUMN catalog.product_search_view.dimensions_height IS 'Dimensions VO, flattened; all four are set together or all four are null (digital/service products).';
    COMMENT ON COLUMN catalog.product_search_view.dimensions_unit IS 'Dimensions VO, flattened; all four are set together or all four are null (digital/service products).';
    COMMENT ON COLUMN catalog.product_search_view.is_sellable IS 'Computed flag — wired up by the StockLevelChangedEvent Kafka inbox consumer.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE TABLE catalog.product_images (
        product_id uuid NOT NULL,
        ordinal integer GENERATED BY DEFAULT AS IDENTITY,
        url character varying(2048) NOT NULL,
        alt_text character varying(200) NOT NULL,
        display_order integer NOT NULL,
        CONSTRAINT pk_product_images PRIMARY KEY (product_id, ordinal),
        CONSTRAINT fk_product_images_products_product_id FOREIGN KEY (product_id) REFERENCES catalog.products (id) ON DELETE CASCADE
    );
    COMMENT ON TABLE catalog.product_images IS 'Ordered image collection — owned by the Product aggregate.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE INDEX ix_categories_path ON catalog.categories (path);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE INDEX ix_inbox_messages_processed_at_utc ON catalog.inbox_messages (processed_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE INDEX ix_product_search_view_category_id ON catalog.product_search_view (category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE INDEX ix_product_search_view_category_path ON catalog.product_search_view (category_path);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE INDEX ix_product_search_view_price_amount ON catalog.product_search_view (price_amount);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE INDEX ix_product_search_view_status ON catalog.product_search_view (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE UNIQUE INDEX ux_product_search_view_sku ON catalog.product_search_view (sku);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE INDEX ix_products_category_id ON catalog.products (category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE INDEX ix_products_status ON catalog.products (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    CREATE UNIQUE INDEX ux_products_sku ON catalog.products (sku);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM catalog."__EFMigrationsHistory" WHERE "migration_id" = '20260728225607_CreateCatalogTables') THEN
    INSERT INTO catalog."__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260728225607_CreateCatalogTables', '10.0.8');
    END IF;
END $EF$;
