<Project Sdk="Microsoft.NET.Sdk">
    <!-- Project-specific packages only (common test packages in ../../test/Directory.Build.props) -->
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="FluentResults.Extensions.FluentAssertions"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Platform.Api\Platform.Api.csproj"/>
    </ItemGroup>
</Project>
