<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Serilog.Sinks.XUnit.Injectable" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\Payments\Payments.Api\Payments.Api.csproj" />
        <ProjectReference Include="..\..\platform\Platform.Test.Framework\Platform.Test.Framework.csproj" />
        <ProjectReference Include="..\Payments.IntegrationTests\Payments.IntegrationTests.csproj" />
    </ItemGroup>
</Project>
