<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="NetArchTest.eNhancedEdition" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\Catalog\Catalog.Api\Catalog.Api.csproj" />
        <ProjectReference Include="..\..\services\Catalog\Catalog.Application\Catalog.Application.csproj" />
        <ProjectReference Include="..\..\services\Catalog\Catalog.Domain\Catalog.Domain.csproj" />
        <ProjectReference Include="..\..\services\Catalog\Catalog.Infrastructure\Catalog.Infrastructure.csproj" />
        <ProjectReference Include="..\..\platform\Platform.Test.Framework\Platform.Test.Framework.csproj" />
    </ItemGroup>
</Project>
