// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Weather.Feedback
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted when user updates their feedback. Contains complete before/after state. Compare old vs new values to determine what changed.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class FeedbackChangedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""FeedbackChangedEvent"",""doc"":""Event emitted when user updates their feedback. Contains complete before/after state. Compare old vs new values to determine what changed."",""namespace"":""Weather.Feedback"",""fields"":[{""name"":""FeedbackId"",""doc"":""Identifier of the feedback aggregate."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""UserId"",""doc"":""User who made the change."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""OldText"",""doc"":""Previous feedback text. Compare with NewText to detect changes."",""type"":""string""},{""name"":""NewText"",""doc"":""Current feedback text. If equal to OldText, text did not change."",""type"":""string""},{""name"":""OldRating"",""doc"":""Previous rating (1-5). Compare with NewRating to detect changes."",""type"":""int""},{""name"":""NewRating"",""doc"":""Current rating (1-5). If equal to OldRating, rating did not change."",""type"":""int""},{""name"":""OccurredOnUtc"",""doc"":""UTC timestamp when event occurred."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Identifier of the feedback aggregate.
		/// </summary>
		private System.Guid _FeedbackId;
		/// <summary>
		/// User who made the change.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Previous feedback text. Compare with NewText to detect changes.
		/// </summary>
		private string _OldText;
		/// <summary>
		/// Current feedback text. If equal to OldText, text did not change.
		/// </summary>
		private string _NewText;
		/// <summary>
		/// Previous rating (1-5). Compare with NewRating to detect changes.
		/// </summary>
		private int _OldRating;
		/// <summary>
		/// Current rating (1-5). If equal to OldRating, rating did not change.
		/// </summary>
		private int _NewRating;
		/// <summary>
		/// UTC timestamp when event occurred.
		/// </summary>
		private System.DateTime _OccurredOnUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return FeedbackChangedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Identifier of the feedback aggregate.
		/// </summary>
		public System.Guid FeedbackId
		{
			get
			{
				return this._FeedbackId;
			}
			set
			{
				this._FeedbackId = value;
			}
		}
		/// <summary>
		/// User who made the change.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Previous feedback text. Compare with NewText to detect changes.
		/// </summary>
		public string OldText
		{
			get
			{
				return this._OldText;
			}
			set
			{
				this._OldText = value;
			}
		}
		/// <summary>
		/// Current feedback text. If equal to OldText, text did not change.
		/// </summary>
		public string NewText
		{
			get
			{
				return this._NewText;
			}
			set
			{
				this._NewText = value;
			}
		}
		/// <summary>
		/// Previous rating (1-5). Compare with NewRating to detect changes.
		/// </summary>
		public int OldRating
		{
			get
			{
				return this._OldRating;
			}
			set
			{
				this._OldRating = value;
			}
		}
		/// <summary>
		/// Current rating (1-5). If equal to OldRating, rating did not change.
		/// </summary>
		public int NewRating
		{
			get
			{
				return this._NewRating;
			}
			set
			{
				this._NewRating = value;
			}
		}
		/// <summary>
		/// UTC timestamp when event occurred.
		/// </summary>
		public System.DateTime OccurredOnUtc
		{
			get
			{
				return this._OccurredOnUtc;
			}
			set
			{
				this._OccurredOnUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.FeedbackId;
			case 1: return this.UserId;
			case 2: return this.OldText;
			case 3: return this.NewText;
			case 4: return this.OldRating;
			case 5: return this.NewRating;
			case 6: return this.OccurredOnUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.FeedbackId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.OldText = (System.String)fieldValue; break;
			case 3: this.NewText = (System.String)fieldValue; break;
			case 4: this.OldRating = (System.Int32)fieldValue; break;
			case 5: this.NewRating = (System.Int32)fieldValue; break;
			case 6: this.OccurredOnUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
