<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AnalysisLevel>latest</AnalysisLevel>
        <AnalysisMode>All</AnalysisMode>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

        <!-- For GitVersion-->
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
        <InformationalVersion>$(Version)</InformationalVersion>
    </PropertyGroup>
</Project>
