<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <!-- MassTransit Core -->
        <PackageReference Include="MassTransit"/>
        <PackageReference Include="MassTransit.EntityFrameworkCore"/>
        <PackageReference Include="MassTransit.SqlTransport.SqlServer"/>
        <PackageReference Include="MassTransit.Kafka"/>

        <!-- Confluent Schema Registry -->
        <PackageReference Include="Confluent.SchemaRegistry"/>
        <PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro"/>

        <!-- EF Core -->
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <!-- OpenTelemetry -->
        <PackageReference Include="OpenTelemetry.Extensions.Hosting"/>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Process"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore"/>
        <PackageReference Include="OpenTelemetry.Resources.Container"/>
        <PackageReference Include="OpenTelemetry.Resources.Host"/>

        <!-- Health checks -->
        <PackageReference Include="AspNetCore.HealthChecks.Kafka"/>
        <PackageReference Include="AspNetCore.HealthChecks.ApplicationStatus"/>
        <PackageReference Include="AspNetCore.HealthChecks.UI.SqlServer.Storage"/>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore"/>

        <!-- Analyzers -->
        <PackageReference Include="StyleCop.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\platform\Platform.Avro.UniversalSerDes\Platform.Avro.UniversalSerDes.csproj" />
        <ProjectReference Include="..\..\platform\Platform.ServiceDefaults\Platform.ServiceDefaults.csproj" />
        <ProjectReference Include="..\..\platform\Platform.ReliableMessaging.Outbox.EFCore\Platform.ReliableMessaging.Outbox.EFCore.csproj" />
        <ProjectReference Include="..\..\platform\Platform.ReliableMessaging.Outbox.Core\Platform.ReliableMessaging.Outbox.Core.csproj" />
        <ProjectReference Include="..\..\platform\Platform.SchemaRegistry.Contracts\Platform.SchemaRegistry.Contracts.csproj" />
        <ProjectReference Include="..\..\platform\Platform.SharedKernel\Platform.SharedKernel.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DotNetAtlas.Sagas.IntegrationTests"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Common\Persistence\Database\Migrations\SqlScripts\" />
    </ItemGroup>

</Project>
