DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventory') THEN
        CREATE SCHEMA inventory;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS inventory."__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventory') THEN
            CREATE SCHEMA inventory;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    CREATE TABLE inventory.current_stock_levels (
        product_id uuid NOT NULL,
        on_hand integer NOT NULL,
        reserved integer NOT NULL,
        available integer NOT NULL,
        previous_available integer NOT NULL,
        last_updated_utc timestamp with time zone NOT NULL,
        last_version integer NOT NULL,
        CONSTRAINT pk_current_stock_levels PRIMARY KEY (product_id)
    );
    COMMENT ON TABLE inventory.current_stock_levels IS 'Denormalised read projection: one row per ProductId, mutated by CurrentStockLevelsProjectionDomainEventHandler on every ES event. Rebuildable from inventory.stock_events.';
    COMMENT ON COLUMN inventory.current_stock_levels.product_id IS 'Aggregate identity / stream id. Shared with Catalog''s Product.ProductId.';
    COMMENT ON COLUMN inventory.current_stock_levels.on_hand IS 'Physical units present after the last applied event.';
    COMMENT ON COLUMN inventory.current_stock_levels.reserved IS 'Active reservations total after the last applied event.';
    COMMENT ON COLUMN inventory.current_stock_levels.available IS 'OnHand - Reserved after the last applied event. Materialised for indexable reads.';
    COMMENT ON COLUMN inventory.current_stock_levels.previous_available IS 'Available BEFORE the last applied event; enables StockLevelChangedEvent threshold detection without state replay.';
    COMMENT ON COLUMN inventory.current_stock_levels.last_updated_utc IS '= OccurredOnUtc of the last applied event.';
    COMMENT ON COLUMN inventory.current_stock_levels.last_version IS 'Monotonic per-stream event count applied to this row — guards future projection rebuilds against duplicates.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    CREATE TABLE inventory.inbox_messages (
        message_id uuid NOT NULL,
        processed_at_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_inbox_messages PRIMARY KEY (message_id)
    );
    COMMENT ON TABLE inventory.inbox_messages IS 'Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.';
    COMMENT ON COLUMN inventory.inbox_messages.message_id IS 'Unique message identifier (Primary Key).';
    COMMENT ON COLUMN inventory.inbox_messages.processed_at_utc IS 'UTC timestamp when the message was processed.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    CREATE TABLE inventory.outbox_messages (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        topic_name character varying(249) NOT NULL,
        kafka_key character varying(128),
        avro_payload bytea NOT NULL,
        type character varying(255) NOT NULL,
        headers character varying(8192),
        created_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
    );
    COMMENT ON TABLE inventory.outbox_messages IS 'Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.';
    COMMENT ON COLUMN inventory.outbox_messages.id IS 'PK, Identity';
    COMMENT ON COLUMN inventory.outbox_messages.topic_name IS 'The Kafka topic where this message will be published. Set by the message producer.';
    COMMENT ON COLUMN inventory.outbox_messages.kafka_key IS 'Kafka Key - typically the Aggregate ID for proper event ordering and partitioning';
    COMMENT ON COLUMN inventory.outbox_messages.avro_payload IS 'Avro-serialized domain event payload';
    COMMENT ON COLUMN inventory.outbox_messages.type IS 'Avro type name of the serialized event (e.g., ''FeedbackChangedEvent'') for deserialization and observability';
    COMMENT ON COLUMN inventory.outbox_messages.headers IS 'JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.';
    COMMENT ON COLUMN inventory.outbox_messages.created_utc IS 'Creation timestamp (UTC).';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    CREATE TABLE inventory.reservation_audit (
        reservation_id uuid NOT NULL,
        product_id uuid NOT NULL,
        order_id uuid NOT NULL,
        quantity integer NOT NULL,
        status character varying(16) NOT NULL,
        reserved_at_utc timestamp with time zone NOT NULL,
        expires_at_utc timestamp with time zone NOT NULL,
        resolved_at_utc timestamp with time zone,
        release_reason character varying(16),
        CONSTRAINT pk_reservation_audit PRIMARY KEY (reservation_id)
    );
    COMMENT ON TABLE inventory.reservation_audit IS 'Per-reservation lifecycle projection. Inserted on StockReservedDomainEvent, terminal fields (Status, ResolvedAtUtc, ReleaseReason) mutated on Confirmed / Released. Ops + expiry-worker query surface.';
    COMMENT ON COLUMN inventory.reservation_audit.reservation_id IS 'Saga-supplied reservation id (GUIDv7).';
    COMMENT ON COLUMN inventory.reservation_audit.product_id IS 'Stream id joining back to inventory.current_stock_levels.ProductId.';
    COMMENT ON COLUMN inventory.reservation_audit.order_id IS 'Owning order. Fan-in key for saga correlation.';
    COMMENT ON COLUMN inventory.reservation_audit.quantity IS 'Units reserved. Immutable after the initial insert.';
    COMMENT ON COLUMN inventory.reservation_audit.status IS 'Lifecycle: Active -> Confirmed | Released.';
    COMMENT ON COLUMN inventory.reservation_audit.reserved_at_utc IS 'UTC timestamp the reservation was created.';
    COMMENT ON COLUMN inventory.reservation_audit.expires_at_utc IS 'UTC expiry (= ReservedAtUtc + TTL). Drives the TTL worker scan.';
    COMMENT ON COLUMN inventory.reservation_audit.resolved_at_utc IS 'UTC timestamp of the terminal transition; null while Active.';
    COMMENT ON COLUMN inventory.reservation_audit.release_reason IS 'Populated only on Status=Released (Compensation | Expiry | Cancellation).';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    CREATE TABLE inventory.stock_events (
        stream_id uuid NOT NULL,
        version integer NOT NULL,
        event_type character varying(128) NOT NULL,
        payload jsonb NOT NULL,
        occurred_at_utc timestamp with time zone NOT NULL,
        appended_at_utc timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT pk_stock_events PRIMARY KEY (stream_id, version)
    );
    COMMENT ON TABLE inventory.stock_events IS 'Append-only event store for StockItem aggregates (ADR-0006). One row per internal ES event; composite PK (StreamId, Version) is the optimistic-concurrency mechanism.';
    COMMENT ON COLUMN inventory.stock_events.stream_id IS 'Stream identity = ProductId. One stream per StockItem.';
    COMMENT ON COLUMN inventory.stock_events.version IS 'Monotonic 1-based version per stream. Enforced by PK.';
    COMMENT ON COLUMN inventory.stock_events.event_type IS 'CLR-type name discriminator (e.g. "StockReservedDomainEvent") used by the deserializer.';
    COMMENT ON COLUMN inventory.stock_events.payload IS 'JSON-serialized internal event; stored as jsonb for legibility and indexability.';
    COMMENT ON COLUMN inventory.stock_events.occurred_at_utc IS 'UTC timestamp the domain event was produced; copied from event.OccurredOnUtc for temporal queries.';
    COMMENT ON COLUMN inventory.stock_events.appended_at_utc IS 'DB-side insert timestamp; distinguishes domain time from persisted time during replay/tests.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    CREATE INDEX ix_current_stock_levels_available_low ON inventory.current_stock_levels (available) WHERE available <= 10;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    CREATE INDEX ix_inbox_messages_processed_at_utc ON inventory.inbox_messages (processed_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    CREATE INDEX ix_reservation_audit_active_expiry ON inventory.reservation_audit (expires_at_utc) WHERE status = 'Active';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    CREATE INDEX ix_reservation_audit_order ON inventory.reservation_audit (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    CREATE INDEX ix_stock_events_event_type ON inventory.stock_events (event_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    CREATE INDEX ix_stock_events_occurred_at ON inventory.stock_events (occurred_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260604194506_CreateInventoryTables') THEN
    INSERT INTO inventory."__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260604194506_CreateInventoryTables', '10.0.8');
    END IF;
END $EF$;
