
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260425111658_AddProjectionsAndOutboxInbox') THEN
    CREATE TABLE inventory.current_stock_levels (
        product_id uuid NOT NULL,
        on_hand integer NOT NULL,
        reserved integer NOT NULL,
        available integer NOT NULL,
        previous_available integer NOT NULL,
        last_updated_utc timestamp with time zone NOT NULL,
        last_version integer NOT NULL,
        CONSTRAINT pk_current_stock_levels PRIMARY KEY (product_id)
    );
    COMMENT ON TABLE inventory.current_stock_levels IS 'Denormalised read projection: one row per ProductId, mutated by CurrentStockLevelsProjectionHandler on every ES event. Rebuildable from inventory.stock_events.';
    COMMENT ON COLUMN inventory.current_stock_levels.product_id IS 'Aggregate identity / stream id. Shared with Catalog''s Product.ProductId.';
    COMMENT ON COLUMN inventory.current_stock_levels.on_hand IS 'Physical units present after the last applied event.';
    COMMENT ON COLUMN inventory.current_stock_levels.reserved IS 'Active reservations total after the last applied event.';
    COMMENT ON COLUMN inventory.current_stock_levels.available IS 'OnHand - Reserved after the last applied event. Materialised for indexable reads.';
    COMMENT ON COLUMN inventory.current_stock_levels.previous_available IS 'Available BEFORE the last applied event; enables StockLevelChanged threshold detection without state replay.';
    COMMENT ON COLUMN inventory.current_stock_levels.last_updated_utc IS '= OccurredOnUtc of the last applied event.';
    COMMENT ON COLUMN inventory.current_stock_levels.last_version IS 'Monotonic per-stream event count applied to this row — guards future projection rebuilds against duplicates.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260425111658_AddProjectionsAndOutboxInbox') THEN
    CREATE TABLE inventory."InboxMessages" (
        message_id uuid NOT NULL,
        processed_at_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_inbox_messages PRIMARY KEY (message_id)
    );
    COMMENT ON TABLE inventory."InboxMessages" IS 'Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.';
    COMMENT ON COLUMN inventory."InboxMessages".message_id IS 'Unique message identifier (Primary Key).';
    COMMENT ON COLUMN inventory."InboxMessages".processed_at_utc IS 'UTC timestamp when the message was processed.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260425111658_AddProjectionsAndOutboxInbox') THEN
    CREATE TABLE inventory."OutboxMessages" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        topic_name character varying(249) NOT NULL,
        kafka_key character varying(128),
        avro_payload bytea NOT NULL,
        type character varying(255) NOT NULL,
        headers character varying(8192),
        created_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
    );
    COMMENT ON TABLE inventory."OutboxMessages" IS 'Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.';
    COMMENT ON COLUMN inventory."OutboxMessages".id IS 'PK, Identity';
    COMMENT ON COLUMN inventory."OutboxMessages".topic_name IS 'The Kafka topic where this message will be published. Set by the message producer.';
    COMMENT ON COLUMN inventory."OutboxMessages".kafka_key IS 'Kafka Key - typically the Aggregate ID for proper event ordering and partitioning';
    COMMENT ON COLUMN inventory."OutboxMessages".avro_payload IS 'Avro-serialized domain event payload';
    COMMENT ON COLUMN inventory."OutboxMessages".type IS 'Avro type name of the serialized event (e.g., ''FeedbackChangedEvent'') for deserialization and observability';
    COMMENT ON COLUMN inventory."OutboxMessages".headers IS 'JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.';
    COMMENT ON COLUMN inventory."OutboxMessages".created_utc IS 'Creation timestamp (UTC).';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260425111658_AddProjectionsAndOutboxInbox') THEN
    CREATE TABLE inventory.reservation_audit (
        reservation_id uuid NOT NULL,
        product_id uuid NOT NULL,
        order_id uuid NOT NULL,
        quantity integer NOT NULL,
        status character varying(16) NOT NULL,
        reserved_at_utc timestamp with time zone NOT NULL,
        expires_at_utc timestamp with time zone NOT NULL,
        resolved_at_utc timestamp with time zone,
        release_reason character varying(16),
        CONSTRAINT pk_reservation_audit PRIMARY KEY (reservation_id)
    );
    COMMENT ON TABLE inventory.reservation_audit IS 'Per-reservation lifecycle projection. Inserted on StockReservedDomainEvent, terminal fields (Status, ResolvedAtUtc, ReleaseReason) mutated on Confirmed / Released. Ops + expiry-worker query surface.';
    COMMENT ON COLUMN inventory.reservation_audit.reservation_id IS 'Saga-supplied reservation id (GUIDv7).';
    COMMENT ON COLUMN inventory.reservation_audit.product_id IS 'Stream id joining back to inventory.current_stock_levels.ProductId.';
    COMMENT ON COLUMN inventory.reservation_audit.order_id IS 'Owning order. Fan-in key for saga correlation.';
    COMMENT ON COLUMN inventory.reservation_audit.quantity IS 'Units reserved. Immutable after the initial insert.';
    COMMENT ON COLUMN inventory.reservation_audit.status IS 'Lifecycle: Active -> Confirmed | Released.';
    COMMENT ON COLUMN inventory.reservation_audit.reserved_at_utc IS 'UTC timestamp the reservation was created.';
    COMMENT ON COLUMN inventory.reservation_audit.expires_at_utc IS 'UTC expiry (= ReservedAtUtc + TTL). Drives the TTL worker scan.';
    COMMENT ON COLUMN inventory.reservation_audit.resolved_at_utc IS 'UTC timestamp of the terminal transition; null while Active.';
    COMMENT ON COLUMN inventory.reservation_audit.release_reason IS 'Populated only on Status=Released (Compensation | Expiry | Cancellation).';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260425111658_AddProjectionsAndOutboxInbox') THEN
    CREATE INDEX ix_current_stock_levels_available_low ON inventory.current_stock_levels (available) WHERE available <= 10;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260425111658_AddProjectionsAndOutboxInbox') THEN
    CREATE INDEX "IX_InboxMessages_ProcessedAtUtc" ON inventory."InboxMessages" (processed_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260425111658_AddProjectionsAndOutboxInbox') THEN
    CREATE INDEX ix_reservation_audit_active_expiry ON inventory.reservation_audit (expires_at_utc) WHERE status = 'Active';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260425111658_AddProjectionsAndOutboxInbox') THEN
    CREATE INDEX ix_reservation_audit_order ON inventory.reservation_audit (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "migration_id" = '20260425111658_AddProjectionsAndOutboxInbox') THEN
    INSERT INTO inventory."__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260425111658_AddProjectionsAndOutboxInbox', '10.0.8');
    END IF;
END $EF$;
