IF OBJECT_ID(N'[payment].[__EFMigrationsHistory]') IS NULL
BEGIN
    IF SCHEMA_ID(N'payment') IS NULL EXEC(N'CREATE SCHEMA [payment];');
    CREATE TABLE [payment].[__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [payment].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260209224017_CreateInboxAndOutboxTables'
)
BEGIN
    IF SCHEMA_ID(N'payment') IS NULL EXEC(N'CREATE SCHEMA [payment];');
END;

IF NOT EXISTS (
    SELECT * FROM [payment].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260209224017_CreateInboxAndOutboxTables'
)
BEGIN
    CREATE TABLE [payment].[InboxMessages] (
        [MessageId] uniqueidentifier NOT NULL,
        [ProcessedAtUtc] datetimeoffset NOT NULL,
        CONSTRAINT [PK_InboxMessages] PRIMARY KEY ([MessageId])
    );
    DECLARE @description AS sql_variant;
    SET @description = N'Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'payment', 'TABLE', N'InboxMessages';
    SET @description = N'Unique message identifier (Primary Key).';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'payment', 'TABLE', N'InboxMessages', 'COLUMN', N'MessageId';
    SET @description = N'UTC timestamp when the message was processed.';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'payment', 'TABLE', N'InboxMessages', 'COLUMN', N'ProcessedAtUtc';
END;

IF NOT EXISTS (
    SELECT * FROM [payment].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260209224017_CreateInboxAndOutboxTables'
)
BEGIN
    CREATE TABLE [payment].[OutboxMessages] (
        [Id] bigint NOT NULL IDENTITY,
        [TopicName] varchar(249) NOT NULL,
        [KafkaKey] nvarchar(128) NULL,
        [AvroPayload] varbinary(max) NOT NULL,
        [Type] varchar(255) NOT NULL,
        [Headers] nvarchar(max) NULL,
        [CreatedUtc] datetimeoffset NOT NULL,
        CONSTRAINT [PK_OutboxMessages] PRIMARY KEY ([Id])
    );
    DECLARE @description1 AS sql_variant;
    SET @description1 = N'Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'payment', 'TABLE', N'OutboxMessages';
    SET @description1 = N'PK, Identity';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'payment', 'TABLE', N'OutboxMessages', 'COLUMN', N'Id';
    SET @description1 = N'The Kafka topic where this message will be published. Set by the message producer.';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'payment', 'TABLE', N'OutboxMessages', 'COLUMN', N'TopicName';
    SET @description1 = N'Kafka Key - typically the Aggregate ID for proper event ordering and partitioning';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'payment', 'TABLE', N'OutboxMessages', 'COLUMN', N'KafkaKey';
    SET @description1 = N'Avro-serialized domain event payload';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'payment', 'TABLE', N'OutboxMessages', 'COLUMN', N'AvroPayload';
    SET @description1 = N'Avro type name of the serialized event (e.g., ''FeedbackChangedEvent'') for deserialization and observability';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'payment', 'TABLE', N'OutboxMessages', 'COLUMN', N'Type';
    SET @description1 = N'JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'payment', 'TABLE', N'OutboxMessages', 'COLUMN', N'Headers';
    SET @description1 = N'Creation timestamp (UTC).';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'payment', 'TABLE', N'OutboxMessages', 'COLUMN', N'CreatedUtc';
END;

IF NOT EXISTS (
    SELECT * FROM [payment].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260209224017_CreateInboxAndOutboxTables'
)
BEGIN
    CREATE INDEX [IX_InboxMessages_ProcessedAtUtc] ON [payment].[InboxMessages] ([ProcessedAtUtc]);
END;

IF NOT EXISTS (
    SELECT * FROM [payment].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260209224017_CreateInboxAndOutboxTables'
)
BEGIN
    INSERT INTO [payment].[__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260209224017_CreateInboxAndOutboxTables', N'10.0.0');
END;

COMMIT;
GO

