<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="FluentResults.Extensions.FluentAssertions" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\Catalog\Catalog.API\Catalog.API.csproj" />
        <ProjectReference Include="..\..\platform\Platform.Test.Framework\Platform.Test.Framework.csproj" />
    </ItemGroup>
</Project>
