<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FastEndpoints.Attributes"/>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="Riok.Mapperly"/>
        <PackageReference Include="Serilog.AspNetCore"/>
        <PackageReference Include="Scrutor"/>
        <PackageReference Include="ZiggyCreatures.FusionCache"/>
        <PackageReference Include="ZiggyCreatures.FusionCache.Serialization.CysharpMemoryPack"/>
        <PackageReference Include="MessagePack.Annotations"/>
        <PackageReference Include="TypedSignalR.Client.Attributes"/>

        <PackageReference Include="StyleCop.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Weather.Application.IntegrationTests"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Weather.Domain\Weather.Domain.csproj" />
        <ProjectReference Include="..\..\platform\Platform.CQS\Platform.CQS.csproj" />
        <ProjectReference Include="..\..\platform\Platform.ReliableMessaging.Outbox.EFCore\Platform.ReliableMessaging.Outbox.EFCore.csproj" />
        <ProjectReference Include="..\..\platform\Platform.SchemaRegistry.Contracts\Platform.SchemaRegistry.Contracts.csproj" />
    </ItemGroup>
</Project>
