<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="EntityFrameworkCore.Exceptions.Common" />
        <PackageReference Include="KafkaFlow"/>
        <PackageReference Include="KafkaFlow.Microsoft.DependencyInjection"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>

        <PackageReference Include="StyleCop.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DotNetAtlas.Messaging.Abstractions\DotNetAtlas.Messaging.Abstractions.csproj"/>
        <ProjectReference Include="..\DotNetAtlas.ReliableMessaging.Inbox.EFCore\DotNetAtlas.ReliableMessaging.Inbox.EFCore.csproj"/>
    </ItemGroup>
</Project>
