IF OBJECT_ID(N'[saga].[__EFMigrationsHistory]') IS NULL
BEGIN
    IF SCHEMA_ID(N'saga') IS NULL EXEC(N'CREATE SCHEMA [saga];');
    CREATE TABLE [saga].[__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    IF SCHEMA_ID(N'saga') IS NULL EXEC(N'CREATE SCHEMA [saga];');
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE TABLE [saga].[OutboxMessages] (
        [Id] bigint NOT NULL IDENTITY,
        [TopicName] varchar(249) NOT NULL,
        [KafkaKey] nvarchar(128) NULL,
        [AvroPayload] varbinary(max) NOT NULL,
        [Type] varchar(255) NOT NULL,
        [Headers] nvarchar(max) NULL,
        [CreatedUtc] datetimeoffset NOT NULL,
        CONSTRAINT [PK_OutboxMessages] PRIMARY KEY ([Id])
    );
    DECLARE @description AS sql_variant;
    SET @description = N'Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'saga', 'TABLE', N'OutboxMessages';
    SET @description = N'PK, Identity';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'saga', 'TABLE', N'OutboxMessages', 'COLUMN', N'Id';
    SET @description = N'The Kafka topic where this message will be published. Set by the message producer.';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'saga', 'TABLE', N'OutboxMessages', 'COLUMN', N'TopicName';
    SET @description = N'Kafka Key - typically the Aggregate ID for proper event ordering and partitioning';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'saga', 'TABLE', N'OutboxMessages', 'COLUMN', N'KafkaKey';
    SET @description = N'Avro-serialized domain event payload';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'saga', 'TABLE', N'OutboxMessages', 'COLUMN', N'AvroPayload';
    SET @description = N'Avro type name of the serialized event (e.g., ''FeedbackChangedEvent'') for deserialization and observability';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'saga', 'TABLE', N'OutboxMessages', 'COLUMN', N'Type';
    SET @description = N'JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'saga', 'TABLE', N'OutboxMessages', 'COLUMN', N'Headers';
    SET @description = N'Creation timestamp (UTC).';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'saga', 'TABLE', N'OutboxMessages', 'COLUMN', N'CreatedUtc';
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE TABLE [saga].[PaymentSagaState] (
        [CorrelationId] uniqueidentifier NOT NULL,
        [CurrentState] nvarchar(64) NOT NULL,
        [UserId] uniqueidentifier NOT NULL,
        [PaymentMethodId] uniqueidentifier NOT NULL,
        [Amount] decimal(19,4) NOT NULL,
        [Currency] nvarchar(3) NOT NULL,
        [IdempotencyKey] nvarchar(128) NOT NULL,
        [AuthorizationId] nvarchar(256) NULL,
        [AuthorizationExpiresAtUtc] datetimeoffset NULL,
        [PaymentTransactionId] uniqueidentifier NULL,
        [InitiatedAtUtc] datetimeoffset NOT NULL,
        [CreatedUtc] datetimeoffset NOT NULL,
        [LastModifiedUtc] datetimeoffset NOT NULL,
        [AuthorizedAtUtc] datetimeoffset NULL,
        [CapturedAtUtc] datetimeoffset NULL,
        [AuthorizationRetryCount] int NOT NULL DEFAULT 0,
        [CaptureRetryCount] int NOT NULL DEFAULT 0,
        [ErrorCode] nvarchar(64) NULL,
        [ErrorMessage] nvarchar(2048) NULL,
        [CompensationTriggered] bit NOT NULL,
        [CompensationCompletedAtUtc] datetimeoffset NULL,
        [RowVersion] rowversion NULL,
        [AuthorizationTimeoutTokenId] uniqueidentifier NULL,
        [CaptureTimeoutTokenId] uniqueidentifier NULL,
        [VoidTimeoutTokenId] uniqueidentifier NULL,
        [RefundTimeoutTokenId] uniqueidentifier NULL,
        [SuccessFinalizationTimeoutTokenId] uniqueidentifier NULL,
        CONSTRAINT [PK_PaymentSagaState] PRIMARY KEY ([CorrelationId])
    );
    DECLARE @description1 AS sql_variant;
    SET @description1 = N'Saga state for payment processing orchestration.';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState';
    SET @description1 = N'Unique correlation ID for the payment saga';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'CorrelationId';
    SET @description1 = N'Current state of the saga state machine';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'CurrentState';
    SET @description1 = N'User initiating the payment';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'UserId';
    SET @description1 = N'ID of the saved payment method';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'PaymentMethodId';
    SET @description1 = N'Payment amount';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'Amount';
    SET @description1 = N'ISO 4217 currency code';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'Currency';
    SET @description1 = N'Idempotency key to prevent duplicate processing';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'IdempotencyKey';
    SET @description1 = N'Authorization ID from payment provider';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'AuthorizationId';
    SET @description1 = N'UTC timestamp when authorization expires';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'AuthorizationExpiresAtUtc';
    SET @description1 = N'Payment transaction ID after capture';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'PaymentTransactionId';
    SET @description1 = N'UTC timestamp when payment was initiated';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'InitiatedAtUtc';
    SET @description1 = N'UTC timestamp when saga was created';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'CreatedUtc';
    SET @description1 = N'UTC timestamp when saga was last updated';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'LastModifiedUtc';
    SET @description1 = N'UTC timestamp when authorization completed';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'AuthorizedAtUtc';
    SET @description1 = N'UTC timestamp when capture completed';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'CapturedAtUtc';
    SET @description1 = N'Number of authorization retry attempts';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'AuthorizationRetryCount';
    SET @description1 = N'Number of capture retry attempts';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'CaptureRetryCount';
    SET @description1 = N'Error code for categorized failure handling';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'ErrorCode';
    SET @description1 = N'Error message if failed';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'ErrorMessage';
    SET @description1 = N'Whether compensation has been triggered';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'CompensationTriggered';
    SET @description1 = N'UTC timestamp when compensation completed';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'CompensationCompletedAtUtc';
    SET @description1 = N'Optimistic concurrency token.';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'RowVersion';
    SET @description1 = N'Token ID for authorization timeout scheduler - set when schedule is active';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'AuthorizationTimeoutTokenId';
    SET @description1 = N'Token ID for capture timeout scheduler - set when schedule is active';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'CaptureTimeoutTokenId';
    SET @description1 = N'Token ID for void timeout scheduler - set when schedule is active';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'VoidTimeoutTokenId';
    SET @description1 = N'Token ID for refund timeout scheduler - set when schedule is active';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'RefundTimeoutTokenId';
    SET @description1 = N'Token ID for success finalization timeout scheduler - set when schedule is active';
    EXEC sp_addextendedproperty 'MS_Description', @description1, 'SCHEMA', N'saga', 'TABLE', N'PaymentSagaState', 'COLUMN', N'SuccessFinalizationTimeoutTokenId';
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE TABLE [saga].[SubscriptionExtensionSagaState] (
        [CorrelationId] uniqueidentifier NOT NULL,
        [CurrentState] nvarchar(64) NOT NULL,
        [UserId] uniqueidentifier NOT NULL,
        [PaymentMethodId] uniqueidentifier NOT NULL,
        [DurationDays] int NOT NULL,
        [Amount] decimal(19,4) NOT NULL,
        [Currency] nvarchar(3) NOT NULL,
        [IdempotencyKey] nvarchar(128) NOT NULL,
        [PaymentTransactionId] uniqueidentifier NULL,
        [ExtensionInitiatedAtUtc] datetimeoffset NOT NULL,
        [PaymentCompletedAtUtc] datetimeoffset NULL,
        [CreatedUtc] datetimeoffset NOT NULL,
        [LastModifiedUtc] datetimeoffset NOT NULL,
        [ExtensionCompletedAtUtc] datetimeoffset NULL,
        [NewExpiresAtUtc] datetimeoffset NULL,
        [ErrorMessage] nvarchar(2048) NULL,
        [ErrorCode] nvarchar(64) NULL,
        [CompensationTriggered] bit NOT NULL,
        [CompensationCompletedAtUtc] datetimeoffset NULL,
        [RowVersion] rowversion NULL,
        [PaymentTimeoutTokenId] uniqueidentifier NULL,
        [ExtensionTimeoutTokenId] uniqueidentifier NULL,
        [CompensationTimeoutTokenId] uniqueidentifier NULL,
        CONSTRAINT [PK_SubscriptionExtensionSagaState] PRIMARY KEY ([CorrelationId])
    );
    DECLARE @description2 AS sql_variant;
    SET @description2 = N'Saga state for subscription extension orchestration.';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState';
    SET @description2 = N'PK - Unique correlation ID (also PaymentTransactionId)';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'CorrelationId';
    SET @description2 = N'Current state of the saga state machine';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'CurrentState';
    SET @description2 = N'User who is extending the subscription';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'UserId';
    SET @description2 = N'ID of the saved payment method';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'PaymentMethodId';
    SET @description2 = N'Subscription extension duration in days';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'DurationDays';
    SET @description2 = N'Payment amount';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'Amount';
    SET @description2 = N'ISO 4217 currency code';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'Currency';
    SET @description2 = N'Idempotency key to prevent duplicate extensions';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'IdempotencyKey';
    SET @description2 = N'Payment transaction ID (set after payment completes)';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'PaymentTransactionId';
    SET @description2 = N'UTC timestamp when extension was initiated';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'ExtensionInitiatedAtUtc';
    SET @description2 = N'UTC timestamp when payment completed (null if not completed)';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'PaymentCompletedAtUtc';
    SET @description2 = N'UTC timestamp when saga was created';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'CreatedUtc';
    SET @description2 = N'UTC timestamp when saga was last updated';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'LastModifiedUtc';
    SET @description2 = N'UTC timestamp when extension completed (null if not completed)';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'ExtensionCompletedAtUtc';
    SET @description2 = N'New subscription expiration date after extension (null if not completed)';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'NewExpiresAtUtc';
    SET @description2 = N'Error message if failed';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'ErrorMessage';
    SET @description2 = N'Error code for categorized failure handling';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'ErrorCode';
    SET @description2 = N'Whether compensation (refund) has been triggered';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'CompensationTriggered';
    SET @description2 = N'UTC timestamp when compensation completed';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'CompensationCompletedAtUtc';
    SET @description2 = N'Optimistic concurrency token.';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'RowVersion';
    SET @description2 = N'Token ID for payment timeout scheduler - set when schedule is active';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'PaymentTimeoutTokenId';
    SET @description2 = N'Token ID for extension timeout scheduler - set when schedule is active';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'ExtensionTimeoutTokenId';
    SET @description2 = N'Token ID for compensation timeout scheduler - set when schedule is active';
    EXEC sp_addextendedproperty 'MS_Description', @description2, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionExtensionSagaState', 'COLUMN', N'CompensationTimeoutTokenId';
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE TABLE [saga].[SubscriptionPurchaseSagaState] (
        [CorrelationId] uniqueidentifier NOT NULL,
        [CurrentState] nvarchar(64) NOT NULL,
        [UserId] uniqueidentifier NOT NULL,
        [PaymentMethodId] uniqueidentifier NOT NULL,
        [SubscriptionTier] int NOT NULL,
        [DurationDays] int NOT NULL,
        [Amount] decimal(19,4) NOT NULL,
        [Currency] nvarchar(3) NOT NULL,
        [IdempotencyKey] nvarchar(128) NOT NULL,
        [PaymentTransactionId] uniqueidentifier NULL,
        [PurchaseInitiatedUtc] datetimeoffset NOT NULL,
        [PaymentCompletedUtc] datetimeoffset NULL,
        [CreatedUtc] datetimeoffset NOT NULL,
        [LastModifiedUtc] datetimeoffset NOT NULL,
        [ActivationCompletedUtc] datetimeoffset NULL,
        [ErrorMessage] nvarchar(2048) NULL,
        [ErrorCode] nvarchar(64) NULL,
        [CompensationTriggered] bit NOT NULL,
        [CompensationCompletedUtc] datetimeoffset NULL,
        [RowVersion] rowversion NULL,
        [PaymentTimeoutTokenId] uniqueidentifier NULL,
        [ActivationTimeoutTokenId] uniqueidentifier NULL,
        [CompensationTimeoutTokenId] uniqueidentifier NULL,
        CONSTRAINT [PK_SubscriptionPurchaseSagaState] PRIMARY KEY ([CorrelationId])
    );
    DECLARE @description3 AS sql_variant;
    SET @description3 = N'Saga state for subscription purchase orchestration.';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState';
    SET @description3 = N'PK - Unique correlation ID (also PaymentTransactionId)';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'CorrelationId';
    SET @description3 = N'Current state of the saga state machine';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'CurrentState';
    SET @description3 = N'User who purchased the subscription';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'UserId';
    SET @description3 = N'ID of the saved payment method';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'PaymentMethodId';
    SET @description3 = N'Subscription tier (Pro, Ultra)';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'SubscriptionTier';
    SET @description3 = N'Subscription duration in days';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'DurationDays';
    SET @description3 = N'Payment amount';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'Amount';
    SET @description3 = N'ISO 4217 currency code';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'Currency';
    SET @description3 = N'Idempotency key to prevent duplicate purchases';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'IdempotencyKey';
    SET @description3 = N'Payment transaction ID (set after payment completes)';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'PaymentTransactionId';
    SET @description3 = N'UTC timestamp when purchase was initiated';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'PurchaseInitiatedUtc';
    SET @description3 = N'UTC timestamp when payment completed (null if not completed)';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'PaymentCompletedUtc';
    SET @description3 = N'UTC timestamp when saga was created';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'CreatedUtc';
    SET @description3 = N'UTC timestamp when saga was last updated';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'LastModifiedUtc';
    SET @description3 = N'UTC timestamp when activation completed (null if not completed)';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'ActivationCompletedUtc';
    SET @description3 = N'Error message if failed';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'ErrorMessage';
    SET @description3 = N'Error code for categorized failure handling';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'ErrorCode';
    SET @description3 = N'Whether compensation (refund) has been triggered';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'CompensationTriggered';
    SET @description3 = N'UTC timestamp when compensation completed';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'CompensationCompletedUtc';
    SET @description3 = N'Optimistic concurrency token.';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'RowVersion';
    SET @description3 = N'Token ID for payment timeout scheduler - set when schedule is active';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'PaymentTimeoutTokenId';
    SET @description3 = N'Token ID for activation timeout scheduler - set when schedule is active';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'ActivationTimeoutTokenId';
    SET @description3 = N'Token ID for compensation timeout scheduler - set when schedule is active';
    EXEC sp_addextendedproperty 'MS_Description', @description3, 'SCHEMA', N'saga', 'TABLE', N'SubscriptionPurchaseSagaState', 'COLUMN', N'CompensationTimeoutTokenId';
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_PaymentSagaState_CurrentState] ON [saga].[PaymentSagaState] ([CurrentState]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE UNIQUE INDEX [IX_PaymentSagaState_IdempotencyKey] ON [saga].[PaymentSagaState] ([IdempotencyKey]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_PaymentSagaState_State_Created] ON [saga].[PaymentSagaState] ([CurrentState], [CreatedUtc]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_PaymentSagaState_State_LastUpdated] ON [saga].[PaymentSagaState] ([CurrentState], [LastModifiedUtc]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_PaymentSagaState_UserId] ON [saga].[PaymentSagaState] ([UserId]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_SubscriptionExtensionSagaState_CurrentState] ON [saga].[SubscriptionExtensionSagaState] ([CurrentState]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE UNIQUE INDEX [IX_SubscriptionExtensionSagaState_IdempotencyKey] ON [saga].[SubscriptionExtensionSagaState] ([IdempotencyKey]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_SubscriptionExtensionSagaState_State_Created] ON [saga].[SubscriptionExtensionSagaState] ([CurrentState], [CreatedUtc]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_SubscriptionExtensionSagaState_State_LastUpdated] ON [saga].[SubscriptionExtensionSagaState] ([CurrentState], [LastModifiedUtc]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_SubscriptionExtensionSagaState_UserId] ON [saga].[SubscriptionExtensionSagaState] ([UserId]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_SubscriptionPurchaseSagaState_CurrentState] ON [saga].[SubscriptionPurchaseSagaState] ([CurrentState]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE UNIQUE INDEX [IX_SubscriptionPurchaseSagaState_IdempotencyKey] ON [saga].[SubscriptionPurchaseSagaState] ([IdempotencyKey]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_SubscriptionPurchaseSagaState_State_Created] ON [saga].[SubscriptionPurchaseSagaState] ([CurrentState], [CreatedUtc]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_SubscriptionPurchaseSagaState_State_LastUpdated] ON [saga].[SubscriptionPurchaseSagaState] ([CurrentState], [LastModifiedUtc]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    CREATE INDEX [IX_SubscriptionPurchaseSagaState_UserId] ON [saga].[SubscriptionPurchaseSagaState] ([UserId]);
END;

IF NOT EXISTS (
    SELECT * FROM [saga].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260206122605_Asdf'
)
BEGIN
    INSERT INTO [saga].[__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260206122605_Asdf', N'10.0.0');
END;

COMMIT;
GO

