<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>

        <PackageReference Include="FastEndpoints"/>
        <PackageReference Include="FastEndpoints.Swagger"/>
        <PackageReference Include="FluentResults"/>
        <PackageReference Include="FluentValidation"/>

        <PackageReference Include="StyleCop.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Platform.SharedKernel\Platform.SharedKernel.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Platform.Api.UnitTests"/>
    </ItemGroup>
</Project>
