BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [weather].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20251112184015_CreateOutboxMessagesTable'
)
BEGIN
    CREATE TABLE [weather].[OutboxMessages] (
        [Id] bigint NOT NULL IDENTITY,
        [KafkaKey] nvarchar(128) NULL,
        [AvroPayload] varbinary(max) NOT NULL,
        [Type] varchar(255) NOT NULL,
        [Headers] nvarchar(max) NULL,
        [CreatedUtc] datetimeoffset NOT NULL,
        CONSTRAINT [PK_OutboxMessages] PRIMARY KEY ([Id])
    );
    DECLARE @description AS sql_variant;
    SET @description = N'Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'weather', 'TABLE', N'OutboxMessages';
    SET @description = N'PK, Identity';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'weather', 'TABLE', N'OutboxMessages', 'COLUMN', N'Id';
    SET @description = N'Kafka Key - typically the Aggregate ID for proper event ordering and partitioning';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'weather', 'TABLE', N'OutboxMessages', 'COLUMN', N'KafkaKey';
    SET @description = N'Avro-serialized domain event payload';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'weather', 'TABLE', N'OutboxMessages', 'COLUMN', N'AvroPayload';
    SET @description = N'Avro type name of the serialized event (e.g., ''FeedbackChangedEvent'') used for type-based topic routing';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'weather', 'TABLE', N'OutboxMessages', 'COLUMN', N'Type';
    SET @description = N'JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'weather', 'TABLE', N'OutboxMessages', 'COLUMN', N'Headers';
    SET @description = N'Creation timestamp (UTC).';
    EXEC sp_addextendedproperty 'MS_Description', @description, 'SCHEMA', N'weather', 'TABLE', N'OutboxMessages', 'COLUMN', N'CreatedUtc';
END;

IF NOT EXISTS (
    SELECT * FROM [weather].[__EFMigrationsHistory]
    WHERE [MigrationId] = N'20251112184015_CreateOutboxMessagesTable'
)
BEGIN
    INSERT INTO [weather].[__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20251112184015_CreateOutboxMessagesTable', N'10.0.0-rc.1.25451.107');
END;

COMMIT;
GO

