// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Inventory.Reservations
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Command to release an Active reservation without confirming it (saga compensation, TTL expiry, or admin cancel). Inventory emits ReservationReleasedEvent with the specified ReleaseReason.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class ReleaseReservationCommand : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ReleaseReservationCommand"",""doc"":""Command to release an Active reservation without confirming it (saga compensation, TTL expiry, or admin cancel). Inventory emits ReservationReleasedEvent with the specified ReleaseReason."",""namespace"":""Inventory.Reservations"",""fields"":[{""name"":""ProductId"",""doc"":""Product whose reservation to release."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""ReservationId"",""doc"":""Reservation to release. Must refer to an Active reservation."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""ReleaseReason"",""doc"":""Compensation = saga rollback; Expiry = TTL worker auto-release; Cancellation = explicit customer/ops action. Propagates to ReservationReleasedEvent.ReleaseReason. Shares the ReleaseReason enum defined by ReservationReleasedEvent.avsc."",""type"":{""type"":""enum"",""name"":""ReleaseReason"",""namespace"":""Inventory.Reservations"",""symbols"":[""Compensation"",""Expiry"",""Cancellation""]}},{""name"":""RequestedAtUtc"",""doc"":""UTC timestamp when the saga issued the command."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Product whose reservation to release.
		/// </summary>
		private System.Guid _ProductId;
		/// <summary>
		/// Reservation to release. Must refer to an Active reservation.
		/// </summary>
		private System.Guid _ReservationId;
		/// <summary>
		/// Compensation = saga rollback; Expiry = TTL worker auto-release; Cancellation = explicit customer/ops action. Propagates to ReservationReleasedEvent.ReleaseReason. Shares the ReleaseReason enum defined by ReservationReleasedEvent.avsc.
		/// </summary>
		private Inventory.Reservations.ReleaseReason _ReleaseReason;
		/// <summary>
		/// UTC timestamp when the saga issued the command.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ReleaseReservationCommand._SCHEMA;
			}
		}
		/// <summary>
		/// Product whose reservation to release.
		/// </summary>
		public System.Guid ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				this._ProductId = value;
			}
		}
		/// <summary>
		/// Reservation to release. Must refer to an Active reservation.
		/// </summary>
		public System.Guid ReservationId
		{
			get
			{
				return this._ReservationId;
			}
			set
			{
				this._ReservationId = value;
			}
		}
		/// <summary>
		/// Compensation = saga rollback; Expiry = TTL worker auto-release; Cancellation = explicit customer/ops action. Propagates to ReservationReleasedEvent.ReleaseReason. Shares the ReleaseReason enum defined by ReservationReleasedEvent.avsc.
		/// </summary>
		public Inventory.Reservations.ReleaseReason ReleaseReason
		{
			get
			{
				return this._ReleaseReason;
			}
			set
			{
				this._ReleaseReason = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the saga issued the command.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ProductId;
			case 1: return this.ReservationId;
			case 2: return this.ReleaseReason;
			case 3: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ProductId = (System.Guid)fieldValue; break;
			case 1: this.ReservationId = (System.Guid)fieldValue; break;
			case 2: this.ReleaseReason = (Inventory.Reservations.ReleaseReason)fieldValue; break;
			case 3: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
