// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Inventory.Reservations
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Command issued by the Checkout saga to reserve N units of one product for an order. The saga issues one command per line item; Inventory responds asynchronously with StockReservedEvent on success or StockReservationFailedEvent on failure.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class ReserveStockCommand : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ReserveStockCommand"",""doc"":""Command issued by the Checkout saga to reserve N units of one product for an order. The saga issues one command per line item; Inventory responds asynchronously with StockReservedEvent on success or StockReservationFailedEvent on failure."",""namespace"":""Inventory.Reservations"",""fields"":[{""name"":""OrderId"",""doc"":""Order for which stock is being reserved. Used by Inventory to tag the reservation."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""ProductId"",""doc"":""Product to reserve. Keys the event-sourced stream in Inventory."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""ReservationId"",""doc"":""Saga-generated reservation id (GUIDv7). Becomes the ReservationId on StockReservedEvent / ReservationConfirmedEvent / ReservationReleasedEvent."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Quantity"",""doc"":""Units to reserve (>= 1)."",""type"":""int""},{""name"":""RequestedAtUtc"",""doc"":""UTC timestamp when the saga issued the command."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Order for which stock is being reserved. Used by Inventory to tag the reservation.
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// Product to reserve. Keys the event-sourced stream in Inventory.
		/// </summary>
		private System.Guid _ProductId;
		/// <summary>
		/// Saga-generated reservation id (GUIDv7). Becomes the ReservationId on StockReservedEvent / ReservationConfirmedEvent / ReservationReleasedEvent.
		/// </summary>
		private System.Guid _ReservationId;
		/// <summary>
		/// Units to reserve (>= 1).
		/// </summary>
		private int _Quantity;
		/// <summary>
		/// UTC timestamp when the saga issued the command.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ReserveStockCommand._SCHEMA;
			}
		}
		/// <summary>
		/// Order for which stock is being reserved. Used by Inventory to tag the reservation.
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// Product to reserve. Keys the event-sourced stream in Inventory.
		/// </summary>
		public System.Guid ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				this._ProductId = value;
			}
		}
		/// <summary>
		/// Saga-generated reservation id (GUIDv7). Becomes the ReservationId on StockReservedEvent / ReservationConfirmedEvent / ReservationReleasedEvent.
		/// </summary>
		public System.Guid ReservationId
		{
			get
			{
				return this._ReservationId;
			}
			set
			{
				this._ReservationId = value;
			}
		}
		/// <summary>
		/// Units to reserve (>= 1).
		/// </summary>
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				this._Quantity = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the saga issued the command.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.ProductId;
			case 2: return this.ReservationId;
			case 3: return this.Quantity;
			case 4: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Guid)fieldValue; break;
			case 1: this.ProductId = (System.Guid)fieldValue; break;
			case 2: this.ReservationId = (System.Guid)fieldValue; break;
			case 3: this.Quantity = (System.Int32)fieldValue; break;
			case 4: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
