// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Inventory.Reservations
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    /// <summary>
    /// Command issued by the Checkout saga to reserve N units of one product for an order. The saga issues one command per line item; Inventory responds asynchronously with StockReservedEvent on success or StockReservationFailedEvent on failure.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
    public partial class ReserveStockCommand : global::Avro.Specific.ISpecificRecord
    {
        public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(
            "{\"type\":\"record\",\"name\":\"ReserveStockCommand\",\"doc\":\"Command issued by the Checko" +
            "ut saga to reserve N units of one product for an order. The saga issues one co" +
            "mmand per line item; Inventory responds asynchronously with StockReservedEvent" +
            " on success or StockReservationFailedEvent on failure.\",\"namespace\":\"Inventory." +
            "Reservations\",\"fields\":[{\"name\":\"CorrelationId\",\"doc\":\"Checkout saga correlation" +
            " id. Also the Kafka message key.\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}" +
            "},{\"name\":\"OrderId\",\"doc\":\"Order for which stock is being reserved. Used by Inv" +
            "entory to tag the reservation.\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}}," +
            "{\"name\":\"ProductId\",\"doc\":\"Product to reserve. Keys the event-sourced stream in" +
            " Inventory.\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"Reservatio" +
            "nId\",\"doc\":\"Saga-generated reservation id (GUIDv7). Becomes the ReservationId o" +
            "n StockReservedEvent / ReservationConfirmedEvent / ReservationReleasedEvent.\"," +
            "\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"Quantity\",\"doc\":\"Units t" +
            "o reserve (>= 1).\",\"type\":\"int\"},{\"name\":\"RequestedAtUtc\",\"doc\":\"UTC timestamp " +
            "when the saga issued the command.\",\"type\":{\"type\":\"long\",\"logicalType\":\"timest" +
            "amp-millis\"}}]}");

        private System.Guid _CorrelationId;
        private System.Guid _OrderId;
        private System.Guid _ProductId;
        private System.Guid _ReservationId;
        private int _Quantity;
        private System.DateTime _RequestedAtUtc;

        public virtual global::Avro.Schema Schema => ReserveStockCommand._SCHEMA;

        public System.Guid CorrelationId { get => this._CorrelationId; set => this._CorrelationId = value; }
        public System.Guid OrderId { get => this._OrderId; set => this._OrderId = value; }
        public System.Guid ProductId { get => this._ProductId; set => this._ProductId = value; }
        public System.Guid ReservationId { get => this._ReservationId; set => this._ReservationId = value; }
        public int Quantity { get => this._Quantity; set => this._Quantity = value; }
        public System.DateTime RequestedAtUtc { get => this._RequestedAtUtc; set => this._RequestedAtUtc = value; }

        public virtual object Get(int fieldPos)
        {
            switch (fieldPos)
            {
            case 0: return this.CorrelationId;
            case 1: return this.OrderId;
            case 2: return this.ProductId;
            case 3: return this.ReservationId;
            case 4: return this.Quantity;
            case 5: return this.RequestedAtUtc;
            default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            }
        }

        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
            case 0: this.CorrelationId = (System.Guid)fieldValue; break;
            case 1: this.OrderId = (System.Guid)fieldValue; break;
            case 2: this.ProductId = (System.Guid)fieldValue; break;
            case 3: this.ReservationId = (System.Guid)fieldValue; break;
            case 4: this.Quantity = (int)fieldValue; break;
            case 5: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
            default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            }
        }
    }
}
