###
# @name SendFeedback
POST {{AppHostAddress}}/api/v1/weather/feedback
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "feedback": "Your radar is my spirit animal. Dodged the storm like Neo",
  "rating": 5
}
