###
# @name SendFeedback
POST {{AppHostAddress}}/api/v1/weather/feedback
Authorization: Bearer {{$auth.token("keycloak-local")}}
Content-Type: application/json

{
  "feedback": "Your radar is my spirit animal. Dodged the storm like Neo",
  "rating": 5
}
