using DotNetAtlas.Outbox.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DotNetAtlas.Outbox.EntityFrameworkCore.EntityConfiguration;

/// <summary>
/// EF Core configuration for the OutboxMessage entity.
/// </summary>
public class OutboxMessageConfiguration : IEntityTypeConfiguration<OutboxMessage>
{
    private readonly string _schemaName;
    private readonly string _tableName;

    public OutboxMessageConfiguration(string schemaName, string tableName = "OutboxMessages")
    {
        _schemaName = schemaName;
        _tableName = tableName;
    }

    public void Configure(EntityTypeBuilder<OutboxMessage> builder)
    {
        builder.HasKey(om => om.Id);
        builder.Property(om => om.Id)
            .HasComment("PK, Identity")
            .ValueGeneratedOnAdd();

        builder.ToTable(_tableName, _schemaName,
            table => table.HasComment(
                "Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing."));

        builder.Property(om => om.KafkaKey)
            .HasComment(
                "Kafka Key - typically the Aggregate ID for proper event ordering and partitioning")
            .HasMaxLength(36);

        builder.Property(om => om.AvroPayload)
            .HasComment("Avro-serialized domain event payload")
            .HasColumnType("varbinary(max)");

        builder.Property(om => om.Type)
            .HasComment(
                "Avro type name of the serialized event (e.g., 'FeedbackChangedEvent') used for type-based topic routing")
            .HasMaxLength(255)
            .IsUnicode(false);

        builder.Property(om => om.Headers)
            .HasComment(
                "JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. " +
                "Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.")
            .HasMaxLength(8192)
            .IsUnicode(false);

        builder.Property(om => om.CreatedUtc)
            .HasComment("Creation timestamp (UTC).");
    }
}
