<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp" />
        <PackageReference Include="FluentResults.Extensions.FluentAssertions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\Inventory\Inventory.Domain\Inventory.Domain.csproj" />
        <ProjectReference Include="..\..\services\Inventory\Inventory.Application\Inventory.Application.csproj" />
    </ItemGroup>
</Project>
