using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Payments.Infrastructure.Persistence.Database.Migrations
{
    /// <inheritdoc />
    public partial class Init_Payments : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "payments");

            migrationBuilder.CreateTable(
                name: "InboxMessages",
                schema: "payments",
                columns: table => new
                {
                    message_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Unique message identifier (Primary Key)."),
                    processed_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "UTC timestamp when the message was processed.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_inbox_messages", x => x.message_id);
                },
                comment: "Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.");

            migrationBuilder.CreateTable(
                name: "OutboxMessages",
                schema: "payments",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false, comment: "PK, Identity")
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    topic_name = table.Column<string>(type: "character varying(249)", unicode: false, maxLength: 249, nullable: false, comment: "The Kafka topic where this message will be published. Set by the message producer."),
                    kafka_key = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true, comment: "Kafka Key - typically the Aggregate ID for proper event ordering and partitioning"),
                    avro_payload = table.Column<byte[]>(type: "bytea", nullable: false, comment: "Avro-serialized domain event payload"),
                    type = table.Column<string>(type: "character varying(255)", unicode: false, maxLength: 255, nullable: false, comment: "Avro type name of the serialized event (e.g., 'FeedbackChangedEvent') for deserialization and observability"),
                    headers = table.Column<string>(type: "character varying(8192)", maxLength: 8192, nullable: true, comment: "JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation."),
                    created_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "Creation timestamp (UTC).")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_outbox_messages", x => x.id);
                },
                comment: "Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.");

            migrationBuilder.CreateTable(
                name: "payment_transactions",
                schema: "payments",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Primary key (Guid v7 — time-ordered)."),
                    correlation_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Originating saga correlation id. Idempotency key for the saga-issued AuthorizePaymentCommand."),
                    buyer_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "JWT sub of the buyer the payment is for."),
                    order_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Ordering aggregate id this payment is attached to (frozen at creation; debugging/admin-lookup convenience)."),
                    amount = table.Column<decimal>(type: "numeric(19,4)", precision: 19, scale: 4, nullable: false, comment: "Payment amount."),
                    amount_currency = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false, comment: "ISO 4217 currency code."),
                    payment_method_id_enc = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false, comment: "PII (ADR-0011): gateway-issued tokenised payment instrument. v1 plaintext; v2 encrypts."),
                    status = table.Column<int>(type: "integer", nullable: false, comment: "Lifecycle status (Requested / Authorized / Captured / Completed / Failed / Voided / Refunded)."),
                    gateway_transaction_id_enc = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true, comment: "Sensitive token (ADR-0011): gateway transaction reference; null until first successful gateway call. v1 plaintext; v2 encrypts."),
                    gateway_response_code = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true, comment: "Last observed gateway response code (forensic; not used for control flow)."),
                    gateway_response_message = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: true, comment: "Last observed gateway response human-readable message."),
                    authorized_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "UTC timestamp when authorize succeeded (nullable)."),
                    captured_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "UTC timestamp when capture succeeded (nullable)."),
                    completed_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "UTC timestamp when capture auto-advanced to Completed (nullable)."),
                    refunded_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "UTC timestamp when refund completed (nullable)."),
                    voided_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "UTC timestamp when authorization was voided (nullable)."),
                    failure_reason = table.Column<int>(type: "integer", nullable: true, comment: "Classified terminal failure reason."),
                    failure_gateway_code = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true, comment: "Raw gateway code at failure time (nullable when gateway returned no code)."),
                    failure_recorded_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "UTC timestamp when the failure was observed and recorded on the aggregate."),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false, comment: "Optimistic concurrency token (Postgres xmin system column).")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_payment_transactions", x => x.id);
                },
                comment: "PaymentTransaction aggregate — saga-scoped lifecycle from Requested through Completed/Failed/Voided/Refunded.");

            migrationBuilder.CreateIndex(
                name: "IX_InboxMessages_ProcessedAtUtc",
                schema: "payments",
                table: "InboxMessages",
                column: "processed_at_utc");

            migrationBuilder.CreateIndex(
                name: "IX_PaymentTransactions_BuyerId",
                schema: "payments",
                table: "payment_transactions",
                column: "buyer_id");

            migrationBuilder.CreateIndex(
                name: "IX_PaymentTransactions_OrderId",
                schema: "payments",
                table: "payment_transactions",
                column: "order_id");

            migrationBuilder.CreateIndex(
                name: "UX_PaymentTransactions_CorrelationId",
                schema: "payments",
                table: "payment_transactions",
                column: "correlation_id",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "InboxMessages",
                schema: "payments");

            migrationBuilder.DropTable(
                name: "OutboxMessages",
                schema: "payments");

            migrationBuilder.DropTable(
                name: "payment_transactions",
                schema: "payments");
        }
    }
}
