// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payments.Infrastructure.Persistence.Database;

#nullable disable

namespace Payments.Infrastructure.Persistence.Database.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20260531235922_CreatePaymentsTables")]
    partial class CreatePaymentsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payments.Domain.Transactions.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Primary key. v1 collapse: PaymentId == saga CorrelationId (Guid v4, random). Index locality is therefore random, not time-ordered. See docs/bc-design/payments.md § 2.1 + Wave-1 closeout H-7.");

                    b.Property<DateTimeOffset?>("AuthorizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authorized_at_utc")
                        .HasComment("UTC timestamp when authorize succeeded (nullable).");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id")
                        .HasComment("JWT sub of the buyer the payment is for.");

                    b.Property<DateTimeOffset?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc")
                        .HasComment("UTC timestamp when capture succeeded (nullable).");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc")
                        .HasComment("UTC timestamp when capture auto-advanced to Completed (nullable).");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id")
                        .HasComment("Originating saga correlation id. Idempotency key for the saga-issued AuthorizePaymentCommand.");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("gateway_transaction_id_enc")
                        .HasComment("Sensitive token (ADR-0011): gateway transaction reference; null until first successful gateway call. v1 plaintext; v2 encrypts.");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id")
                        .HasComment("Ordering aggregate id this payment is attached to (frozen at creation; debugging/admin-lookup convenience).");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_method_id_enc")
                        .HasComment("PII (ADR-0011): gateway-issued tokenised payment instrument. v1 plaintext; v2 encrypts.");

                    b.Property<DateTimeOffset?>("RefundedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at_utc")
                        .HasComment("UTC timestamp when refund completed (nullable).");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComment("Optimistic concurrency token (Postgres xmin system column).");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("Lifecycle status (Requested / Authorized / Captured / Completed / Failed / Voided / Refunded).");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("void_reason")
                        .HasComment("Saga-supplied reason for the void (H-5 closeout; nullable until Void succeeds).");

                    b.Property<DateTimeOffset?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at_utc")
                        .HasComment("UTC timestamp when authorization was voided (nullable).");

                    b.HasKey("Id")
                        .HasName("pk_payment_transactions");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("ix_payment_transactions_buyer_id");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_transactions_correlation_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payment_transactions_order_id");

                    b.ToTable("payment_transactions", "payments", t =>
                        {
                            t.HasComment("PaymentTransaction aggregate — saga-scoped lifecycle from Requested through Completed/Failed/Voided/Refunded.");
                        });
                });

            modelBuilder.Entity("Platform.ReliableMessaging.Inbox.Core.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id")
                        .HasComment("Unique message identifier (Primary Key).");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc")
                        .HasComment("UTC timestamp when the message was processed.");

                    b.HasKey("MessageId")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_inbox_messages_processed_at_utc");

                    b.ToTable("inbox_messages", "payments", t =>
                        {
                            t.HasComment("Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.");
                        });
                });

            modelBuilder.Entity("Platform.ReliableMessaging.Outbox.Core.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("PK, Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("AvroPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("avro_payload")
                        .HasComment("Avro-serialized domain event payload");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<string>("Headers")
                        .HasMaxLength(8192)
                        .IsUnicode(true)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("headers")
                        .HasComment("JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.");

                    b.Property<string>("KafkaKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("kafka_key")
                        .HasComment("Kafka Key - typically the Aggregate ID for proper event ordering and partitioning");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(249)
                        .IsUnicode(false)
                        .HasColumnType("character varying(249)")
                        .HasColumnName("topic_name")
                        .HasComment("The Kafka topic where this message will be published. Set by the message producer.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type")
                        .HasComment("Avro type name of the serialized event (e.g., 'FeedbackChangedEvent') for deserialization and observability");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "payments", t =>
                        {
                            t.HasComment("Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.");
                        });
                });

            modelBuilder.Entity("Payments.Domain.Transactions.PaymentTransaction", b =>
                {
                    b.OwnsOne("Payments.Domain.Transactions.ValueObjects.FailureInfo", "FailureInfo", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("GatewayCode")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("failure_gateway_code")
                                .HasComment("Raw gateway code at failure time (nullable when gateway returned no code).");

                            b1.Property<int>("Reason")
                                .HasColumnType("integer")
                                .HasColumnName("failure_reason")
                                .HasComment("Classified terminal failure reason.");

                            b1.Property<DateTimeOffset>("RecordedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("failure_recorded_at_utc")
                                .HasComment("UTC timestamp when the failure was observed and recorded on the aggregate.");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("payment_transactions", "payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId")
                                .HasConstraintName("fk_payment_transactions_payment_transactions_id");
                        });

                    b.OwnsOne("Payments.Domain.Transactions.ValueObjects.GatewayResponseCode", "GatewayResponseCode", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("gateway_response_code")
                                .HasComment("Last observed gateway response code (forensic; not used for control flow).");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("gateway_response_message")
                                .HasComment("Last observed gateway response human-readable message.");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("payment_transactions", "payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId")
                                .HasConstraintName("fk_payment_transactions_payment_transactions_id");
                        });

                    b.OwnsOne("Platform.SharedKernel.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("amount")
                                .HasComment("Payment amount.");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency")
                                .HasComment("ISO 4217 currency code.");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("payment_transactions", "payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId")
                                .HasConstraintName("fk_payment_transactions_payment_transactions_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("FailureInfo");

                    b.Navigation("GatewayResponseCode");
                });
#pragma warning restore 612, 618
        }
    }
}
