// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ordering.Orders
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Command issued by the Checkout saga (or ops tooling) to cancel an Order. Ordering transitions to Cancelled and emits OrderCancelledEvent, which downstream consumers use to release stock and refund if captured.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class CancelOrderCommand : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""CancelOrderCommand"",""doc"":""Command issued by the Checkout saga (or ops tooling) to cancel an Order. Ordering transitions to Cancelled and emits OrderCancelledEvent, which downstream consumers use to release stock and refund if captured."",""namespace"":""Ordering.Orders"",""fields"":[{""name"":""OrderId"",""doc"":""Unique identifier of the Order to cancel. Also the Kafka message key."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""CorrelationId"",""doc"":""Checkout saga correlation id. Present for admin-driven cancellations too (null-sentinel omitted for v1)."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Reason"",""doc"":""Human- or system-assigned cancellation reason (max 500 chars). Propagates to OrderCancelledEvent.Reason."",""type"":""string""},{""name"":""RequestedAtUtc"",""doc"":""UTC timestamp when the cancellation was requested."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Unique identifier of the Order to cancel. Also the Kafka message key.
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// Checkout saga correlation id. Present for admin-driven cancellations too (null-sentinel omitted for v1).
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// Human- or system-assigned cancellation reason (max 500 chars). Propagates to OrderCancelledEvent.Reason.
		/// </summary>
		private string _Reason;
		/// <summary>
		/// UTC timestamp when the cancellation was requested.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return CancelOrderCommand._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the Order to cancel. Also the Kafka message key.
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// Checkout saga correlation id. Present for admin-driven cancellations too (null-sentinel omitted for v1).
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// Human- or system-assigned cancellation reason (max 500 chars). Propagates to OrderCancelledEvent.Reason.
		/// </summary>
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				this._Reason = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the cancellation was requested.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.CorrelationId;
			case 2: return this.Reason;
			case 3: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Guid)fieldValue; break;
			case 1: this.CorrelationId = (System.Guid)fieldValue; break;
			case 2: this.Reason = (System.String)fieldValue; break;
			case 3: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
