// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ordering.Orders
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Postal address for shipping or billing.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class OrderAddress : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderAddress"",""doc"":""Postal address for shipping or billing."",""namespace"":""Ordering.Orders"",""fields"":[{""name"":""Street1"",""doc"":""Primary street line (max 200 chars, required)."",""type"":""string""},{""name"":""Street2"",""doc"":""Secondary street line (max 200 chars, optional)."",""default"":null,""type"":[""null"",""string""]},{""name"":""City"",""doc"":""City (max 100 chars, required)."",""type"":""string""},{""name"":""State"",""doc"":""State or province (max 100 chars, optional for countries that do not use one)."",""default"":null,""type"":[""null"",""string""]},{""name"":""PostalCode"",""doc"":""Postal or ZIP code (max 20 chars, required)."",""type"":""string""},{""name"":""CountryCode"",""doc"":""ISO 3166-1 alpha-2 country code (exactly 2 uppercase letters, required)."",""type"":""string""}]}");
		/// <summary>
		/// Primary street line (max 200 chars, required).
		/// </summary>
		private string _Street1;
		/// <summary>
		/// Secondary street line (max 200 chars, optional).
		/// </summary>
		private string _Street2;
		/// <summary>
		/// City (max 100 chars, required).
		/// </summary>
		private string _City;
		/// <summary>
		/// State or province (max 100 chars, optional for countries that do not use one).
		/// </summary>
		private string _State;
		/// <summary>
		/// Postal or ZIP code (max 20 chars, required).
		/// </summary>
		private string _PostalCode;
		/// <summary>
		/// ISO 3166-1 alpha-2 country code (exactly 2 uppercase letters, required).
		/// </summary>
		private string _CountryCode;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OrderAddress._SCHEMA;
			}
		}
		/// <summary>
		/// Primary street line (max 200 chars, required).
		/// </summary>
		public string Street1
		{
			get
			{
				return this._Street1;
			}
			set
			{
				this._Street1 = value;
			}
		}
		/// <summary>
		/// Secondary street line (max 200 chars, optional).
		/// </summary>
		public string Street2
		{
			get
			{
				return this._Street2;
			}
			set
			{
				this._Street2 = value;
			}
		}
		/// <summary>
		/// City (max 100 chars, required).
		/// </summary>
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				this._City = value;
			}
		}
		/// <summary>
		/// State or province (max 100 chars, optional for countries that do not use one).
		/// </summary>
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				this._State = value;
			}
		}
		/// <summary>
		/// Postal or ZIP code (max 20 chars, required).
		/// </summary>
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				this._PostalCode = value;
			}
		}
		/// <summary>
		/// ISO 3166-1 alpha-2 country code (exactly 2 uppercase letters, required).
		/// </summary>
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				this._CountryCode = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Street1;
			case 1: return this.Street2;
			case 2: return this.City;
			case 3: return this.State;
			case 4: return this.PostalCode;
			case 5: return this.CountryCode;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Street1 = (System.String)fieldValue; break;
			case 1: this.Street2 = (System.String)fieldValue; break;
			case 2: this.City = (System.String)fieldValue; break;
			case 3: this.State = (System.String)fieldValue; break;
			case 4: this.PostalCode = (System.String)fieldValue; break;
			case 5: this.CountryCode = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
