// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ordering.Orders
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Emitted when the carrier confirms delivery. Terminal happy-path event for the order lifecycle.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class OrderDeliveredEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderDeliveredEvent"",""doc"":""Emitted when the carrier confirms delivery. Terminal happy-path event for the order lifecycle."",""namespace"":""Ordering.Orders"",""fields"":[{""name"":""OrderId"",""doc"":""Unique identifier of the Order that was delivered."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""BuyerId"",""doc"":""User who placed the order."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""DeliveredAtUtc"",""doc"":""UTC timestamp when the order was delivered."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Unique identifier of the Order that was delivered.
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// User who placed the order.
		/// </summary>
		private System.Guid _BuyerId;
		/// <summary>
		/// UTC timestamp when the order was delivered.
		/// </summary>
		private System.DateTime _DeliveredAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OrderDeliveredEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the Order that was delivered.
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// User who placed the order.
		/// </summary>
		public System.Guid BuyerId
		{
			get
			{
				return this._BuyerId;
			}
			set
			{
				this._BuyerId = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the order was delivered.
		/// </summary>
		public System.DateTime DeliveredAtUtc
		{
			get
			{
				return this._DeliveredAtUtc;
			}
			set
			{
				this._DeliveredAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.BuyerId;
			case 2: return this.DeliveredAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Guid)fieldValue; break;
			case 1: this.BuyerId = (System.Guid)fieldValue; break;
			case 2: this.DeliveredAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
