// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ordering.Orders
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Emitted when the Order is handed to a carrier with a tracking number.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class OrderShippedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderShippedEvent"",""doc"":""Emitted when the Order is handed to a carrier with a tracking number."",""namespace"":""Ordering.Orders"",""fields"":[{""name"":""OrderId"",""doc"":""Unique identifier of the Order that was shipped."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""CorrelationId"",""doc"":""Checkout saga correlation id (carried post-saga for forensic continuity; saga itself is finalised by this point)."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""BuyerId"",""doc"":""User who placed the order."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Carrier"",""doc"":""Shipping carrier name (e.g., 'FedEx', 'DHL', 'UPS')."",""type"":""string""},{""name"":""TrackingNumber"",""doc"":""Carrier-assigned tracking number."",""type"":""string""},{""name"":""ShippedAtUtc"",""doc"":""UTC timestamp when the order was shipped."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Unique identifier of the Order that was shipped.
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// Checkout saga correlation id (carried post-saga for forensic continuity; saga itself is finalised by this point).
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// User who placed the order.
		/// </summary>
		private System.Guid _BuyerId;
		/// <summary>
		/// Shipping carrier name (e.g., 'FedEx', 'DHL', 'UPS').
		/// </summary>
		private string _Carrier;
		/// <summary>
		/// Carrier-assigned tracking number.
		/// </summary>
		private string _TrackingNumber;
		/// <summary>
		/// UTC timestamp when the order was shipped.
		/// </summary>
		private System.DateTime _ShippedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OrderShippedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the Order that was shipped.
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// Checkout saga correlation id (carried post-saga for forensic continuity; saga itself is finalised by this point).
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// User who placed the order.
		/// </summary>
		public System.Guid BuyerId
		{
			get
			{
				return this._BuyerId;
			}
			set
			{
				this._BuyerId = value;
			}
		}
		/// <summary>
		/// Shipping carrier name (e.g., 'FedEx', 'DHL', 'UPS').
		/// </summary>
		public string Carrier
		{
			get
			{
				return this._Carrier;
			}
			set
			{
				this._Carrier = value;
			}
		}
		/// <summary>
		/// Carrier-assigned tracking number.
		/// </summary>
		public string TrackingNumber
		{
			get
			{
				return this._TrackingNumber;
			}
			set
			{
				this._TrackingNumber = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the order was shipped.
		/// </summary>
		public System.DateTime ShippedAtUtc
		{
			get
			{
				return this._ShippedAtUtc;
			}
			set
			{
				this._ShippedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.CorrelationId;
			case 2: return this.BuyerId;
			case 3: return this.Carrier;
			case 4: return this.TrackingNumber;
			case 5: return this.ShippedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Guid)fieldValue; break;
			case 1: this.CorrelationId = (System.Guid)fieldValue; break;
			case 2: this.BuyerId = (System.Guid)fieldValue; break;
			case 3: this.Carrier = (System.String)fieldValue; break;
			case 4: this.TrackingNumber = (System.String)fieldValue; break;
			case 5: this.ShippedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
