// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ordering.Orders
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Emitted when the Order has been successfully confirmed (stock reserved AND payment completed).
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class OrderConfirmedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderConfirmedEvent"",""doc"":""Emitted when the Order has been successfully confirmed (stock reserved AND payment completed)."",""namespace"":""Ordering.Orders"",""fields"":[{""name"":""OrderId"",""doc"":""Unique identifier of the Order that was confirmed."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""CorrelationId"",""doc"":""Checkout saga correlation id. Consumers can correlate this event with the saga run."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""BuyerId"",""doc"":""User who placed the order."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""ConfirmedAtUtc"",""doc"":""UTC timestamp when the order was confirmed."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Unique identifier of the Order that was confirmed.
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// Checkout saga correlation id. Consumers can correlate this event with the saga run.
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// User who placed the order.
		/// </summary>
		private System.Guid _BuyerId;
		/// <summary>
		/// UTC timestamp when the order was confirmed.
		/// </summary>
		private System.DateTime _ConfirmedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OrderConfirmedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the Order that was confirmed.
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// Checkout saga correlation id. Consumers can correlate this event with the saga run.
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// User who placed the order.
		/// </summary>
		public System.Guid BuyerId
		{
			get
			{
				return this._BuyerId;
			}
			set
			{
				this._BuyerId = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the order was confirmed.
		/// </summary>
		public System.DateTime ConfirmedAtUtc
		{
			get
			{
				return this._ConfirmedAtUtc;
			}
			set
			{
				this._ConfirmedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.CorrelationId;
			case 2: return this.BuyerId;
			case 3: return this.ConfirmedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Guid)fieldValue; break;
			case 1: this.CorrelationId = (System.Guid)fieldValue; break;
			case 2: this.BuyerId = (System.Guid)fieldValue; break;
			case 3: this.ConfirmedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
