// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ordering.Orders
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Summary Event (per ADR-0020) emitted when the Order is cancelled. Carries the aggregate snapshot at the cancellation transition — Items, TotalAmount, Currency, BillingAddress — so downstream consumers (notably Invoicing's credit-note path under 10-year retention) can rebuild state without an HTTP round-trip back to Ordering. The four enrichment fields are nullable / defaulted for FORWARD_TRANSITIVE compatibility per ADR-0007; production producers always populate them. Downstream compensation consumers (Inventory release, Payments refund, Notifications, BFF cache, checkout saga) continue to read only the Reason / AtStatus delta payload they already used.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class OrderCancelledEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"OrderCancelledEvent\",\"doc\":\"Summary Event (per ADR-0020)" +
				" emitted when the Order is cancelled. Carries the aggregate snapshot at the canc" +
				"ellation transition — Items, TotalAmount, Currency, BillingAddress — so downstre" +
				"am consumers (notably Invoicing\'s credit-note path under 10-year retention) can " +
				"rebuild state without an HTTP round-trip back to Ordering. The four enrichment f" +
				"ields are nullable / defaulted for FORWARD_TRANSITIVE compatibility per ADR-0007" +
				"; production producers always populate them. Downstream compensation consumers (" +
				"Inventory release, Payments refund, Notifications, BFF cache, checkout saga) con" +
				"tinue to read only the Reason / AtStatus delta payload they already used.\",\"name" +
				"space\":\"Ordering.Orders\",\"fields\":[{\"name\":\"OrderId\",\"doc\":\"Unique identifier of" +
				" the Order that was cancelled.\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{" +
				"\"name\":\"BuyerId\",\"doc\":\"User who placed the order.\",\"type\":{\"type\":\"string\",\"log" +
				"icalType\":\"uuid\"}},{\"name\":\"Reason\",\"doc\":\"Human- or system-assigned cancellatio" +
				"n reason.\",\"type\":\"string\"},{\"name\":\"AtStatus\",\"doc\":\"OrderStatus just before ca" +
				"ncellation. Informs consumers what compensation to perform (release stock, refun" +
				"d, etc.).\",\"type\":{\"type\":\"enum\",\"name\":\"OrderStatusAtTransition\",\"namespace\":\"O" +
				"rdering.Orders\",\"symbols\":[\"Created\",\"StockReserved\",\"PaymentCompleted\",\"Confirm" +
				"ed\"]}},{\"name\":\"CancelledAtUtc\",\"doc\":\"UTC timestamp when the order was cancelle" +
				"d.\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"Items\",\"do" +
				"c\":\"Order line items with frozen product snapshots and prices. Empty default exi" +
				"sts for FORWARD_TRANSITIVE compatibility with the v1 (pre-Wave-1.6) schema; prod" +
				"uction producers always populate at least one item per Order invariant I-7.\",\"de" +
				"fault\":[],\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OrderItemCance" +
				"lled\",\"doc\":\"One cancelled-order line. Mirrors the OrderItemConfirmed shape from" +
				" OrderConfirmedEvent.avsc (different name to avoid an avrogen per-file class col" +
				"lision in namespace \'Ordering.Orders\' — see ADR-0020 § Implementation Notes). Fr" +
				"ozen at cancellation per Order invariant I-2.\",\"namespace\":\"Ordering.Orders\",\"fi" +
				"elds\":[{\"name\":\"ProductId\",\"doc\":\"Catalog product identifier for this line.\",\"ty" +
				"pe\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"Sku\",\"doc\":\"Catalog SKU sna" +
				"pshot at order creation time.\",\"type\":\"string\"},{\"name\":\"Name\",\"doc\":\"Product di" +
				"splay name snapshot at order creation time.\",\"type\":\"string\"},{\"name\":\"Quantity\"" +
				",\"doc\":\"Quantity of this line (>= 1).\",\"type\":\"int\"},{\"name\":\"UnitPriceAmount\",\"" +
				"doc\":\"Per-unit price amount.\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"pr" +
				"ecision\":19,\"scale\":4}},{\"name\":\"LineTotalAmount\",\"doc\":\"UnitPriceAmount * Quant" +
				"ity, pre-computed.\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":1" +
				"9,\"scale\":4}}]}}},{\"name\":\"TotalAmount\",\"doc\":\"Total order amount (sum of OrderI" +
				"temCancelled.LineTotalAmount). Nullable union for FORWARD_TRANSITIVE compatibili" +
				"ty with the v1 schema (Avro decimal defaults are encoding-fragile per ADR-0020);" +
				" production producers always populate.\",\"default\":null,\"type\":[\"null\",{\"type\":\"b" +
				"ytes\",\"logicalType\":\"decimal\",\"precision\":19,\"scale\":4}]},{\"name\":\"Currency\",\"do" +
				"c\":\"ISO 4217 currency code shared by all items. Nullable union covaries with Tot" +
				"alAmount; production producers always populate.\",\"default\":null,\"type\":[\"null\",\"" +
				"string\"]},{\"name\":\"BillingAddress\",\"doc\":\"Buyer\'s billing address snapshot. Cons" +
				"umed by Invoicing for credit-note generation.\",\"default\":null,\"type\":[\"null\",{\"t" +
				"ype\":\"record\",\"name\":\"OrderCancellationBillingAddress\",\"doc\":\"Snapshot of the bu" +
				"yer\'s billing address at cancellation time. Field shape is identical to Basket.S" +
				"essions.CheckoutAddress and Wave 1.5\'s Ordering.Orders.OrderBillingAddress; defi" +
				"ned locally because avrogen processes each .avsc file in isolation and a cross-f" +
				"ile reference would emit a class collision (see ADR-0020 § Implementation Notes)" +
				".\",\"namespace\":\"Ordering.Orders\",\"fields\":[{\"name\":\"Street1\",\"doc\":\"Primary stre" +
				"et line.\",\"type\":\"string\"},{\"name\":\"Street2\",\"doc\":\"Optional second street line " +
				"(apartment, suite, etc.).\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Cit" +
				"y\",\"doc\":\"City name.\",\"type\":\"string\"},{\"name\":\"State\",\"doc\":\"Optional state/pro" +
				"vince/region. Null for countries without this concept.\",\"default\":null,\"type\":[\"" +
				"null\",\"string\"]},{\"name\":\"PostalCode\",\"doc\":\"Postal or ZIP code.\",\"type\":\"string" +
				"\"},{\"name\":\"CountryCode\",\"doc\":\"ISO 3166-1 alpha-2 country code (e.g., \'US\', \'CZ" +
				"\').\",\"type\":\"string\"}]}]}]}");
		/// <summary>
		/// Unique identifier of the Order that was cancelled.
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// User who placed the order.
		/// </summary>
		private System.Guid _BuyerId;
		/// <summary>
		/// Human- or system-assigned cancellation reason.
		/// </summary>
		private string _Reason;
		/// <summary>
		/// OrderStatus just before cancellation. Informs consumers what compensation to perform (release stock, refund, etc.).
		/// </summary>
		private Ordering.Orders.OrderStatusAtTransition _AtStatus;
		/// <summary>
		/// UTC timestamp when the order was cancelled.
		/// </summary>
		private System.DateTime _CancelledAtUtc;
		/// <summary>
		/// Order line items with frozen product snapshots and prices. Empty default exists for FORWARD_TRANSITIVE compatibility with the v1 (pre-Wave-1.6) schema; production producers always populate at least one item per Order invariant I-7.
		/// </summary>
		private IList<Ordering.Orders.OrderItemCancelled> _Items;
		/// <summary>
		/// Total order amount (sum of OrderItemCancelled.LineTotalAmount). Nullable union for FORWARD_TRANSITIVE compatibility with the v1 schema (Avro decimal defaults are encoding-fragile per ADR-0020); production producers always populate.
		/// </summary>
		private System.Nullable<Avro.AvroDecimal> _TotalAmount;
		/// <summary>
		/// ISO 4217 currency code shared by all items. Nullable union covaries with TotalAmount; production producers always populate.
		/// </summary>
		private string _Currency;
		/// <summary>
		/// Buyer's billing address snapshot. Consumed by Invoicing for credit-note generation.
		/// </summary>
		private Ordering.Orders.OrderCancellationBillingAddress _BillingAddress;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OrderCancelledEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the Order that was cancelled.
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// User who placed the order.
		/// </summary>
		public System.Guid BuyerId
		{
			get
			{
				return this._BuyerId;
			}
			set
			{
				this._BuyerId = value;
			}
		}
		/// <summary>
		/// Human- or system-assigned cancellation reason.
		/// </summary>
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				this._Reason = value;
			}
		}
		/// <summary>
		/// OrderStatus just before cancellation. Informs consumers what compensation to perform (release stock, refund, etc.).
		/// </summary>
		public Ordering.Orders.OrderStatusAtTransition AtStatus
		{
			get
			{
				return this._AtStatus;
			}
			set
			{
				this._AtStatus = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the order was cancelled.
		/// </summary>
		public System.DateTime CancelledAtUtc
		{
			get
			{
				return this._CancelledAtUtc;
			}
			set
			{
				this._CancelledAtUtc = value;
			}
		}
		/// <summary>
		/// Order line items with frozen product snapshots and prices. Empty default exists for FORWARD_TRANSITIVE compatibility with the v1 (pre-Wave-1.6) schema; production producers always populate at least one item per Order invariant I-7.
		/// </summary>
		public IList<Ordering.Orders.OrderItemCancelled> Items
		{
			get
			{
				return this._Items;
			}
			set
			{
				this._Items = value;
			}
		}
		/// <summary>
		/// Total order amount (sum of OrderItemCancelled.LineTotalAmount). Nullable union for FORWARD_TRANSITIVE compatibility with the v1 schema (Avro decimal defaults are encoding-fragile per ADR-0020); production producers always populate.
		/// </summary>
		public System.Nullable<Avro.AvroDecimal> TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				this._TotalAmount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code shared by all items. Nullable union covaries with TotalAmount; production producers always populate.
		/// </summary>
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		/// <summary>
		/// Buyer's billing address snapshot. Consumed by Invoicing for credit-note generation.
		/// </summary>
		public Ordering.Orders.OrderCancellationBillingAddress BillingAddress
		{
			get
			{
				return this._BillingAddress;
			}
			set
			{
				this._BillingAddress = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.BuyerId;
			case 2: return this.Reason;
			case 3: return this.AtStatus;
			case 4: return this.CancelledAtUtc;
			case 5: return this.Items;
			case 6: return this.TotalAmount;
			case 7: return this.Currency;
			case 8: return this.BillingAddress;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Guid)fieldValue; break;
			case 1: this.BuyerId = (System.Guid)fieldValue; break;
			case 2: this.Reason = (System.String)fieldValue; break;
			case 3: this.AtStatus = (Ordering.Orders.OrderStatusAtTransition)fieldValue; break;
			case 4: this.CancelledAtUtc = (System.DateTime)fieldValue; break;
			case 5: this.Items = (IList<Ordering.Orders.OrderItemCancelled>)fieldValue; break;
			case 6: this.TotalAmount = (System.Nullable<Avro.AvroDecimal>)fieldValue; break;
			case 7: this.Currency = (System.String)fieldValue; break;
			case 8: this.BillingAddress = (Ordering.Orders.OrderCancellationBillingAddress)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
