// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ordering.Orders
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Emitted when the Order is cancelled. Downstream consumers trigger compensation (release stock, refund, notify).
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class OrderCancelledEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderCancelledEvent"",""doc"":""Emitted when the Order is cancelled. Downstream consumers trigger compensation (release stock, refund, notify)."",""namespace"":""Ordering.Orders"",""fields"":[{""name"":""OrderId"",""doc"":""Unique identifier of the Order that was cancelled."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""CorrelationId"",""doc"":""Checkout saga correlation id. Used by the saga to correlate compensation flows."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""BuyerId"",""doc"":""User who placed the order."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Reason"",""doc"":""Human- or system-assigned cancellation reason."",""type"":""string""},{""name"":""AtStatus"",""doc"":""OrderStatus just before cancellation. Informs consumers what compensation to perform (release stock, refund, etc.)."",""type"":{""type"":""enum"",""name"":""OrderStatusAtTransition"",""namespace"":""Ordering.Orders"",""symbols"":[""Created"",""StockReserved"",""PaymentCompleted"",""Confirmed""]}},{""name"":""CancelledAtUtc"",""doc"":""UTC timestamp when the order was cancelled."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Unique identifier of the Order that was cancelled.
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// Checkout saga correlation id. Used by the saga to correlate compensation flows.
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// User who placed the order.
		/// </summary>
		private System.Guid _BuyerId;
		/// <summary>
		/// Human- or system-assigned cancellation reason.
		/// </summary>
		private string _Reason;
		/// <summary>
		/// OrderStatus just before cancellation. Informs consumers what compensation to perform (release stock, refund, etc.).
		/// </summary>
		private Ordering.Orders.OrderStatusAtTransition _AtStatus;
		/// <summary>
		/// UTC timestamp when the order was cancelled.
		/// </summary>
		private System.DateTime _CancelledAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OrderCancelledEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the Order that was cancelled.
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// Checkout saga correlation id. Used by the saga to correlate compensation flows.
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// User who placed the order.
		/// </summary>
		public System.Guid BuyerId
		{
			get
			{
				return this._BuyerId;
			}
			set
			{
				this._BuyerId = value;
			}
		}
		/// <summary>
		/// Human- or system-assigned cancellation reason.
		/// </summary>
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				this._Reason = value;
			}
		}
		/// <summary>
		/// OrderStatus just before cancellation. Informs consumers what compensation to perform (release stock, refund, etc.).
		/// </summary>
		public Ordering.Orders.OrderStatusAtTransition AtStatus
		{
			get
			{
				return this._AtStatus;
			}
			set
			{
				this._AtStatus = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the order was cancelled.
		/// </summary>
		public System.DateTime CancelledAtUtc
		{
			get
			{
				return this._CancelledAtUtc;
			}
			set
			{
				this._CancelledAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.CorrelationId;
			case 2: return this.BuyerId;
			case 3: return this.Reason;
			case 4: return this.AtStatus;
			case 5: return this.CancelledAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Guid)fieldValue; break;
			case 1: this.CorrelationId = (System.Guid)fieldValue; break;
			case 2: this.BuyerId = (System.Guid)fieldValue; break;
			case 3: this.Reason = (System.String)fieldValue; break;
			case 4: this.AtStatus = (Ordering.Orders.OrderStatusAtTransition)fieldValue; break;
			case 5: this.CancelledAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
