// <auto-generated />
using System;
using DotNetAtlas.Sagas.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetAtlas.Sagas.Common.Persistence.Database.Migrations
{
    [DbContext(typeof(SagaDbContext))]
    [Migration("20260212173135_Asdf")]
    partial class Asdf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("saga")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetAtlas.ReliableMessaging.Outbox.Core.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("PK, Identity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("AvroPayload")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasComment("Avro-serialized domain event payload");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<string>("Headers")
                        .HasMaxLength(8192)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.");

                    b.Property<string>("KafkaKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Kafka Key - typically the Aggregate ID for proper event ordering and partitioning");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(249)
                        .IsUnicode(false)
                        .HasColumnType("varchar(249)")
                        .HasComment("The Kafka topic where this message will be published. Set by the message producer.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasComment("Avro type name of the serialized event (e.g., 'FeedbackChangedEvent') for deserialization and observability");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "saga", t =>
                        {
                            t.HasComment("Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.");
                        });
                });

            modelBuilder.Entity("DotNetAtlas.Sagas.Finance.PaymentProcessingSaga.PaymentProcessingSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique correlation ID for the payment saga");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasComment("Payment amount");

                    b.Property<DateTimeOffset?>("AuthorizationExpiresAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when authorization expires");

                    b.Property<string>("AuthorizationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("Authorization ID from payment provider");

                    b.Property<int>("AuthorizationRetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Number of authorization retry attempts");

                    b.Property<Guid?>("AuthorizationTimeoutTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Token ID for authorization timeout scheduler - set when schedule is active");

                    b.Property<DateTimeOffset?>("AuthorizedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when authorization completed");

                    b.Property<int>("CaptureRetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Number of capture retry attempts");

                    b.Property<Guid?>("CaptureTimeoutTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Token ID for capture timeout scheduler - set when schedule is active");

                    b.Property<DateTimeOffset?>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when capture completed");

                    b.Property<DateTimeOffset?>("CompensationCompletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when compensation completed");

                    b.Property<bool>("CompensationTriggered")
                        .HasColumnType("bit")
                        .HasComment("Whether compensation has been triggered");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when saga was created");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasComment("ISO 4217 currency code");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Current state of the saga state machine");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Error code for categorized failure handling");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Error message if failed");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Idempotency key to prevent duplicate processing");

                    b.Property<DateTimeOffset>("InitiatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when payment was initiated");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when saga was last updated");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID of the saved payment method");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Payment transaction ID after capture");

                    b.Property<Guid?>("RefundTimeoutTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Token ID for refund timeout scheduler - set when schedule is active");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Optimistic concurrency token.");

                    b.Property<Guid?>("SuccessFinalizationTimeoutTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Token ID for success finalization timeout scheduler - set when schedule is active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User initiating the payment");

                    b.Property<Guid?>("VoidTimeoutTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Token ID for void timeout scheduler - set when schedule is active");

                    b.HasKey("CorrelationId");

                    b.HasIndex("CurrentState")
                        .HasDatabaseName("IX_PaymentSagaState_CurrentState");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentSagaState_IdempotencyKey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PaymentSagaState_UserId");

                    b.HasIndex("CurrentState", "CreatedUtc")
                        .HasDatabaseName("IX_PaymentSagaState_State_Created");

                    b.HasIndex("CurrentState", "LastModifiedUtc")
                        .HasDatabaseName("IX_PaymentSagaState_State_LastUpdated");

                    b.ToTable("PaymentProcessingSagaState", "saga", t =>
                        {
                            t.HasComment("Saga state for payment processing orchestration.");
                        });
                });

            modelBuilder.Entity("DotNetAtlas.Sagas.Orders.AlertSubscriptionExtensionSaga.AlertSubscriptionExtensionSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK - Unique correlation ID (also PaymentTransactionId)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasComment("Payment amount");

                    b.Property<DateTimeOffset?>("CompensationCompletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when compensation completed");

                    b.Property<Guid?>("CompensationTimeoutTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Token ID for compensation timeout scheduler - set when schedule is active");

                    b.Property<bool>("CompensationTriggered")
                        .HasColumnType("bit")
                        .HasComment("Whether compensation (refund) has been triggered");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when saga was created");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasComment("ISO 4217 currency code");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Current state of the saga state machine");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int")
                        .HasComment("Subscription extension duration in days");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Error code for categorized failure handling");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Error message if failed");

                    b.Property<DateTimeOffset?>("ExtensionCompletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when extension completed (null if not completed)");

                    b.Property<DateTimeOffset>("ExtensionInitiatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when extension was initiated");

                    b.Property<Guid?>("ExtensionTimeoutTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Token ID for extension timeout scheduler - set when schedule is active");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when saga was last updated");

                    b.Property<DateTimeOffset?>("NewExpiresAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("New subscription expiration date after extension (null if not completed)");

                    b.Property<DateTimeOffset?>("PaymentCompletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when payment completed (null if not completed)");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID of the saved payment method");

                    b.Property<Guid?>("PaymentTimeoutTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Token ID for payment timeout scheduler - set when schedule is active");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Payment transaction ID (set after payment completes)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Optimistic concurrency token.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User who is extending the subscription");

                    b.HasKey("CorrelationId");

                    b.HasIndex("CurrentState")
                        .HasDatabaseName("IX_SubscriptionExtensionSagaState_CurrentState");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SubscriptionExtensionSagaState_UserId");

                    b.HasIndex("CurrentState", "CreatedUtc")
                        .HasDatabaseName("IX_SubscriptionExtensionSagaState_State_Created");

                    b.HasIndex("CurrentState", "LastModifiedUtc")
                        .HasDatabaseName("IX_SubscriptionExtensionSagaState_State_LastUpdated");

                    b.ToTable("AlertSubscriptionExtensionSagaState", "saga", t =>
                        {
                            t.HasComment("Saga state for alert subscription extension orchestration.");
                        });
                });

            modelBuilder.Entity("DotNetAtlas.Sagas.Orders.AlertSubscriptionPurchaseSaga.AlertSubscriptionPurchaseSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK - Unique correlation ID (also PaymentTransactionId)");

                    b.Property<DateTimeOffset?>("ActivationCompletedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when activation completed (null if not completed)");

                    b.Property<Guid?>("ActivationTimeoutTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Token ID for activation timeout scheduler - set when schedule is active");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasComment("Payment amount");

                    b.Property<DateTimeOffset?>("CompensationCompletedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when compensation completed");

                    b.Property<Guid?>("CompensationTimeoutTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Token ID for compensation timeout scheduler - set when schedule is active");

                    b.Property<bool>("CompensationTriggered")
                        .HasColumnType("bit")
                        .HasComment("Whether compensation (refund) has been triggered");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when saga was created");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasComment("ISO 4217 currency code");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Current state of the saga state machine");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int")
                        .HasComment("Subscription duration in days");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Error code for categorized failure handling");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Error message if failed");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when saga was last updated");

                    b.Property<DateTimeOffset?>("PaymentCompletedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when payment completed (null if not completed)");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID of the saved payment method");

                    b.Property<Guid?>("PaymentTimeoutTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Token ID for payment timeout scheduler - set when schedule is active");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Payment transaction ID (set after payment completes)");

                    b.Property<DateTimeOffset>("PurchaseInitiatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when purchase was initiated");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Optimistic concurrency token.");

                    b.Property<int>("SubscriptionTier")
                        .HasColumnType("int")
                        .HasComment("Subscription tier (Pro, Ultra)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User who purchased the subscription");

                    b.HasKey("CorrelationId");

                    b.HasIndex("CurrentState")
                        .HasDatabaseName("IX_SubscriptionPurchaseSagaState_CurrentState");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SubscriptionPurchaseSagaState_UserId");

                    b.HasIndex("CurrentState", "CreatedUtc")
                        .HasDatabaseName("IX_SubscriptionPurchaseSagaState_State_Created");

                    b.HasIndex("CurrentState", "LastModifiedUtc")
                        .HasDatabaseName("IX_SubscriptionPurchaseSagaState_State_LastUpdated");

                    b.ToTable("AlertSubscriptionPurchaseSagaState", "saga", t =>
                        {
                            t.HasComment("Saga state for alert subscription purchase orchestration.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
