// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SagaOrchestrators.Common.Persistence.Database;

#nullable disable

namespace SagaOrchestrators.Common.Persistence.Database.Migrations
{
    [DbContext(typeof(SagaDbContext))]
    partial class SagaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("saga")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.ReliableMessaging.Outbox.Core.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("PK, Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("AvroPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("avro_payload")
                        .HasComment("Avro-serialized domain event payload");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<string>("Headers")
                        .HasMaxLength(8192)
                        .IsUnicode(true)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("headers")
                        .HasComment("JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.");

                    b.Property<string>("KafkaKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("kafka_key")
                        .HasComment("Kafka Key - typically the Aggregate ID for proper event ordering and partitioning");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(249)
                        .IsUnicode(false)
                        .HasColumnType("character varying(249)")
                        .HasColumnName("topic_name")
                        .HasComment("The Kafka topic where this message will be published. Set by the message producer.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type")
                        .HasComment("Avro type name of the serialized event (e.g., 'FeedbackChangedEvent') for deserialization and observability");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("OutboxMessages", "saga", t =>
                        {
                            t.HasComment("Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.");
                        });
                });

            modelBuilder.Entity("SagaOrchestrators.Payments.PaymentProcessingSaga.PaymentProcessingSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id")
                        .HasComment("Unique correlation ID for the payment saga");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount")
                        .HasComment("Payment amount");

                    b.Property<DateTimeOffset?>("AuthorizationExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authorization_expires_at_utc")
                        .HasComment("UTC timestamp when authorization expires");

                    b.Property<string>("AuthorizationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("authorization_id")
                        .HasComment("Authorization ID from payment provider");

                    b.Property<int>("AuthorizationRetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("authorization_retry_count")
                        .HasComment("Number of authorization retry attempts");

                    b.Property<Guid?>("AuthorizationTimeoutTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorization_timeout_token_id")
                        .HasComment("Token ID for authorization timeout scheduler - set when schedule is active");

                    b.Property<DateTimeOffset?>("AuthorizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authorized_at_utc")
                        .HasComment("UTC timestamp when authorization completed");

                    b.Property<int>("CaptureRetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("capture_retry_count")
                        .HasComment("Number of capture retry attempts");

                    b.Property<Guid?>("CaptureTimeoutTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("capture_timeout_token_id")
                        .HasComment("Token ID for capture timeout scheduler - set when schedule is active");

                    b.Property<DateTimeOffset?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc")
                        .HasComment("UTC timestamp when capture completed");

                    b.Property<DateTimeOffset?>("CompensationCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("compensation_completed_at_utc")
                        .HasComment("UTC timestamp when compensation completed");

                    b.Property<bool>("CompensationTriggered")
                        .HasColumnType("boolean")
                        .HasColumnName("compensation_triggered")
                        .HasComment("Whether compensation has been triggered");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasComment("UTC timestamp when saga was created");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency")
                        .HasComment("ISO 4217 currency code");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_state")
                        .HasComment("Current state of the saga state machine");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code")
                        .HasComment("Error code for categorized failure handling");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message")
                        .HasComment("Error message if failed");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key")
                        .HasComment("Idempotency key to prevent duplicate processing");

                    b.Property<DateTimeOffset>("InitiatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at_utc")
                        .HasComment("UTC timestamp when payment was initiated");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_utc")
                        .HasComment("UTC timestamp when saga was last updated");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_method_id")
                        .HasComment("ID of the saved payment method");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id")
                        .HasComment("Payment transaction ID after capture");

                    b.Property<Guid?>("RefundTimeoutTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_timeout_token_id")
                        .HasComment("Token ID for refund timeout scheduler - set when schedule is active");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComment("Optimistic concurrency token.");

                    b.Property<Guid?>("SuccessFinalizationTimeoutTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("success_finalization_timeout_token_id")
                        .HasComment("Token ID for success finalization timeout scheduler - set when schedule is active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("User initiating the payment");

                    b.Property<Guid?>("VoidTimeoutTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("void_timeout_token_id")
                        .HasComment("Token ID for void timeout scheduler - set when schedule is active");

                    b.HasKey("CorrelationId")
                        .HasName("pk_payment_processing_saga_state");

                    b.HasIndex("CurrentState")
                        .HasDatabaseName("IX_PaymentSagaState_CurrentState");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentSagaState_IdempotencyKey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PaymentSagaState_UserId");

                    b.HasIndex("CurrentState", "CreatedUtc")
                        .HasDatabaseName("IX_PaymentSagaState_State_Created");

                    b.HasIndex("CurrentState", "LastModifiedUtc")
                        .HasDatabaseName("IX_PaymentSagaState_State_LastUpdated");

                    b.ToTable("PaymentProcessingSagaState", "saga", t =>
                        {
                            t.HasComment("Saga state for payment processing orchestration.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
