DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'payments') THEN
        CREATE SCHEMA payments;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS payments."__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM payments."__EFMigrationsHistory" WHERE "migration_id" = '20260604194448_CreatePaymentsTables') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'payments') THEN
            CREATE SCHEMA payments;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM payments."__EFMigrationsHistory" WHERE "migration_id" = '20260604194448_CreatePaymentsTables') THEN
    CREATE TABLE payments.inbox_messages (
        message_id uuid NOT NULL,
        processed_at_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_inbox_messages PRIMARY KEY (message_id)
    );
    COMMENT ON TABLE payments.inbox_messages IS 'Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.';
    COMMENT ON COLUMN payments.inbox_messages.message_id IS 'Unique message identifier (Primary Key).';
    COMMENT ON COLUMN payments.inbox_messages.processed_at_utc IS 'UTC timestamp when the message was processed.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM payments."__EFMigrationsHistory" WHERE "migration_id" = '20260604194448_CreatePaymentsTables') THEN
    CREATE TABLE payments.outbox_messages (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        topic_name character varying(249) NOT NULL,
        kafka_key character varying(128),
        avro_payload bytea NOT NULL,
        type character varying(255) NOT NULL,
        headers character varying(8192),
        created_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
    );
    COMMENT ON TABLE payments.outbox_messages IS 'Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.';
    COMMENT ON COLUMN payments.outbox_messages.id IS 'PK, Identity';
    COMMENT ON COLUMN payments.outbox_messages.topic_name IS 'The Kafka topic where this message will be published. Set by the message producer.';
    COMMENT ON COLUMN payments.outbox_messages.kafka_key IS 'Kafka Key - typically the Aggregate ID for proper event ordering and partitioning';
    COMMENT ON COLUMN payments.outbox_messages.avro_payload IS 'Avro-serialized domain event payload';
    COMMENT ON COLUMN payments.outbox_messages.type IS 'Avro type name of the serialized event (e.g., ''FeedbackChangedEvent'') for deserialization and observability';
    COMMENT ON COLUMN payments.outbox_messages.headers IS 'JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.';
    COMMENT ON COLUMN payments.outbox_messages.created_utc IS 'Creation timestamp (UTC).';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM payments."__EFMigrationsHistory" WHERE "migration_id" = '20260604194448_CreatePaymentsTables') THEN
    CREATE TABLE payments.payment_transactions (
        id uuid NOT NULL,
        buyer_id uuid NOT NULL,
        order_id uuid NOT NULL,
        amount numeric(19,4) NOT NULL,
        amount_currency character varying(3) NOT NULL,
        payment_method_id_enc character varying(64) NOT NULL,
        status integer NOT NULL,
        gateway_transaction_id_enc character varying(256),
        gateway_response_code character varying(64),
        gateway_response_message character varying(512),
        authorized_at_utc timestamp with time zone,
        captured_at_utc timestamp with time zone,
        completed_at_utc timestamp with time zone,
        refunded_at_utc timestamp with time zone,
        voided_at_utc timestamp with time zone,
        void_reason character varying(256),
        failure_reason integer,
        failure_gateway_code character varying(64),
        failure_recorded_at_utc timestamp with time zone,
        CONSTRAINT pk_payment_transactions PRIMARY KEY (id)
    );
    COMMENT ON TABLE payments.payment_transactions IS 'PaymentTransaction aggregate — saga-scoped lifecycle from Requested through Completed/Failed/Voided/Refunded.';
    COMMENT ON COLUMN payments.payment_transactions.id IS 'Primary key — saga-minted UUID v7 (time-ordered), carried on AuthorizePaymentCommand as PaymentTransactionId; distinct from the saga key (OrderId). One payment per order is enforced by the ux_payment_transactions_order_id unique index (ADR-0029). See docs/bc-design/payments.md § 2.2 (I-7).';
    COMMENT ON COLUMN payments.payment_transactions.buyer_id IS 'JWT sub of the buyer the payment is for.';
    COMMENT ON COLUMN payments.payment_transactions.order_id IS 'Ordering aggregate id this payment is attached to (frozen at creation). Unique index enforces one payment per order (ADR-0029).';
    COMMENT ON COLUMN payments.payment_transactions.amount IS 'Payment amount.';
    COMMENT ON COLUMN payments.payment_transactions.amount_currency IS 'ISO 4217 currency code.';
    COMMENT ON COLUMN payments.payment_transactions.payment_method_id_enc IS 'PII (ADR-0011): gateway-issued tokenised payment instrument. v1 plaintext; v2 encrypts.';
    COMMENT ON COLUMN payments.payment_transactions.status IS 'Lifecycle status (Requested / Authorized / Captured / Completed / Failed / Voided / Refunded).';
    COMMENT ON COLUMN payments.payment_transactions.gateway_transaction_id_enc IS 'Sensitive token (ADR-0011): gateway transaction reference; null until first successful gateway call. v1 plaintext; v2 encrypts.';
    COMMENT ON COLUMN payments.payment_transactions.gateway_response_code IS 'Last observed gateway response code (forensic; not used for control flow).';
    COMMENT ON COLUMN payments.payment_transactions.gateway_response_message IS 'Last observed gateway response human-readable message.';
    COMMENT ON COLUMN payments.payment_transactions.authorized_at_utc IS 'UTC timestamp when authorize succeeded (nullable).';
    COMMENT ON COLUMN payments.payment_transactions.captured_at_utc IS 'UTC timestamp when capture succeeded (nullable).';
    COMMENT ON COLUMN payments.payment_transactions.completed_at_utc IS 'UTC timestamp when capture auto-advanced to Completed (nullable).';
    COMMENT ON COLUMN payments.payment_transactions.refunded_at_utc IS 'UTC timestamp when refund completed (nullable).';
    COMMENT ON COLUMN payments.payment_transactions.voided_at_utc IS 'UTC timestamp when authorization was voided (nullable).';
    COMMENT ON COLUMN payments.payment_transactions.void_reason IS 'Saga-supplied reason for the void (H-5 closeout; nullable until Void succeeds).';
    COMMENT ON COLUMN payments.payment_transactions.failure_reason IS 'Classified terminal failure reason.';
    COMMENT ON COLUMN payments.payment_transactions.failure_gateway_code IS 'Raw gateway code at failure time (nullable when gateway returned no code).';
    COMMENT ON COLUMN payments.payment_transactions.failure_recorded_at_utc IS 'UTC timestamp when the failure was observed and recorded on the aggregate.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM payments."__EFMigrationsHistory" WHERE "migration_id" = '20260604194448_CreatePaymentsTables') THEN
    CREATE INDEX ix_inbox_messages_processed_at_utc ON payments.inbox_messages (processed_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM payments."__EFMigrationsHistory" WHERE "migration_id" = '20260604194448_CreatePaymentsTables') THEN
    CREATE INDEX ix_payment_transactions_buyer_id ON payments.payment_transactions (buyer_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM payments."__EFMigrationsHistory" WHERE "migration_id" = '20260604194448_CreatePaymentsTables') THEN
    CREATE UNIQUE INDEX ux_payment_transactions_order_id ON payments.payment_transactions (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM payments."__EFMigrationsHistory" WHERE "migration_id" = '20260604194448_CreatePaymentsTables') THEN
    INSERT INTO payments."__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260604194448_CreatePaymentsTables', '10.0.8');
    END IF;
END $EF$;
