using Basket.Application.Baskets.Common.Contracts;
using Platform.CQRS;

namespace Basket.Application.Baskets.Checkout;

/// <summary>
/// Terminal transition for the basket owned by <paramref name="UserId"/>. Writes a
/// <c>BasketCheckoutInitiatedEvent</c> to the transactional outbox (topic
/// <c>basket.sessions</c>, key = UserId) and deletes the Redis entry on SQL-commit
/// success. Returns the <paramref name="CorrelationId"/> on success — it becomes
/// the downstream Checkout Saga's correlation id.
/// </summary>
/// <param name="UserId">Basket owner (JWT <c>sub</c>).</param>
/// <param name="CorrelationId">RFC 9562 Version-7 GUID generated by the caller.</param>
/// <param name="ShippingAddress">Shipping address — pass-through courier data per ADR-0005.</param>
/// <param name="BillingAddress">Billing address; may equal <paramref name="ShippingAddress"/>.</param>
/// <param name="PaymentMethodId">Reference to a saved payment method in the Payments service.</param>
public sealed record CheckoutBasketCommand(
    Guid UserId,
    Guid CorrelationId,
    CheckoutAddressDto ShippingAddress,
    CheckoutAddressDto BillingAddress,
    Guid PaymentMethodId) : ICommand<Guid>;
