<Project Sdk="Microsoft.NET.Sdk">
    <!-- Project-specific packages only (common packages in test/Directory.Build.props) -->
    <ItemGroup>
        <PackageReference Include="NetArchTest.eNhancedEdition" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\Invoicing\Invoicing.Api\Invoicing.Api.csproj" />
        <ProjectReference Include="..\..\services\Invoicing\Invoicing.Domain\Invoicing.Domain.csproj" />
        <ProjectReference Include="..\..\services\Invoicing\Invoicing.Application\Invoicing.Application.csproj" />
        <ProjectReference Include="..\..\services\Invoicing\Invoicing.Infrastructure\Invoicing.Infrastructure.csproj" />
        <ProjectReference Include="..\..\platform\Platform.Test.Framework\Platform.Test.Framework.csproj" />
    </ItemGroup>
</Project>
