DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'saga') THEN
        CREATE SCHEMA saga;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS saga."__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260419185512_Initial') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'saga') THEN
            CREATE SCHEMA saga;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260419185512_Initial') THEN
    CREATE TABLE saga."OutboxMessages" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        topic_name character varying(249) NOT NULL,
        kafka_key character varying(128),
        avro_payload bytea NOT NULL,
        type character varying(255) NOT NULL,
        headers character varying(8192),
        created_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
    );
    COMMENT ON TABLE saga."OutboxMessages" IS 'Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.';
    COMMENT ON COLUMN saga."OutboxMessages".id IS 'PK, Identity';
    COMMENT ON COLUMN saga."OutboxMessages".topic_name IS 'The Kafka topic where this message will be published. Set by the message producer.';
    COMMENT ON COLUMN saga."OutboxMessages".kafka_key IS 'Kafka Key - typically the Aggregate ID for proper event ordering and partitioning';
    COMMENT ON COLUMN saga."OutboxMessages".avro_payload IS 'Avro-serialized domain event payload';
    COMMENT ON COLUMN saga."OutboxMessages".type IS 'Avro type name of the serialized event (e.g., ''FeedbackChangedEvent'') for deserialization and observability';
    COMMENT ON COLUMN saga."OutboxMessages".headers IS 'JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.';
    COMMENT ON COLUMN saga."OutboxMessages".created_utc IS 'Creation timestamp (UTC).';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260419185512_Initial') THEN
    CREATE TABLE saga."PaymentProcessingSagaState" (
        correlation_id uuid NOT NULL,
        current_state character varying(64) NOT NULL,
        user_id uuid NOT NULL,
        payment_method_id uuid NOT NULL,
        amount numeric(19,4) NOT NULL,
        currency character varying(3) NOT NULL,
        idempotency_key character varying(128) NOT NULL,
        authorization_id character varying(256),
        authorization_expires_at_utc timestamp with time zone,
        payment_transaction_id uuid,
        initiated_at_utc timestamp with time zone NOT NULL,
        created_utc timestamp with time zone NOT NULL,
        last_modified_utc timestamp with time zone NOT NULL,
        authorized_at_utc timestamp with time zone,
        captured_at_utc timestamp with time zone,
        authorization_retry_count integer NOT NULL DEFAULT 0,
        capture_retry_count integer NOT NULL DEFAULT 0,
        error_code character varying(64),
        error_message character varying(2048),
        compensation_triggered boolean NOT NULL,
        compensation_completed_at_utc timestamp with time zone,
        authorization_timeout_token_id uuid,
        capture_timeout_token_id uuid,
        void_timeout_token_id uuid,
        refund_timeout_token_id uuid,
        success_finalization_timeout_token_id uuid,
        CONSTRAINT pk_payment_processing_saga_state PRIMARY KEY (correlation_id)
    );
    COMMENT ON TABLE saga."PaymentProcessingSagaState" IS 'Saga state for payment processing orchestration.';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".correlation_id IS 'Unique correlation ID for the payment saga';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".current_state IS 'Current state of the saga state machine';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".user_id IS 'User initiating the payment';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".payment_method_id IS 'ID of the saved payment method';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".amount IS 'Payment amount';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".currency IS 'ISO 4217 currency code';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".idempotency_key IS 'Idempotency key to prevent duplicate processing';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".authorization_id IS 'Authorization ID from payment provider';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".authorization_expires_at_utc IS 'UTC timestamp when authorization expires';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".payment_transaction_id IS 'Payment transaction ID after capture';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".initiated_at_utc IS 'UTC timestamp when payment was initiated';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".created_utc IS 'UTC timestamp when saga was created';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".last_modified_utc IS 'UTC timestamp when saga was last updated';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".authorized_at_utc IS 'UTC timestamp when authorization completed';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".captured_at_utc IS 'UTC timestamp when capture completed';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".authorization_retry_count IS 'Number of authorization retry attempts';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".capture_retry_count IS 'Number of capture retry attempts';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".error_code IS 'Error code for categorized failure handling';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".error_message IS 'Error message if failed';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".compensation_triggered IS 'Whether compensation has been triggered';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".compensation_completed_at_utc IS 'UTC timestamp when compensation completed';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".authorization_timeout_token_id IS 'Token ID for authorization timeout scheduler - set when schedule is active';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".capture_timeout_token_id IS 'Token ID for capture timeout scheduler - set when schedule is active';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".void_timeout_token_id IS 'Token ID for void timeout scheduler - set when schedule is active';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".refund_timeout_token_id IS 'Token ID for refund timeout scheduler - set when schedule is active';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".success_finalization_timeout_token_id IS 'Token ID for success finalization timeout scheduler - set when schedule is active';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260419185512_Initial') THEN
    CREATE INDEX "IX_PaymentSagaState_CurrentState" ON saga."PaymentProcessingSagaState" (current_state);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260419185512_Initial') THEN
    CREATE UNIQUE INDEX "IX_PaymentSagaState_IdempotencyKey" ON saga."PaymentProcessingSagaState" (idempotency_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260419185512_Initial') THEN
    CREATE INDEX "IX_PaymentSagaState_State_Created" ON saga."PaymentProcessingSagaState" (current_state, created_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260419185512_Initial') THEN
    CREATE INDEX "IX_PaymentSagaState_State_LastUpdated" ON saga."PaymentProcessingSagaState" (current_state, last_modified_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260419185512_Initial') THEN
    CREATE INDEX "IX_PaymentSagaState_UserId" ON saga."PaymentProcessingSagaState" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260419185512_Initial') THEN
    INSERT INTO saga."__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260419185512_Initial', '10.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260427000942_AddOrderIdToPaymentProcessingSagaState') THEN
    ALTER TABLE saga."PaymentProcessingSagaState" ADD order_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    COMMENT ON COLUMN saga."PaymentProcessingSagaState".order_id IS 'Ordering aggregate id this payment is attached to. Frozen at saga start.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260427000942_AddOrderIdToPaymentProcessingSagaState') THEN
    CREATE INDEX "IX_PaymentSagaState_OrderId" ON saga."PaymentProcessingSagaState" (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260427000942_AddOrderIdToPaymentProcessingSagaState') THEN
    INSERT INTO saga."__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260427000942_AddOrderIdToPaymentProcessingSagaState', '10.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260503214827_AddCheckoutSagaState') THEN
    CREATE TABLE saga."CheckoutSagaState" (
        correlation_id uuid NOT NULL,
        current_state character varying(64) NOT NULL,
        user_id uuid NOT NULL,
        total_amount numeric(19,4) NOT NULL,
        currency character varying(3) NOT NULL,
        payment_method_id uuid NOT NULL,
        basket_snapshot_json jsonb NOT NULL,
        shipping_address_json jsonb,
        billing_address_json jsonb,
        initiated_at_utc timestamp with time zone NOT NULL,
        order_id uuid,
        order_created_at_utc timestamp with time zone,
        reservation_ids_json jsonb NOT NULL,
        expected_reservations integer NOT NULL DEFAULT 0,
        pending_reservations integer NOT NULL DEFAULT 0,
        stock_reservation_started_at_utc timestamp with time zone,
        stock_reservation_completed_at_utc timestamp with time zone,
        payment_transaction_id uuid,
        payment_requested_at_utc timestamp with time zone,
        payment_completed_at_utc timestamp with time zone,
        order_confirmation_requested_at_utc timestamp with time zone,
        order_confirmed_at_utc timestamp with time zone,
        pending_releases integer NOT NULL DEFAULT 0,
        order_cancelled_received boolean NOT NULL DEFAULT FALSE,
        compensation_started_at_utc timestamp with time zone,
        compensation_completed_at_utc timestamp with time zone,
        compensation_triggered boolean NOT NULL,
        error_code character varying(64),
        error_message character varying(2048),
        failed_at_state character varying(64),
        order_creation_timeout_token_id uuid,
        stock_reservation_timeout_token_id uuid,
        payment_timeout_token_id uuid,
        order_confirmation_timeout_token_id uuid,
        compensation_timeout_token_id uuid,
        created_utc timestamp with time zone NOT NULL,
        last_modified_utc timestamp with time zone NOT NULL,
        CONSTRAINT pk_checkout_saga_state PRIMARY KEY (correlation_id)
    );
    COMMENT ON TABLE saga."CheckoutSagaState" IS 'Saga state for the checkout orchestration.';
    COMMENT ON COLUMN saga."CheckoutSagaState".correlation_id IS 'Workflow correlation id - equals BasketCheckoutInitiatedEvent.BasketCorrelationId (ADR-0008).';
    COMMENT ON COLUMN saga."CheckoutSagaState".current_state IS 'Current state of the saga state machine.';
    COMMENT ON COLUMN saga."CheckoutSagaState".user_id IS 'User initiating checkout. Becomes Ordering''s BuyerId.';
    COMMENT ON COLUMN saga."CheckoutSagaState".total_amount IS 'Sum of basket line totals captured at checkout initiation.';
    COMMENT ON COLUMN saga."CheckoutSagaState".currency IS 'ISO 4217 currency code.';
    COMMENT ON COLUMN saga."CheckoutSagaState".payment_method_id IS 'Saved payment method id - passed through to PaymentProcessingSaga.';
    COMMENT ON COLUMN saga."CheckoutSagaState".basket_snapshot_json IS 'Serialized basket line snapshot (immutable for the saga''s lifetime).';
    COMMENT ON COLUMN saga."CheckoutSagaState".shipping_address_json IS 'Serialized shipping Address value object. Nulled out on terminal per ADR-0011.';
    COMMENT ON COLUMN saga."CheckoutSagaState".billing_address_json IS 'Serialized billing Address value object. Nulled out on terminal per ADR-0011.';
    COMMENT ON COLUMN saga."CheckoutSagaState".initiated_at_utc IS 'UTC timestamp when the saga was initiated (copied from the Basket event).';
    COMMENT ON COLUMN saga."CheckoutSagaState".order_id IS 'Ordering aggregate id assigned after OrderCreatedEvent. Null until OrderCreated arrives.';
    COMMENT ON COLUMN saga."CheckoutSagaState".order_created_at_utc IS 'UTC timestamp when Ordering reported the order created.';
    COMMENT ON COLUMN saga."CheckoutSagaState".reservation_ids_json IS 'Serialized per-ProductId reservation tracking dictionary.';
    COMMENT ON COLUMN saga."CheckoutSagaState".expected_reservations IS 'Number of distinct ProductIds in the basket - target reservation count.';
    COMMENT ON COLUMN saga."CheckoutSagaState".pending_reservations IS 'Decremented on each StockReservedSagaEvent. Zero triggers AwaitingPayment.';
    COMMENT ON COLUMN saga."CheckoutSagaState".stock_reservation_started_at_utc IS 'UTC timestamp when stock reservation fan-out began.';
    COMMENT ON COLUMN saga."CheckoutSagaState".stock_reservation_completed_at_utc IS 'UTC timestamp when all reservations completed.';
    COMMENT ON COLUMN saga."CheckoutSagaState".payment_transaction_id IS 'Payment transaction id from PaymentProcessingSaga. Required for refund compensation.';
    COMMENT ON COLUMN saga."CheckoutSagaState".payment_requested_at_utc IS 'UTC timestamp when PaymentRequestedEvent was emitted.';
    COMMENT ON COLUMN saga."CheckoutSagaState".payment_completed_at_utc IS 'UTC timestamp when PaymentCompletedSagaEvent was received.';
    COMMENT ON COLUMN saga."CheckoutSagaState".order_confirmation_requested_at_utc IS 'UTC timestamp when ConfirmOrderCommand was dispatched.';
    COMMENT ON COLUMN saga."CheckoutSagaState".order_confirmed_at_utc IS 'UTC timestamp when OrderConfirmedSagaEvent arrived.';
    COMMENT ON COLUMN saga."CheckoutSagaState".pending_releases IS 'Decremented on each ReservationReleasedSagaEvent during compensation. Zero AND OrderCancelledReceived=true gates the transition to Compensated.';
    COMMENT ON COLUMN saga."CheckoutSagaState".order_cancelled_received IS 'True once OrderCancelledSagaEvent has been observed during compensation - gates the transition to Compensated.';
    COMMENT ON COLUMN saga."CheckoutSagaState".compensation_started_at_utc IS 'UTC timestamp at first transition into any Compensating* state.';
    COMMENT ON COLUMN saga."CheckoutSagaState".compensation_completed_at_utc IS 'UTC timestamp at transition into Compensated.';
    COMMENT ON COLUMN saga."CheckoutSagaState".compensation_triggered IS 'Set true on the first Compensating* transition.';
    COMMENT ON COLUMN saga."CheckoutSagaState".error_code IS 'Categorised failure code (e.g., STOCK_UNAVAILABLE, PAYMENT_FAILED).';
    COMMENT ON COLUMN saga."CheckoutSagaState".error_message IS 'Human-readable failure message.';
    COMMENT ON COLUMN saga."CheckoutSagaState".failed_at_state IS 'Name of the state when failure first occurred. Aids ops forensics.';
    COMMENT ON COLUMN saga."CheckoutSagaState".order_creation_timeout_token_id IS 'Token ID for the order-creation timeout scheduler - set when schedule is active.';
    COMMENT ON COLUMN saga."CheckoutSagaState".stock_reservation_timeout_token_id IS 'Token ID for the stock-reservation timeout scheduler - set when schedule is active.';
    COMMENT ON COLUMN saga."CheckoutSagaState".payment_timeout_token_id IS 'Token ID for the payment timeout scheduler - set when schedule is active.';
    COMMENT ON COLUMN saga."CheckoutSagaState".order_confirmation_timeout_token_id IS 'Token ID for the order-confirmation timeout scheduler - set when schedule is active.';
    COMMENT ON COLUMN saga."CheckoutSagaState".compensation_timeout_token_id IS 'Token ID for the compensation timeout scheduler - set when schedule is active.';
    COMMENT ON COLUMN saga."CheckoutSagaState".created_utc IS 'UTC timestamp when saga row was created.';
    COMMENT ON COLUMN saga."CheckoutSagaState".last_modified_utc IS 'UTC timestamp when saga row was last mutated.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260503214827_AddCheckoutSagaState') THEN
    CREATE INDEX "IX_CheckoutSagaState_CurrentState" ON saga."CheckoutSagaState" (current_state);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260503214827_AddCheckoutSagaState') THEN
    CREATE INDEX "IX_CheckoutSagaState_OrderId" ON saga."CheckoutSagaState" (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260503214827_AddCheckoutSagaState') THEN
    CREATE INDEX "IX_CheckoutSagaState_State_Created" ON saga."CheckoutSagaState" (current_state, created_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260503214827_AddCheckoutSagaState') THEN
    CREATE INDEX "IX_CheckoutSagaState_State_LastUpdated" ON saga."CheckoutSagaState" (current_state, last_modified_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260503214827_AddCheckoutSagaState') THEN
    CREATE INDEX "IX_CheckoutSagaState_UserId" ON saga."CheckoutSagaState" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saga."__EFMigrationsHistory" WHERE "migration_id" = '20260503214827_AddCheckoutSagaState') THEN
    INSERT INTO saga."__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260503214827_AddCheckoutSagaState', '10.0.5');
    END IF;
END $EF$;
