-- Test-only provisioning for the outbox publish-path integration suite.
-- Applied to a throwaway PostgreSQL Testcontainer by Evolve (see PostgreSqlTestContainer).
--
-- Columns, types and constraints MUST match what the platform model produces. Source of truth:
--   Platform.ReliableMessaging.Outbox.EFCore.OutboxMessageConfiguration
--   + EFCore.NamingConventions snake_case convention on OutboxDbContext (column casing).

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'outbox_relay_tests') THEN
        CREATE SCHEMA outbox_relay_tests;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS outbox_relay_tests.outbox_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    topic_name character varying(249) NOT NULL,
    kafka_key character varying(128),
    avro_payload bytea NOT NULL,
    type character varying(255) NOT NULL,
    headers character varying(8192),
    created_utc timestamp with time zone NOT NULL,
    CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
);
