#!/bin/bash
# Post-attach script - runs each time VS Code attaches to the container.
# Brings up the storage dependencies (core profile) so Postgres is ready
# immediately; the full multi-BC stack is an explicit opt-in (see below).

# core = Postgres + redis-basket + Azurite + Mailpit. The full stack (every BC API,
# outbox relays, Kafka, Schema Registry, Keycloak, observability) is `--profile full`.
echo "Starting storage dependencies (docker compose --profile core)..."
if docker compose --profile core up -d; then
  echo "   storage dependencies are up."
else
  echo "   ⚠️  'docker compose --profile core up -d' failed — start it manually once Docker is ready."
fi

echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "✅ DotNetAtlas Development Environment Ready!"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📖 Quick Start:"
echo "   • Run tests (Testcontainers — no compose stack needed):"
echo "       dotnet test"
echo "   • Bring the full stack up once — Kafka, Keycloak, redis-cache, observability, and"
echo "     every BC API on 8100-8107; Flyway applies all migrations:"
echo "       docker compose --profile full up -d"
echo "   • Then hit a containerised BC directly (8100-8107), or iterate on one as a host"
echo "     process against those deps:"
echo "       dotnet run --project services/Catalog/Catalog.Api   # → http://localhost:5101/swagger"
echo ""
echo "🧩 Bounded-context API ports:"
echo "   ┌───────────────┬───────────────────────┬──────────────────────────────┐"
echo "   │ Bounded ctx   │ dotnet run (local)    │ --profile full (container)   │"
echo "   ├───────────────┼───────────────────────┼──────────────────────────────┤"
echo "   │ Basket        │ http://localhost:5100 │ http://localhost:8104        │"
echo "   │ Catalog       │ http://localhost:5101 │ http://localhost:8100        │"
echo "   │ Inventory     │ http://localhost:5102 │ http://localhost:8105        │"
echo "   │ Invoicing     │ http://localhost:5103 │ http://localhost:8102        │"
echo "   │ Notifications │ http://localhost:5104 │ http://localhost:8103        │"
echo "   │ Ordering      │ http://localhost:5105 │ http://localhost:8101        │"
echo "   │ Payments      │ http://localhost:5106 │ http://localhost:8106        │"
echo "   └───────────────┴───────────────────────┴──────────────────────────────┘"
echo "   (Saga orchestrator: container only → http://localhost:8107)"
echo ""
echo "🔗 Infrastructure URLs ([full] = requires --profile full):"
echo "   ┌─────────────────────┬───────────────────────────────────────────────┐"
echo "   │ Service             │ URL / endpoint                                │"
echo "   ├─────────────────────┼───────────────────────────────────────────────┤"
echo "   │ PostgreSQL          │ localhost:5433 (postgres / POSTGRES_PASSWORD) │"
echo "   │ Redis (basket)      │ localhost:6379                                │"
echo "   │ Redis (cache)       │ localhost:6380                          [full] │"
echo "   │ Redis Insight       │ http://localhost:5540                  [full] │"
echo "   │ Mailpit (email)     │ http://localhost:8025                         │"
echo "   │ Seq (logging)       │ http://localhost:5341                  [full] │"
echo "   │ Jaeger (tracing)    │ http://localhost:16686                 [full] │"
echo "   │ Prometheus          │ http://localhost:9090                  [full] │"
echo "   │ Grafana             │ http://localhost:3000                  [full] │"
echo "   │ Kafka (AKHQ UI)     │ http://localhost:9000                  [full] │"
echo "   │ Schema Registry     │ http://localhost:8081                  [full] │"
echo "   │ Keycloak            │ http://localhost:9011                  [full] │"
echo "   │ Azurite (blob)      │ http://localhost:10000                        │"
echo "   └─────────────────────┴───────────────────────────────────────────────┘"
echo ""
echo "🗄️  Postgres databases (one per bounded context; created by src/postgres/init-bcs.sql):"
echo "   Catalog · Basket · Inventory · Ordering · Invoicing · Payments · Notifications · Saga"
echo "   Connect via the PostgreSQL extension → host 127.0.0.1, port 5433, user postgres,"
echo "   password = POSTGRES_PASSWORD from .env."
echo ""
echo "🛠️  Useful commands:"
echo "   • Run all tests:        dotnet test"
echo "   • Tests with coverage:  pwsh test/test-coverage.ps1"
echo "   • Storage deps only:    docker compose --profile core up -d"
echo "   • Whole stack:          docker compose --profile full up -d   (Flyway applies all BC migrations)"
echo "   • EF migration (add):   dotnet ef migrations add <Name> -p services/<BC>/<BC>.Infrastructure -s services/<BC>/<BC>.Api"
echo "   • EF database update:   dotnet ef database update -p services/<BC>/<BC>.Infrastructure -s services/<BC>/<BC>.Api"
echo ""
