#!/bin/bash
# Post-attach script - runs each time VS Code attaches to the container

echo "Starting infrastructure services..."

docker-compose up -d

echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "✅ DotNetAtlas Development Environment Ready!"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📖 Quick Start Guide:"
echo "   1. Run API:               dotnet run --project src/DotNetAtlas.Api"
echo "   2. Run tests:             dotnet test"
echo "   3. View API docs:         http://localhost:5159/swagger"
echo ""
echo "🔗 Service URLs:"
echo "   ┌─────────────────────────────────────────────────────────────────────────┐"
echo "   │ Service             │ URL                                              │"
echo "   ├─────────────────────────────────────────────────────────────────────────┤"
echo "   │ API                 │ http://localhost:5159                            │"
echo "   │ SQL Server          │ localhost:12345 (sa / from .env)                 │"
echo "   │ Redis               │ localhost:12346                                  │"
echo "   │ Redis Insight       │ http://localhost:5540                            │"
echo "   │ Seq (Logging)       │ http://localhost:5341                            │"
echo "   │ Jaeger (Tracing)    │ http://localhost:16686                           │"
echo "   │ Prometheus          │ http://localhost:9090                            │"
echo "   │ Grafana             │ http://localhost:3000                            │"
echo "   │ Kafka (AKHQ)        │ http://localhost:9000                            │"
echo "   │ Schema Registry     │ http://localhost:8081                            │"
echo "   │ FusionAuth          │ http://localhost:9011                            │"
echo "   └─────────────────────────────────────────────────────────────────────────┘"
echo ""
echo "🛠️  Useful Commands:"
echo "   - Run all tests:         dotnet test"
echo "   - Run with coverage:     pwsh test/test-coverage.ps1"
echo "   - EF migrations:         dotnet ef migrations add <Name> -p src/DotNetAtlas.Infrastructure -s src/DotNetAtlas.Api"
echo "   - Update database:       dotnet ef database update -p src/DotNetAtlas.Infrastructure -s src/DotNetAtlas.Api"
echo ""
