// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Payments.Payments
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted when a payment is requested. Triggers the Payment Saga to process authorization and capture. This is a 'dumb' payment event - it knows nothing about the business context (subscription, order, etc.).
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class PaymentRequestedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PaymentRequestedEvent"",""doc"":""Event emitted when a payment is requested. Triggers the Payment Saga to process authorization and capture. This is a 'dumb' payment event - it knows nothing about the business context (subscription, order, etc.)."",""namespace"":""Payments.Payments"",""fields"":[{""name"":""CorrelationId"",""doc"":""Correlation ID shared across the entire business flow (e.g., purchase → payment → activation)."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""UserId"",""doc"":""User initiating the payment."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""PaymentMethodId"",""doc"":""ID of the saved payment method to use for this transaction."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Amount"",""doc"":""Payment amount."",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":19,""scale"":4}},{""name"":""Currency"",""doc"":""ISO 4217 currency code (e.g., 'USD', 'EUR')."",""type"":""string""},{""name"":""IdempotencyKey"",""doc"":""Idempotency key for preventing duplicate payment processing."",""type"":""string""},{""name"":""RequestedAtUtc"",""doc"":""UTC timestamp when payment was requested."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Correlation ID shared across the entire business flow (e.g., purchase → payment → activation).
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// User initiating the payment.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// ID of the saved payment method to use for this transaction.
		/// </summary>
		private System.Guid _PaymentMethodId;
		/// <summary>
		/// Payment amount.
		/// </summary>
		private Avro.AvroDecimal _Amount;
		/// <summary>
		/// ISO 4217 currency code (e.g., 'USD', 'EUR').
		/// </summary>
		private string _Currency;
		/// <summary>
		/// Idempotency key for preventing duplicate payment processing.
		/// </summary>
		private string _IdempotencyKey;
		/// <summary>
		/// UTC timestamp when payment was requested.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PaymentRequestedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Correlation ID shared across the entire business flow (e.g., purchase → payment → activation).
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// User initiating the payment.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// ID of the saved payment method to use for this transaction.
		/// </summary>
		public System.Guid PaymentMethodId
		{
			get
			{
				return this._PaymentMethodId;
			}
			set
			{
				this._PaymentMethodId = value;
			}
		}
		/// <summary>
		/// Payment amount.
		/// </summary>
		public Avro.AvroDecimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				this._Amount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code (e.g., 'USD', 'EUR').
		/// </summary>
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		/// <summary>
		/// Idempotency key for preventing duplicate payment processing.
		/// </summary>
		public string IdempotencyKey
		{
			get
			{
				return this._IdempotencyKey;
			}
			set
			{
				this._IdempotencyKey = value;
			}
		}
		/// <summary>
		/// UTC timestamp when payment was requested.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CorrelationId;
			case 1: return this.UserId;
			case 2: return this.PaymentMethodId;
			case 3: return this.Amount;
			case 4: return this.Currency;
			case 5: return this.IdempotencyKey;
			case 6: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CorrelationId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.PaymentMethodId = (System.Guid)fieldValue; break;
			case 3: this.Amount = (Avro.AvroDecimal)fieldValue; break;
			case 4: this.Currency = (System.String)fieldValue; break;
			case 5: this.IdempotencyKey = (System.String)fieldValue; break;
			case 6: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
