// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Payments.Payments
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted by Payment Saga when payment processing is complete (authorization + capture succeeded). Business sagas listen to this event to continue their workflow.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class PaymentCompletedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PaymentCompletedEvent"",""doc"":""Event emitted by Payment Saga when payment processing is complete (authorization + capture succeeded). Business sagas listen to this event to continue their workflow."",""namespace"":""Payments.Payments"",""fields"":[{""name"":""CorrelationId"",""doc"":""Correlation ID shared with the business saga that initiated the payment."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""UserId"",""doc"":""User whose payment was completed."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""PaymentTransactionId"",""doc"":""Payment transaction ID. Used for refunds if business operation fails."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Amount"",""doc"":""Amount that was charged."",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":19,""scale"":4}},{""name"":""Currency"",""doc"":""ISO 4217 currency code."",""type"":""string""},{""name"":""CompletedAtUtc"",""doc"":""UTC timestamp when payment was completed."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Correlation ID shared with the business saga that initiated the payment.
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// User whose payment was completed.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Payment transaction ID. Used for refunds if business operation fails.
		/// </summary>
		private System.Guid _PaymentTransactionId;
		/// <summary>
		/// Amount that was charged.
		/// </summary>
		private Avro.AvroDecimal _Amount;
		/// <summary>
		/// ISO 4217 currency code.
		/// </summary>
		private string _Currency;
		/// <summary>
		/// UTC timestamp when payment was completed.
		/// </summary>
		private System.DateTime _CompletedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PaymentCompletedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Correlation ID shared with the business saga that initiated the payment.
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// User whose payment was completed.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Payment transaction ID. Used for refunds if business operation fails.
		/// </summary>
		public System.Guid PaymentTransactionId
		{
			get
			{
				return this._PaymentTransactionId;
			}
			set
			{
				this._PaymentTransactionId = value;
			}
		}
		/// <summary>
		/// Amount that was charged.
		/// </summary>
		public Avro.AvroDecimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				this._Amount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code.
		/// </summary>
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		/// <summary>
		/// UTC timestamp when payment was completed.
		/// </summary>
		public System.DateTime CompletedAtUtc
		{
			get
			{
				return this._CompletedAtUtc;
			}
			set
			{
				this._CompletedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CorrelationId;
			case 1: return this.UserId;
			case 2: return this.PaymentTransactionId;
			case 3: return this.Amount;
			case 4: return this.Currency;
			case 5: return this.CompletedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CorrelationId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.PaymentTransactionId = (System.Guid)fieldValue; break;
			case 3: this.Amount = (Avro.AvroDecimal)fieldValue; break;
			case 4: this.Currency = (System.String)fieldValue; break;
			case 5: this.CompletedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
