// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Payments.Payments
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Command sent by Payment Saga to void (cancel) an authorized payment that has not yet been captured.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class VoidPaymentCommand : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""VoidPaymentCommand"",""doc"":""Command sent by Payment Saga to void (cancel) an authorized payment that has not yet been captured."",""namespace"":""Payments.Payments"",""fields"":[{""name"":""CorrelationId"",""doc"":""Correlation ID for tracking the workflow."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""UserId"",""doc"":""User whose payment authorization to void."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""AuthorizationId"",""doc"":""Authorization ID from the payment provider to void."",""type"":""string""},{""name"":""Reason"",""doc"":""Reason for voiding the authorization."",""type"":""string""},{""name"":""RequestedAtUtc"",""doc"":""UTC timestamp when void was requested."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Correlation ID for tracking the workflow.
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// User whose payment authorization to void.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Authorization ID from the payment provider to void.
		/// </summary>
		private string _AuthorizationId;
		/// <summary>
		/// Reason for voiding the authorization.
		/// </summary>
		private string _Reason;
		/// <summary>
		/// UTC timestamp when void was requested.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return VoidPaymentCommand._SCHEMA;
			}
		}
		/// <summary>
		/// Correlation ID for tracking the workflow.
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// User whose payment authorization to void.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Authorization ID from the payment provider to void.
		/// </summary>
		public string AuthorizationId
		{
			get
			{
				return this._AuthorizationId;
			}
			set
			{
				this._AuthorizationId = value;
			}
		}
		/// <summary>
		/// Reason for voiding the authorization.
		/// </summary>
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				this._Reason = value;
			}
		}
		/// <summary>
		/// UTC timestamp when void was requested.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CorrelationId;
			case 1: return this.UserId;
			case 2: return this.AuthorizationId;
			case 3: return this.Reason;
			case 4: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CorrelationId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.AuthorizationId = (System.String)fieldValue; break;
			case 3: this.Reason = (System.String)fieldValue; break;
			case 4: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
