using System.Reflection;
using Mono.Cecil;
using Mono.Cecil.Rocks;
using NetArchTest.Rules;

namespace Notifications.ArchitectureTests;

/// <summary>
/// Shared base for Notifications architecture tests. Anchors the four layer assemblies via the
/// <c>IAssemblyMarker</c> interfaces and exposes the custom <see cref="ICustomRule"/>
/// implementations the rule set leans on.
/// </summary>
public abstract class BaseTest
{
    protected static readonly Assembly DomainAssembly = typeof(global::Notifications.Domain.IAssemblyMarker).Assembly;
    protected static readonly Assembly ApplicationAssembly = typeof(global::Notifications.Application.IAssemblyMarker).Assembly;
    protected static readonly Assembly InfrastructureAssembly = typeof(global::Notifications.Infrastructure.IAssemblyMarker).Assembly;
    protected static readonly Assembly PresentationAssembly = typeof(global::Notifications.Api.IAssemblyMarker).Assembly;

    protected sealed class PrivateConstructorsRule : ICustomRule
    {
        public bool MeetsRule(TypeDefinition type)
        {
            foreach (var constructor in type.GetConstructors())
            {
                // exclude autogenerated static ctor for private static fields like Regex etc.
                if (!constructor.IsStatic && !constructor.IsPrivate)
                {
                    return false;
                }
            }

            return true;
        }
    }
}
