// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Basket.Sessions
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Emitted when a user checks out their basket. Triggers the Checkout Saga. The basket is deleted from Redis after this event is written to the outbox.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class BasketCheckoutInitiatedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"BasketCheckoutInitiatedEvent\",\"doc\":\"Emitted when a user" +
				" checks out their basket. Triggers the Checkout Saga. The basket is deleted from" +
				" Redis after this event is written to the outbox.\",\"namespace\":\"Basket.Sessions\"" +
				",\"fields\":[{\"name\":\"OrderId\",\"doc\":\"Pre-assigned Order identity (UUID v7), alloc" +
				"ated by Basket\'s checkout command handler and carried as a pass-through field. B" +
				"ecomes the Checkout Saga\'s CorrelationId and the Order aggregate\'s id. See ADR-0" +
				"029.\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"UserId\",\"doc\":\"Ide" +
				"ntifier of the user whose basket is being checked out. Also the Kafka message ke" +
				"y for partitioning.\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"Ite" +
				"ms\",\"doc\":\"All line items of the basket at the moment of checkout. Never empty (" +
				"empty-basket checkout is rejected at the aggregate).\",\"type\":{\"type\":\"array\",\"it" +
				"ems\":{\"type\":\"record\",\"name\":\"BasketCheckoutItem\",\"doc\":\"One line of the basket " +
				"at the moment of checkout. Prices reflect the snapshot captured at add-time (or " +
				"at the last explicit refresh).\",\"namespace\":\"Basket.Sessions\",\"fields\":[{\"name\":" +
				"\"ProductId\",\"doc\":\"Catalog Product identifier. Consumers use this to reserve sto" +
				"ck and to load authoritative product data.\",\"type\":{\"type\":\"string\",\"logicalType" +
				"\":\"uuid\"}},{\"name\":\"Sku\",\"doc\":\"Catalog SKU at the time of checkout. Copied from" +
				" the snapshot for consumer convenience.\",\"type\":\"string\"},{\"name\":\"Name\",\"doc\":\"" +
				"Product name at the time of checkout. Copied from the snapshot for order history" +
				"/display.\",\"type\":\"string\"},{\"name\":\"UnitPriceAmount\",\"doc\":\"Snapshot unit price" +
				" amount. Decimal 19,4 matches the Catalog price precision.\",\"type\":{\"type\":\"byte" +
				"s\",\"logicalType\":\"decimal\",\"precision\":19,\"scale\":4}},{\"name\":\"UnitPriceCurrency" +
				"\",\"doc\":\"ISO 4217 currency code of UnitPriceAmount. Uniform across all items (en" +
				"forced by the Basket aggregate invariant).\",\"type\":\"string\"},{\"name\":\"Quantity\"," +
				"\"doc\":\"Number of units of this product in the basket. Always >= 1.\",\"type\":\"int\"" +
				"},{\"name\":\"LineTotal\",\"doc\":\"UnitPriceAmount * Quantity, pre-computed for consum" +
				"er convenience. Equals the domain value of the line at checkout.\",\"type\":{\"type\"" +
				":\"bytes\",\"logicalType\":\"decimal\",\"precision\":19,\"scale\":4}}]}}},{\"name\":\"TotalAm" +
				"ount\",\"doc\":\"Sum of all LineTotal values. Pre-computed so consumers do not have " +
				"to re-sum; they SHOULD re-verify.\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal" +
				"\",\"precision\":19,\"scale\":4}},{\"name\":\"Currency\",\"doc\":\"ISO 4217 currency code fo" +
				"r TotalAmount. Equals all item UnitPriceCurrency values.\",\"type\":\"string\"},{\"nam" +
				"e\":\"ShippingAddress\",\"doc\":\"Shipping address collected by the BFF/client at chec" +
				"kout time and passed through the CheckoutBasketCommand. Basket does NOT own addr" +
				"esses; it carries this payload to the saga unchanged.\",\"type\":{\"type\":\"record\",\"" +
				"name\":\"CheckoutAddress\",\"doc\":\"Postal address supplied at checkout. Basket is a " +
				"pass-through: it does not validate deeply (only non-empty + ISO country code) an" +
				"d does not persist addresses beyond this event. The Ordering service re-snapshot" +
				"s this into the Order aggregate.\",\"namespace\":\"Basket.Sessions\",\"fields\":[{\"name" +
				"\":\"Street1\",\"doc\":\"Primary street line.\",\"type\":\"string\"},{\"name\":\"Street2\",\"doc" +
				"\":\"Optional second street line (apartment, suite, etc.).\",\"default\":null,\"type\":" +
				"[\"null\",\"string\"]},{\"name\":\"City\",\"doc\":\"City name.\",\"type\":\"string\"},{\"name\":\"S" +
				"tate\",\"doc\":\"Optional state/province/region. Null for countries without this con" +
				"cept.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PostalCode\",\"doc\":\"Post" +
				"al or ZIP code.\",\"type\":\"string\"},{\"name\":\"CountryCode\",\"doc\":\"ISO 3166-1 alpha-" +
				"2 country code (e.g., \'US\', \'CZ\').\",\"type\":\"string\"}]}},{\"name\":\"BillingAddress\"" +
				",\"doc\":\"Billing address. Same shape as ShippingAddress; may be identical to it.\"" +
				",\"type\":\"CheckoutAddress\"},{\"name\":\"PaymentMethodId\",\"doc\":\"Reference to a saved" +
				" payment method in the Payments service. Collected at checkout by the BFF/client" +
				"; passed through unchanged. Validation is delegated to Payments during payment.\"" +
				",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"InitiatedAtUtc\",\"doc\":\"" +
				"UTC timestamp when the CheckoutBasketCommand was handled and the domain event wa" +
				"s raised.\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
		/// <summary>
		/// Pre-assigned Order identity (UUID v7), allocated by Basket's checkout command handler and carried as a pass-through field. Becomes the Checkout Saga's CorrelationId and the Order aggregate's id. See ADR-0029.
		/// </summary>
		private System.Guid _OrderId;
		/// <summary>
		/// Identifier of the user whose basket is being checked out. Also the Kafka message key for partitioning.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// All line items of the basket at the moment of checkout. Never empty (empty-basket checkout is rejected at the aggregate).
		/// </summary>
		private IList<Basket.Sessions.BasketCheckoutItem> _Items;
		/// <summary>
		/// Sum of all LineTotal values. Pre-computed so consumers do not have to re-sum; they SHOULD re-verify.
		/// </summary>
		private Avro.AvroDecimal _TotalAmount;
		/// <summary>
		/// ISO 4217 currency code for TotalAmount. Equals all item UnitPriceCurrency values.
		/// </summary>
		private string _Currency;
		/// <summary>
		/// Shipping address collected by the BFF/client at checkout time and passed through the CheckoutBasketCommand. Basket does NOT own addresses; it carries this payload to the saga unchanged.
		/// </summary>
		private Basket.Sessions.CheckoutAddress _ShippingAddress;
		/// <summary>
		/// Billing address. Same shape as ShippingAddress; may be identical to it.
		/// </summary>
		private Basket.Sessions.CheckoutAddress _BillingAddress;
		/// <summary>
		/// Reference to a saved payment method in the Payments service. Collected at checkout by the BFF/client; passed through unchanged. Validation is delegated to Payments during payment.
		/// </summary>
		private System.Guid _PaymentMethodId;
		/// <summary>
		/// UTC timestamp when the CheckoutBasketCommand was handled and the domain event was raised.
		/// </summary>
		private System.DateTime _InitiatedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return BasketCheckoutInitiatedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Pre-assigned Order identity (UUID v7), allocated by Basket's checkout command handler and carried as a pass-through field. Becomes the Checkout Saga's CorrelationId and the Order aggregate's id. See ADR-0029.
		/// </summary>
		public System.Guid OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// Identifier of the user whose basket is being checked out. Also the Kafka message key for partitioning.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// All line items of the basket at the moment of checkout. Never empty (empty-basket checkout is rejected at the aggregate).
		/// </summary>
		public IList<Basket.Sessions.BasketCheckoutItem> Items
		{
			get
			{
				return this._Items;
			}
			set
			{
				this._Items = value;
			}
		}
		/// <summary>
		/// Sum of all LineTotal values. Pre-computed so consumers do not have to re-sum; they SHOULD re-verify.
		/// </summary>
		public Avro.AvroDecimal TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				this._TotalAmount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code for TotalAmount. Equals all item UnitPriceCurrency values.
		/// </summary>
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		/// <summary>
		/// Shipping address collected by the BFF/client at checkout time and passed through the CheckoutBasketCommand. Basket does NOT own addresses; it carries this payload to the saga unchanged.
		/// </summary>
		public Basket.Sessions.CheckoutAddress ShippingAddress
		{
			get
			{
				return this._ShippingAddress;
			}
			set
			{
				this._ShippingAddress = value;
			}
		}
		/// <summary>
		/// Billing address. Same shape as ShippingAddress; may be identical to it.
		/// </summary>
		public Basket.Sessions.CheckoutAddress BillingAddress
		{
			get
			{
				return this._BillingAddress;
			}
			set
			{
				this._BillingAddress = value;
			}
		}
		/// <summary>
		/// Reference to a saved payment method in the Payments service. Collected at checkout by the BFF/client; passed through unchanged. Validation is delegated to Payments during payment.
		/// </summary>
		public System.Guid PaymentMethodId
		{
			get
			{
				return this._PaymentMethodId;
			}
			set
			{
				this._PaymentMethodId = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the CheckoutBasketCommand was handled and the domain event was raised.
		/// </summary>
		public System.DateTime InitiatedAtUtc
		{
			get
			{
				return this._InitiatedAtUtc;
			}
			set
			{
				this._InitiatedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.UserId;
			case 2: return this.Items;
			case 3: return this.TotalAmount;
			case 4: return this.Currency;
			case 5: return this.ShippingAddress;
			case 6: return this.BillingAddress;
			case 7: return this.PaymentMethodId;
			case 8: return this.InitiatedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.Items = (IList<Basket.Sessions.BasketCheckoutItem>)fieldValue; break;
			case 3: this.TotalAmount = (Avro.AvroDecimal)fieldValue; break;
			case 4: this.Currency = (System.String)fieldValue; break;
			case 5: this.ShippingAddress = (Basket.Sessions.CheckoutAddress)fieldValue; break;
			case 6: this.BillingAddress = (Basket.Sessions.CheckoutAddress)fieldValue; break;
			case 7: this.PaymentMethodId = (System.Guid)fieldValue; break;
			case 8: this.InitiatedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
