using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.Persistence.Database.Migrations
{
    /// <inheritdoc />
    public partial class CreateCatalogTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "catalog");

            migrationBuilder.CreateTable(
                name: "categories",
                schema: "catalog",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Primary key (Guid v7 — time-ordered)."),
                    name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false, comment: "Display name (1..100)."),
                    parent_category_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "Parent category id (null for roots) — referenced by id only, no navigation."),
                    path = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false, comment: "Materialized closure (max depth 5)."),
                    created_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "Row-level audit: created timestamp (UTC). Set by interceptor."),
                    last_modified_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "Row-level audit: last-modified timestamp (UTC). Set by interceptor."),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false, comment: "Optimistic concurrency token (Postgres xmin system column).")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_categories", x => x.id);
                },
                comment: "Category aggregate — taxonomy node with materialized path.");

            migrationBuilder.CreateTable(
                name: "inbox_messages",
                schema: "catalog",
                columns: table => new
                {
                    message_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Unique message identifier (Primary Key)."),
                    processed_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "UTC timestamp when the message was processed.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_inbox_messages", x => x.message_id);
                },
                comment: "Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.");

            migrationBuilder.CreateTable(
                name: "outbox_messages",
                schema: "catalog",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false, comment: "PK, Identity")
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    topic_name = table.Column<string>(type: "character varying(249)", unicode: false, maxLength: 249, nullable: false, comment: "The Kafka topic where this message will be published. Set by the message producer."),
                    kafka_key = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true, comment: "Kafka Key - typically the Aggregate ID for proper event ordering and partitioning"),
                    avro_payload = table.Column<byte[]>(type: "bytea", nullable: false, comment: "Avro-serialized domain event payload"),
                    type = table.Column<string>(type: "character varying(255)", unicode: false, maxLength: 255, nullable: false, comment: "Avro type name of the serialized event (e.g., 'FeedbackChangedEvent') for deserialization and observability"),
                    headers = table.Column<string>(type: "character varying(8192)", maxLength: 8192, nullable: true, comment: "JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation."),
                    created_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "Creation timestamp (UTC).")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_outbox_messages", x => x.id);
                },
                comment: "Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.");

            migrationBuilder.CreateTable(
                name: "products",
                schema: "catalog",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Primary key (Guid v7 — time-ordered)."),
                    sku = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false, comment: "Business key — unique per Catalog."),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false, comment: "Display name (1..200)."),
                    description = table.Column<string>(type: "text", nullable: false, comment: "Long-form description; truncated to 4000 chars at write time."),
                    category_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Catalog category identifier — referenced by id only, no navigation per arch test."),
                    brand_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false, comment: "Brand name (1..100)."),
                    price_amount = table.Column<decimal>(type: "numeric(19,4)", precision: 19, scale: 4, nullable: false, comment: "Price amount."),
                    price_currency = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false, comment: "ISO 4217 currency code."),
                    status = table.Column<int>(type: "integer", nullable: false, comment: "Lifecycle status (Active|Discontinued); SmartEnum integer Value."),
                    dimensions_length = table.Column<decimal>(type: "numeric(10,2)", precision: 10, scale: 2, nullable: true),
                    dimensions_width = table.Column<decimal>(type: "numeric(10,2)", precision: 10, scale: 2, nullable: true),
                    dimensions_height = table.Column<decimal>(type: "numeric(10,2)", precision: 10, scale: 2, nullable: true),
                    dimensions_unit = table.Column<string>(type: "character varying(8)", maxLength: 8, nullable: true),
                    created_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "Row-level audit: created timestamp (UTC). Set by interceptor."),
                    last_modified_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "Row-level audit: last-modified timestamp (UTC). Set by interceptor."),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false, comment: "Optimistic concurrency token (Postgres xmin system column).")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_products", x => x.id);
                },
                comment: "Product aggregate — write-side state for a sellable item.");

            migrationBuilder.CreateTable(
                name: "product_search_view",
                schema: "catalog",
                columns: table => new
                {
                    product_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Mirrors Product.Id."),
                    sku = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    description = table.Column<string>(type: "text", nullable: false),
                    category_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Mirrors Product.CategoryId."),
                    category_path = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false, comment: "Materialized category path; rewritten on Reparent by CategoryPathService."),
                    category_breadcrumb = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false, comment: "Denormalized human-readable breadcrumb — may temporarily lag after Reparent."),
                    brand_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    price_amount = table.Column<decimal>(type: "numeric(19,4)", precision: 19, scale: 4, nullable: false),
                    price_currency = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false, comment: "Lifecycle status name (Active|Discontinued)."),
                    dimensions_json = table.Column<string>(type: "jsonb", nullable: true, comment: "Serialized Dimensions VO; null for digital/service products."),
                    images_json = table.Column<string>(type: "jsonb", nullable: false, defaultValue: "[]"),
                    is_sellable = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false, comment: "Computed flag — wired up by the StockLevelChangedEvent Kafka inbox consumer."),
                    created_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    last_updated_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_product_search_view", x => x.product_id);
                    table.ForeignKey(
                        name: "fk_product_search_view_categories_category_id",
                        column: x => x.category_id,
                        principalSchema: "catalog",
                        principalTable: "categories",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "Denormalized read view of Product (catalog.md § 9). Upserted in-process by domain-event handlers in the same transaction as write-model saves.");

            migrationBuilder.CreateTable(
                name: "product_images",
                schema: "catalog",
                columns: table => new
                {
                    product_id = table.Column<Guid>(type: "uuid", nullable: false),
                    ordinal = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    url = table.Column<string>(type: "character varying(2048)", maxLength: 2048, nullable: false),
                    alt_text = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    display_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_product_images", x => new { x.product_id, x.ordinal });
                    table.ForeignKey(
                        name: "fk_product_images_products_product_id",
                        column: x => x.product_id,
                        principalSchema: "catalog",
                        principalTable: "products",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                },
                comment: "Ordered image collection — owned by the Product aggregate.");

            migrationBuilder.CreateIndex(
                name: "ix_categories_path",
                schema: "catalog",
                table: "categories",
                column: "path");

            migrationBuilder.CreateIndex(
                name: "ix_inbox_messages_processed_at_utc",
                schema: "catalog",
                table: "inbox_messages",
                column: "processed_at_utc");

            migrationBuilder.CreateIndex(
                name: "ix_product_search_view_category_id",
                schema: "catalog",
                table: "product_search_view",
                column: "category_id");

            migrationBuilder.CreateIndex(
                name: "ix_product_search_view_category_path",
                schema: "catalog",
                table: "product_search_view",
                column: "category_path");

            migrationBuilder.CreateIndex(
                name: "ix_product_search_view_price_amount",
                schema: "catalog",
                table: "product_search_view",
                column: "price_amount");

            migrationBuilder.CreateIndex(
                name: "ix_product_search_view_status",
                schema: "catalog",
                table: "product_search_view",
                column: "status");

            migrationBuilder.CreateIndex(
                name: "ux_product_search_view_sku",
                schema: "catalog",
                table: "product_search_view",
                column: "sku",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_products_category_id",
                schema: "catalog",
                table: "products",
                column: "category_id");

            migrationBuilder.CreateIndex(
                name: "ix_products_status",
                schema: "catalog",
                table: "products",
                column: "status");

            migrationBuilder.CreateIndex(
                name: "ux_products_sku",
                schema: "catalog",
                table: "products",
                column: "sku",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "inbox_messages",
                schema: "catalog");

            migrationBuilder.DropTable(
                name: "outbox_messages",
                schema: "catalog");

            migrationBuilder.DropTable(
                name: "product_images",
                schema: "catalog");

            migrationBuilder.DropTable(
                name: "product_search_view",
                schema: "catalog");

            migrationBuilder.DropTable(
                name: "products",
                schema: "catalog");

            migrationBuilder.DropTable(
                name: "categories",
                schema: "catalog");
        }
    }
}
