<Project Sdk="Microsoft.NET.Sdk">
    <!-- Project-specific packages only (common packages in test/Directory.Build.props) -->
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentResults.Extensions.FluentAssertions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\Invoicing\Invoicing.Domain\Invoicing.Domain.csproj" />
        <ProjectReference Include="..\..\services\Invoicing\Invoicing.Application\Invoicing.Application.csproj" />
        <ProjectReference Include="..\..\services\Invoicing\Invoicing.Infrastructure\Invoicing.Infrastructure.csproj" />
    </ItemGroup>
</Project>
