<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <SonarQubeTestProject>true</SonarQubeTestProject>
        <CoverletOutput>$(MSBuildProjectDirectory)/TestResults/</CoverletOutput>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DotNetAtlas.Sagas\DotNetAtlas.Sagas.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.TestFramework"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json"/>
        <PackageReference Include="NSubstitute"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\DotNetAtlas.Sagas\appsettings.Testing.json" Link="appsettings.Testing.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
