// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Weather.Alerts
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Command sent by Purchase Saga to activate a subscription in the Weather Alerts service after payment is complete.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class ActivateSubscriptionCommand : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ActivateSubscriptionCommand"",""doc"":""Command sent by Purchase Saga to activate a subscription in the Weather Alerts service after payment is complete."",""namespace"":""Weather.Alerts"",""fields"":[{""name"":""CorrelationId"",""doc"":""Correlation ID for tracking the workflow."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""UserId"",""doc"":""User whose subscription to activate."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""PaymentTransactionId"",""doc"":""Payment transaction ID for correlation. Used for refunds if activation fails."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Tier"",""doc"":""Subscription tier to activate."",""type"":{""type"":""enum"",""name"":""SubscriptionTier"",""namespace"":""Weather.Alerts"",""symbols"":[""Pro"",""Ultra""]}},{""name"":""DurationDays"",""doc"":""Duration of the subscription in days."",""type"":""int""},{""name"":""RequestedAtUtc"",""doc"":""UTC timestamp when activation was requested."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Correlation ID for tracking the workflow.
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// User whose subscription to activate.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Payment transaction ID for correlation. Used for refunds if activation fails.
		/// </summary>
		private System.Guid _PaymentTransactionId;
		/// <summary>
		/// Subscription tier to activate.
		/// </summary>
		private Weather.Alerts.SubscriptionTier _Tier;
		/// <summary>
		/// Duration of the subscription in days.
		/// </summary>
		private int _DurationDays;
		/// <summary>
		/// UTC timestamp when activation was requested.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ActivateSubscriptionCommand._SCHEMA;
			}
		}
		/// <summary>
		/// Correlation ID for tracking the workflow.
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// User whose subscription to activate.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Payment transaction ID for correlation. Used for refunds if activation fails.
		/// </summary>
		public System.Guid PaymentTransactionId
		{
			get
			{
				return this._PaymentTransactionId;
			}
			set
			{
				this._PaymentTransactionId = value;
			}
		}
		/// <summary>
		/// Subscription tier to activate.
		/// </summary>
		public Weather.Alerts.SubscriptionTier Tier
		{
			get
			{
				return this._Tier;
			}
			set
			{
				this._Tier = value;
			}
		}
		/// <summary>
		/// Duration of the subscription in days.
		/// </summary>
		public int DurationDays
		{
			get
			{
				return this._DurationDays;
			}
			set
			{
				this._DurationDays = value;
			}
		}
		/// <summary>
		/// UTC timestamp when activation was requested.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CorrelationId;
			case 1: return this.UserId;
			case 2: return this.PaymentTransactionId;
			case 3: return this.Tier;
			case 4: return this.DurationDays;
			case 5: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CorrelationId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.PaymentTransactionId = (System.Guid)fieldValue; break;
			case 3: this.Tier = (Weather.Alerts.SubscriptionTier)fieldValue; break;
			case 4: this.DurationDays = (System.Int32)fieldValue; break;
			case 5: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
