// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Weather.Alerts
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Reusable error details for subscription-related failure events.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class ErrorDetails : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ErrorDetails"",""doc"":""Reusable error details for subscription-related failure events."",""namespace"":""Weather.Alerts"",""fields"":[{""name"":""ErrorCode"",""doc"":""Error code identifying the failure reason."",""type"":""string""},{""name"":""ErrorMessage"",""doc"":""Human-readable error message."",""type"":""string""}]}");
		/// <summary>
		/// Error code identifying the failure reason.
		/// </summary>
		private string _ErrorCode;
		/// <summary>
		/// Human-readable error message.
		/// </summary>
		private string _ErrorMessage;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ErrorDetails._SCHEMA;
			}
		}
		/// <summary>
		/// Error code identifying the failure reason.
		/// </summary>
		public string ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				this._ErrorCode = value;
			}
		}
		/// <summary>
		/// Human-readable error message.
		/// </summary>
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				this._ErrorMessage = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ErrorCode;
			case 1: return this.ErrorMessage;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ErrorCode = (System.String)fieldValue; break;
			case 1: this.ErrorMessage = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
