// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Weather.Alerts
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted by Weather Alerts service when subscription activation succeeds. Consumed by Purchase Saga to complete the workflow.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class SubscriptionActivatedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""SubscriptionActivatedEvent"",""doc"":""Event emitted by Weather Alerts service when subscription activation succeeds. Consumed by Purchase Saga to complete the workflow."",""namespace"":""Weather.Alerts"",""fields"":[{""name"":""CorrelationId"",""doc"":""Correlation ID for tracking the workflow."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""UserId"",""doc"":""User whose subscription was activated."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""PaymentTransactionId"",""doc"":""Payment transaction ID for saga correlation."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Tier"",""doc"":""Subscription tier that was activated."",""type"":{""type"":""enum"",""name"":""SubscriptionTier"",""namespace"":""Weather.Alerts"",""symbols"":[""Pro"",""Ultra""]}},{""name"":""DurationDays"",""doc"":""Duration of the subscription in days."",""type"":""int""},{""name"":""ExpiresAtUtc"",""doc"":""UTC timestamp when the subscription expires."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}},{""name"":""ActivatedAtUtc"",""doc"":""UTC timestamp when activation occurred."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Correlation ID for tracking the workflow.
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// User whose subscription was activated.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Payment transaction ID for saga correlation.
		/// </summary>
		private System.Guid _PaymentTransactionId;
		/// <summary>
		/// Subscription tier that was activated.
		/// </summary>
		private Weather.Alerts.SubscriptionTier _Tier;
		/// <summary>
		/// Duration of the subscription in days.
		/// </summary>
		private int _DurationDays;
		/// <summary>
		/// UTC timestamp when the subscription expires.
		/// </summary>
		private System.DateTime _ExpiresAtUtc;
		/// <summary>
		/// UTC timestamp when activation occurred.
		/// </summary>
		private System.DateTime _ActivatedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return SubscriptionActivatedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Correlation ID for tracking the workflow.
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// User whose subscription was activated.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Payment transaction ID for saga correlation.
		/// </summary>
		public System.Guid PaymentTransactionId
		{
			get
			{
				return this._PaymentTransactionId;
			}
			set
			{
				this._PaymentTransactionId = value;
			}
		}
		/// <summary>
		/// Subscription tier that was activated.
		/// </summary>
		public Weather.Alerts.SubscriptionTier Tier
		{
			get
			{
				return this._Tier;
			}
			set
			{
				this._Tier = value;
			}
		}
		/// <summary>
		/// Duration of the subscription in days.
		/// </summary>
		public int DurationDays
		{
			get
			{
				return this._DurationDays;
			}
			set
			{
				this._DurationDays = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the subscription expires.
		/// </summary>
		public System.DateTime ExpiresAtUtc
		{
			get
			{
				return this._ExpiresAtUtc;
			}
			set
			{
				this._ExpiresAtUtc = value;
			}
		}
		/// <summary>
		/// UTC timestamp when activation occurred.
		/// </summary>
		public System.DateTime ActivatedAtUtc
		{
			get
			{
				return this._ActivatedAtUtc;
			}
			set
			{
				this._ActivatedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CorrelationId;
			case 1: return this.UserId;
			case 2: return this.PaymentTransactionId;
			case 3: return this.Tier;
			case 4: return this.DurationDays;
			case 5: return this.ExpiresAtUtc;
			case 6: return this.ActivatedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CorrelationId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.PaymentTransactionId = (System.Guid)fieldValue; break;
			case 3: this.Tier = (Weather.Alerts.SubscriptionTier)fieldValue; break;
			case 4: this.DurationDays = (System.Int32)fieldValue; break;
			case 5: this.ExpiresAtUtc = (System.DateTime)fieldValue; break;
			case 6: this.ActivatedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
