<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FastEndpoints.Attributes"/>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations"/>
        <PackageReference Include="Riok.Mapperly"/>

        <PackageReference Include="StyleCop.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Ordering.Infrastructure"/>
        <InternalsVisibleTo Include="Ordering.UnitTests"/>
        <InternalsVisibleTo Include="Ordering.IntegrationTests"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Ordering.Domain\Ordering.Domain.csproj" />
        <ProjectReference Include="..\..\..\platform\Platform.CQRS\Platform.CQRS.csproj" />
        <ProjectReference Include="..\..\..\platform\Platform.ReliableMessaging.Outbox.EFCore\Platform.ReliableMessaging.Outbox.EFCore.csproj" />
        <ProjectReference Include="..\..\..\platform\Platform.SchemaRegistry.Contracts\Platform.SchemaRegistry.Contracts.csproj" />
    </ItemGroup>
</Project>
