// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Catalog.Categories
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted when a new category node is created in the Catalog taxonomy.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class CategoryCreatedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""CategoryCreatedEvent"",""doc"":""Event emitted when a new category node is created in the Catalog taxonomy."",""namespace"":""Catalog.Categories"",""fields"":[{""name"":""CategoryId"",""doc"":""Unique identifier of the category."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Name"",""doc"":""Category display name (max 100 chars)."",""type"":""string""},{""name"":""ParentCategoryId"",""doc"":""Optional identifier of the parent category. Null for root nodes."",""default"":null,""type"":[""null"",{""type"":""string"",""logicalType"":""uuid""}]},{""name"":""Path"",""doc"":""Materialized path of this category (e.g., '/electronics/computers'). Depth 1 to 5 segments."",""type"":""string""},{""name"":""CreatedAtUtc"",""doc"":""UTC timestamp when the category was created."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Unique identifier of the category.
		/// </summary>
		private System.Guid _CategoryId;
		/// <summary>
		/// Category display name (max 100 chars).
		/// </summary>
		private string _Name;
		/// <summary>
		/// Optional identifier of the parent category. Null for root nodes.
		/// </summary>
		private System.Nullable<System.Guid> _ParentCategoryId;
		/// <summary>
		/// Materialized path of this category (e.g., '/electronics/computers'). Depth 1 to 5 segments.
		/// </summary>
		private string _Path;
		/// <summary>
		/// UTC timestamp when the category was created.
		/// </summary>
		private System.DateTime _CreatedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return CategoryCreatedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the category.
		/// </summary>
		public System.Guid CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				this._CategoryId = value;
			}
		}
		/// <summary>
		/// Category display name (max 100 chars).
		/// </summary>
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		/// <summary>
		/// Optional identifier of the parent category. Null for root nodes.
		/// </summary>
		public System.Nullable<System.Guid> ParentCategoryId
		{
			get
			{
				return this._ParentCategoryId;
			}
			set
			{
				this._ParentCategoryId = value;
			}
		}
		/// <summary>
		/// Materialized path of this category (e.g., '/electronics/computers'). Depth 1 to 5 segments.
		/// </summary>
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				this._Path = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the category was created.
		/// </summary>
		public System.DateTime CreatedAtUtc
		{
			get
			{
				return this._CreatedAtUtc;
			}
			set
			{
				this._CreatedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CategoryId;
			case 1: return this.Name;
			case 2: return this.ParentCategoryId;
			case 3: return this.Path;
			case 4: return this.CreatedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CategoryId = (System.Guid)fieldValue; break;
			case 1: this.Name = (System.String)fieldValue; break;
			case 2: this.ParentCategoryId = (System.Nullable<System.Guid>)fieldValue; break;
			case 3: this.Path = (System.String)fieldValue; break;
			case 4: this.CreatedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
