<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="NetArchTest.eNhancedEdition" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\Inventory\Inventory.API\Inventory.API.csproj" />
        <ProjectReference Include="..\..\services\Inventory\Inventory.Application\Inventory.Application.csproj" />
        <ProjectReference Include="..\..\services\Inventory\Inventory.Domain\Inventory.Domain.csproj" />
        <ProjectReference Include="..\..\services\Inventory\Inventory.Infrastructure\Inventory.Infrastructure.csproj" />
        <ProjectReference Include="..\..\platform\Platform.Test.Framework\Platform.Test.Framework.csproj" />
    </ItemGroup>
</Project>
