<Project Sdk="Microsoft.NET.Sdk">
    <!-- Project-specific packages only (common packages in test/Directory.Build.props) -->
    <ItemGroup>
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentResults.Extensions.FluentAssertions" />
        <PackageReference Include="Serilog.Sinks.XUnit.Injectable" />
        <PackageReference Include="Testcontainers.Kafka" />
        <PackageReference Include="Testcontainers.Azurite" />
        <PackageReference Include="Azure.Storage.Blobs" />
        <PackageReference Include="Confluent.Kafka" />
        <PackageReference Include="WireMock.Net" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\Invoicing\Invoicing.API\Invoicing.API.csproj" />
        <ProjectReference Include="..\..\services\Invoicing\Invoicing.Infrastructure\Invoicing.Infrastructure.csproj" />
        <ProjectReference Include="..\..\platform\Platform.Test.Framework\Platform.Test.Framework.csproj" />
    </ItemGroup>
</Project>
