// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notifications.Infrastructure.Persistence.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notifications.Infrastructure.Persistence.Database.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    partial class NotificationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Notifications.Domain.Deliveries.NotificationDelivery", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id")
                        .HasComment("Producer-assigned notification intent identity (half of the ledger key).");

                    b.Property<string>("Channel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel")
                        .HasComment("Delivery channel (Email|Sms|Bell) — the other half of the ledger key.");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasComment("UTC timestamp when the row was first inserted.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status")
                        .HasComment("Latest recorded outcome (Dispatched|Failed).");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasComment("UTC timestamp of the latest status write.");

                    b.HasKey("NotificationId", "Channel")
                        .HasName("pk_notification_deliveries");

                    b.ToTable("notification_deliveries", "notifications", t =>
                        {
                            t.HasComment("Per-channel delivery ledger — idempotency + audit, keyed (notification_id, channel). ADR-0031/0032.");
                        });
                });

            modelBuilder.Entity("Platform.ReliableMessaging.Inbox.Core.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id")
                        .HasComment("Unique message identifier (Primary Key).");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc")
                        .HasComment("UTC timestamp when the message was processed.");

                    b.HasKey("MessageId")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_inbox_messages_processed_at_utc");

                    b.ToTable("inbox_messages", "notifications", t =>
                        {
                            t.HasComment("Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.");
                        });
                });

            modelBuilder.Entity("Platform.ReliableMessaging.Outbox.Core.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("PK, Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("AvroPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("avro_payload")
                        .HasComment("Avro-serialized domain event payload");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<string>("Headers")
                        .HasMaxLength(8192)
                        .IsUnicode(true)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("headers")
                        .HasComment("JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.");

                    b.Property<string>("KafkaKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("kafka_key")
                        .HasComment("Kafka Key - typically the Aggregate ID for proper event ordering and partitioning");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(249)
                        .IsUnicode(false)
                        .HasColumnType("character varying(249)")
                        .HasColumnName("topic_name")
                        .HasComment("The Kafka topic where this message will be published. Set by the message producer.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type")
                        .HasComment("Avro type name of the serialized event (e.g., 'FeedbackChangedEvent') for deserialization and observability");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "notifications", t =>
                        {
                            t.HasComment("Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
