using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.Infrastructure.Persistence.Database.Migrations
{
    /// <inheritdoc />
    public partial class CreateInventoryTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "inventory");

            migrationBuilder.CreateTable(
                name: "current_stock_levels",
                schema: "inventory",
                columns: table => new
                {
                    product_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Aggregate identity / stream id. Shared with Catalog's Product.ProductId."),
                    on_hand = table.Column<int>(type: "integer", nullable: false, comment: "Physical units present after the last applied event."),
                    reserved = table.Column<int>(type: "integer", nullable: false, comment: "Active reservations total after the last applied event."),
                    available = table.Column<int>(type: "integer", nullable: false, comment: "OnHand - Reserved after the last applied event. Materialised for indexable reads."),
                    previous_available = table.Column<int>(type: "integer", nullable: false, comment: "Available BEFORE the last applied event; enables StockLevelChangedEvent threshold detection without state replay."),
                    last_updated_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "= OccurredOnUtc of the last applied event."),
                    last_version = table.Column<int>(type: "integer", nullable: false, comment: "Monotonic per-stream event count applied to this row — guards future projection rebuilds against duplicates.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_current_stock_levels", x => x.product_id);
                },
                comment: "Denormalised read projection: one row per ProductId, mutated by CurrentStockLevelsProjectionDomainEventHandler on every ES event. Rebuildable from inventory.stock_events.");

            migrationBuilder.CreateTable(
                name: "inbox_messages",
                schema: "inventory",
                columns: table => new
                {
                    message_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Unique message identifier (Primary Key)."),
                    processed_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "UTC timestamp when the message was processed.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_inbox_messages", x => x.message_id);
                },
                comment: "Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.");

            migrationBuilder.CreateTable(
                name: "outbox_messages",
                schema: "inventory",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false, comment: "PK, Identity")
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    topic_name = table.Column<string>(type: "character varying(249)", unicode: false, maxLength: 249, nullable: false, comment: "The Kafka topic where this message will be published. Set by the message producer."),
                    kafka_key = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true, comment: "Kafka Key - typically the Aggregate ID for proper event ordering and partitioning"),
                    avro_payload = table.Column<byte[]>(type: "bytea", nullable: false, comment: "Avro-serialized domain event payload"),
                    type = table.Column<string>(type: "character varying(255)", unicode: false, maxLength: 255, nullable: false, comment: "Avro type name of the serialized event (e.g., 'FeedbackChangedEvent') for deserialization and observability"),
                    headers = table.Column<string>(type: "character varying(8192)", maxLength: 8192, nullable: true, comment: "JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation."),
                    created_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "Creation timestamp (UTC).")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_outbox_messages", x => x.id);
                },
                comment: "Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.");

            migrationBuilder.CreateTable(
                name: "reservation_audit",
                schema: "inventory",
                columns: table => new
                {
                    reservation_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Saga-supplied reservation id (GUIDv7)."),
                    product_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Stream id joining back to inventory.current_stock_levels.ProductId."),
                    order_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Owning order. Fan-in key for saga correlation."),
                    quantity = table.Column<int>(type: "integer", nullable: false, comment: "Units reserved. Immutable after the initial insert."),
                    status = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false, comment: "Lifecycle: Active -> Confirmed | Released."),
                    reserved_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "UTC timestamp the reservation was created."),
                    expires_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "UTC expiry (= ReservedAtUtc + TTL). Drives the TTL worker scan."),
                    resolved_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "UTC timestamp of the terminal transition; null while Active."),
                    release_reason = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: true, comment: "Populated only on Status=Released (Compensation | Expiry | Cancellation).")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_reservation_audit", x => x.reservation_id);
                },
                comment: "Per-reservation lifecycle projection. Inserted on StockReservedDomainEvent, terminal fields (Status, ResolvedAtUtc, ReleaseReason) mutated on Confirmed / Released. Ops + expiry-worker query surface.");

            migrationBuilder.CreateTable(
                name: "stock_events",
                schema: "inventory",
                columns: table => new
                {
                    stream_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Stream identity = ProductId. One stream per StockItem."),
                    version = table.Column<int>(type: "integer", nullable: false, comment: "Monotonic 1-based version per stream. Enforced by PK."),
                    event_type = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false, comment: "CLR-type name discriminator (e.g. \"StockReservedDomainEvent\") used by the deserializer."),
                    payload = table.Column<string>(type: "jsonb", nullable: false, comment: "JSON-serialized internal event; stored as jsonb for legibility and indexability."),
                    occurred_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "UTC timestamp the domain event was produced; copied from event.OccurredOnUtc for temporal queries."),
                    appended_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, defaultValueSql: "now()", comment: "DB-side insert timestamp; distinguishes domain time from persisted time during replay/tests."),
                    correlation_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "Saga correlation id (ADR-0008); null for ops-originated events.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_stock_events", x => new { x.stream_id, x.version });
                },
                comment: "Append-only event store for StockItem aggregates (ADR-0006). One row per internal ES event; composite PK (StreamId, Version) is the optimistic-concurrency mechanism.");

            migrationBuilder.CreateIndex(
                name: "ix_current_stock_levels_available_low",
                schema: "inventory",
                table: "current_stock_levels",
                column: "available",
                filter: "available <= 10");

            migrationBuilder.CreateIndex(
                name: "ix_inbox_messages_processed_at_utc",
                schema: "inventory",
                table: "inbox_messages",
                column: "processed_at_utc");

            migrationBuilder.CreateIndex(
                name: "ix_reservation_audit_active_expiry",
                schema: "inventory",
                table: "reservation_audit",
                column: "expires_at_utc",
                filter: "status = 'Active'");

            migrationBuilder.CreateIndex(
                name: "ix_reservation_audit_order",
                schema: "inventory",
                table: "reservation_audit",
                column: "order_id");

            migrationBuilder.CreateIndex(
                name: "ix_stock_events_correlation",
                schema: "inventory",
                table: "stock_events",
                column: "correlation_id",
                filter: "correlation_id IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_stock_events_event_type",
                schema: "inventory",
                table: "stock_events",
                column: "event_type");

            migrationBuilder.CreateIndex(
                name: "ix_stock_events_occurred_at",
                schema: "inventory",
                table: "stock_events",
                column: "occurred_at_utc");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "current_stock_levels",
                schema: "inventory");

            migrationBuilder.DropTable(
                name: "inbox_messages",
                schema: "inventory");

            migrationBuilder.DropTable(
                name: "outbox_messages",
                schema: "inventory");

            migrationBuilder.DropTable(
                name: "reservation_audit",
                schema: "inventory");

            migrationBuilder.DropTable(
                name: "stock_events",
                schema: "inventory");
        }
    }
}
