<Project Sdk="Microsoft.NET.Sdk">
    <!-- Project-specific packages only (common packages in test/Directory.Build.props) -->
    <ItemGroup>
        <PackageReference Include="NetArchTest.eNhancedEdition" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\Basket\Basket.Api\Basket.Api.csproj" />
        <ProjectReference Include="..\..\services\Basket\Basket.Domain\Basket.Domain.csproj" />
        <ProjectReference Include="..\..\services\Basket\Basket.Application\Basket.Application.csproj" />
        <ProjectReference Include="..\..\services\Basket\Basket.Infrastructure\Basket.Infrastructure.csproj" />
    </ItemGroup>
</Project>
