<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp" />
        <PackageReference Include="FluentResults.Extensions.FluentAssertions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\Notifications\Notifications.Domain\Notifications.Domain.csproj" />
        <ProjectReference Include="..\..\services\Notifications\Notifications.Application\Notifications.Application.csproj" />
        <ProjectReference Include="..\..\services\Notifications\Notifications.Infrastructure\Notifications.Infrastructure.csproj" />
    </ItemGroup>
</Project>
