<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <SonarQubeTestProject>true</SonarQubeTestProject>
        <CoverletOutput>$(MSBuildProjectDirectory)/TestResults/</CoverletOutput>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SagaOrchestrators\SagaOrchestrators.csproj" />
        <ProjectReference Include="..\..\platform\Platform.Test.Framework\Platform.Test.Framework.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.TestFramework"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="Serilog.Sinks.XUnit.Injectable"/>
    </ItemGroup>
</Project>
