// <auto-generated />
using System;
using System.Collections.Generic;
using Weather.Infrastructure.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Weather.Infrastructure.Persistence.Database.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20260204220526_Asdf")]
    partial class Asdf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("weather")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Weather.Domain.Alerts.AlertSubscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Timestamp when user first subscribed (UTC).");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Timestamp when subscription was last modified (UTC).");

                    b.Property<DateTimeOffset?>("LastPaidSubscriptionEndedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("When the last paid subscription ended. Null if never had paid subscription.");

                    b.Property<DateTimeOffset?>("SubscriptionExpiryAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Expiry date for subscription (UTC). Null for free tier.");

                    b.Property<int>("SubscriptionTier")
                        .HasColumnType("int")
                        .HasComment("Subscription tier (Free, Pro, Ultra).");

                    b.Property<int>("TemperatureUnitPreference")
                        .HasColumnType("int")
                        .HasComment("Preferred temperature unit (Celsius, Fahrenheit, Kelvin).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Optimistic concurrency token.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User who subscribed for weather alerts.");

                    b.Property<int>("WindSpeedUnitPreference")
                        .HasColumnType("int")
                        .HasComment("Preferred wind speed unit (KilometersPerHour, MilesPerHour).");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Subscribers_UserId");

                    b.HasIndex("SubscriptionTier", "SubscriptionExpiryAtUtc")
                        .HasDatabaseName("IX_Subscribers_SubscriptionTier_ExpiryUtc");

                    b.ToTable("AlertSubscribers", "weather", t =>
                        {
                            t.HasComment("Contains subscribers for weather alert subscriptions.");
                        });
                });

            modelBuilder.Entity("Weather.Domain.Alerts.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK");

                    b.Property<int>("CountryCode")
                        .HasColumnType("int")
                        .HasComment("ISO 3166-1 alpha-2 country code.");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Last modification timestamp (UTC).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Optimistic concurrency token.");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "City", "Weather.Domain.Alerts.Entities.Location.City#City", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City")
                                .HasComment("Name of the city.");
                        });

                    b.HasKey("Id");

                    b.ToTable("Locations", "weather", t =>
                        {
                            t.HasComment("Contains city-country locations.");
                        });
                });

            modelBuilder.Entity("Weather.Domain.Alerts.Entities.MonitoredLocationAlertsSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK");

                    b.Property<Guid?>("AlertSubscriberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Last modification timestamp (UTC).");

                    b.Property<Guid>("MonitoredLocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to MonitoredLocation (ID reference only, no navigation).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Optimistic concurrency token.");

                    b.HasKey("Id");

                    b.HasIndex("AlertSubscriberId");

                    b.HasIndex("MonitoredLocationId")
                        .HasDatabaseName("IX_MonitoredLocationAlertsSubscriptions_MonitoredLocationId");

                    b.ToTable("MonitoredLocationAlertsSubscriptions", "weather", t =>
                        {
                            t.HasComment("Contains user subscriptions to monitored location weather alerts.");
                        });
                });

            modelBuilder.Entity("Weather.Domain.Alerts.MonitoredLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasComment("Whether this location is actively being monitored.");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Last modification timestamp (UTC).");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Optimistic concurrency token.");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Thresholds", "Weather.Domain.Alerts.MonitoredLocation.Thresholds#AlertThresholds", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "HighHumidity", "Weather.Domain.Alerts.MonitoredLocation.Thresholds#AlertThresholds.HighHumidity#Humidity", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Percent")
                                        .HasColumnType("float")
                                        .HasColumnName("HighHumidityThresholdPercent")
                                        .HasComment("Humidity threshold for high humidity alerts (%).");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "HighTemperature", "Weather.Domain.Alerts.MonitoredLocation.Thresholds#AlertThresholds.HighTemperature#Temperature", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Celsius")
                                        .HasColumnType("float")
                                        .HasColumnName("HighTemperatureThresholdC")
                                        .HasComment("Temperature threshold for high temperature alerts (°C).");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "HighWindSpeed", "Weather.Domain.Alerts.MonitoredLocation.Thresholds#AlertThresholds.HighWindSpeed#WindSpeed", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("KilometersPerHour")
                                        .HasColumnType("float")
                                        .HasColumnName("HighWindSpeedThresholdKmh")
                                        .HasComment("Wind speed threshold for high wind alerts (km/h).");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "LowHumidity", "Weather.Domain.Alerts.MonitoredLocation.Thresholds#AlertThresholds.LowHumidity#Humidity", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Percent")
                                        .HasColumnType("float")
                                        .HasColumnName("LowHumidityThresholdPercent")
                                        .HasComment("Humidity threshold for low humidity alerts (%).");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "LowTemperature", "Weather.Domain.Alerts.MonitoredLocation.Thresholds#AlertThresholds.LowTemperature#Temperature", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Celsius")
                                        .HasColumnType("float")
                                        .HasColumnName("LowTemperatureThresholdC")
                                        .HasComment("Temperature threshold for low temperature alerts (°C).");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("MonitoredLocations", "weather", t =>
                        {
                            t.HasComment("Contains monitored locations with weather sensor data and alert thresholds.");
                        });
                });

            modelBuilder.Entity("Weather.Domain.Feedback.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("PK");

                    b.Property<Guid>("CreatedByUser")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User who created the feedback.");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Last modification timestamp (UTC).");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Optimistic concurrency token.");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FeedbackText", "Weather.Domain.Feedback.Feedback.FeedbackText#FeedbackText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Feedback")
                                .HasComment("Weather feedback from the user.");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Rating", "Weather.Domain.Feedback.Feedback.Rating#FeedbackRating", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte>("Value")
                                .HasColumnType("tinyint")
                                .HasColumnName("Rating")
                                .HasComment("Rating given by the user.");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUser")
                        .IsUnique()
                        .HasDatabaseName("UX_WeatherFeedback_CreatedByUser");

                    b.ToTable("Feedbacks", "weather", t =>
                        {
                            t.HasComment("Contains user feedbacks about the weather.");
                        });
                });

            modelBuilder.Entity("Platform.ReliableMessaging.Inbox.Core.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique message identifier (Primary Key).");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when the message was processed.");

                    b.HasKey("MessageId");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("IX_InboxMessages_ProcessedAtUtc");

                    b.ToTable("InboxMessages", "weather", t =>
                        {
                            t.HasComment("Inbox pattern table for idempotent message processing. Tracks processed messages to prevent duplicate processing.");
                        });
                });

            modelBuilder.Entity("Platform.ReliableMessaging.Outbox.Core.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("PK, Identity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("AvroPayload")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasComment("Avro-serialized domain event payload");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasComment("Creation timestamp (UTC).");

                    b.Property<string>("Headers")
                        .HasMaxLength(8192)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON dictionary of OpenTelemetry-standard headers for distributed tracing and metadata. Headers are automatically generated by OpenTelemetry propagators for end-to-end trace context propagation.");

                    b.Property<string>("KafkaKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Kafka Key - typically the Aggregate ID for proper event ordering and partitioning");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(249)
                        .IsUnicode(false)
                        .HasColumnType("varchar(249)")
                        .HasComment("The Kafka topic where this message will be published. Set by the message producer.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasComment("Avro type name of the serialized event (e.g., 'FeedbackChangedEvent') for deserialization and observability");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "weather", t =>
                        {
                            t.HasComment("Outbox pattern table for storing domain events as Avro-serialized messages for reliable event publishing.");
                        });
                });

            modelBuilder.Entity("Weather.Domain.Alerts.Entities.MonitoredLocationAlertsSubscription", b =>
                {
                    b.HasOne("Weather.Domain.Alerts.AlertSubscriber", null)
                        .WithMany("MonitoredLocationAlertsSubscriptions")
                        .HasForeignKey("AlertSubscriberId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Weather.Domain.Alerts.MonitoredLocation", b =>
                {
                    b.HasOne("Weather.Domain.Alerts.Entities.Location", "Location")
                        .WithOne()
                        .HasForeignKey("Weather.Domain.Alerts.MonitoredLocation", "LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Weather.Domain.Alerts.ValueObjects.WeatherReading", "RecentReadings", b1 =>
                        {
                            b1.Property<Guid>("MonitoredLocationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<DateTimeOffset>("RecordedAtUtc")
                                .HasJsonPropertyName("recordedAtUtc");

                            b1.HasKey("MonitoredLocationId", "__synthesizedOrdinal");

                            b1.ToTable("MonitoredLocations", "weather");

                            b1.ToJson("RecentReadings");

                            b1.WithOwner()
                                .HasForeignKey("MonitoredLocationId");

                            b1.OwnsOne("Weather.Domain.Alerts.ValueObjects.Humidity", "Humidity", b2 =>
                                {
                                    b2.Property<Guid>("WeatherReadingMonitoredLocationId");

                                    b2.Property<int>("WeatherReading__synthesizedOrdinal");

                                    b2.Property<double>("Percent")
                                        .HasJsonPropertyName("humidityPercent");

                                    b2.HasKey("WeatherReadingMonitoredLocationId", "WeatherReading__synthesizedOrdinal");

                                    b2.ToTable("MonitoredLocations", "weather");

                                    b2.WithOwner()
                                        .HasForeignKey("WeatherReadingMonitoredLocationId", "WeatherReading__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Weather.Domain.Alerts.ValueObjects.Temperature", "Temperature", b2 =>
                                {
                                    b2.Property<Guid>("WeatherReadingMonitoredLocationId");

                                    b2.Property<int>("WeatherReading__synthesizedOrdinal");

                                    b2.Property<double>("Celsius")
                                        .HasJsonPropertyName("temperatureC");

                                    b2.HasKey("WeatherReadingMonitoredLocationId", "WeatherReading__synthesizedOrdinal");

                                    b2.ToTable("MonitoredLocations", "weather");

                                    b2.WithOwner()
                                        .HasForeignKey("WeatherReadingMonitoredLocationId", "WeatherReading__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Weather.Domain.Alerts.ValueObjects.WindSpeed", "WindSpeed", b2 =>
                                {
                                    b2.Property<Guid>("WeatherReadingMonitoredLocationId");

                                    b2.Property<int>("WeatherReading__synthesizedOrdinal");

                                    b2.Property<double>("KilometersPerHour")
                                        .HasJsonPropertyName("windSpeedKmh");

                                    b2.HasKey("WeatherReadingMonitoredLocationId", "WeatherReading__synthesizedOrdinal");

                                    b2.ToTable("MonitoredLocations", "weather");

                                    b2.WithOwner()
                                        .HasForeignKey("WeatherReadingMonitoredLocationId", "WeatherReading__synthesizedOrdinal");
                                });

                            b1.Navigation("Humidity")
                                .IsRequired();

                            b1.Navigation("Temperature")
                                .IsRequired();

                            b1.Navigation("WindSpeed")
                                .IsRequired();
                        });

                    b.Navigation("Location");

                    b.Navigation("RecentReadings");
                });

            modelBuilder.Entity("Weather.Domain.Alerts.AlertSubscriber", b =>
                {
                    b.Navigation("MonitoredLocationAlertsSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
