<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="NetArchTest.eNhancedEdition"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\services\Ordering\Ordering.Api\Ordering.Api.csproj" />
        <ProjectReference Include="..\..\platform\Platform.Test.Framework\Platform.Test.Framework.csproj" />
    </ItemGroup>

</Project>
