// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Notifications.Email
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Emitted after IEmailGateway reports successful send for a SendEmailNotificationCommand. Generic — consumers route by TemplateId prefix.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class EmailNotificationSentEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""EmailNotificationSentEvent"",""doc"":""Emitted after IEmailGateway reports successful send for a SendEmailNotificationCommand. Generic — consumers route by TemplateId prefix."",""namespace"":""Notifications.Email"",""fields"":[{""name"":""UserId"",""doc"":""Recipient user id, copied from the originating command."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""TemplateId"",""doc"":""Template id from the originating command; consumers filter by prefix (e.g., 'invoicing.*')."",""type"":""string""},{""name"":""IdempotencyKey"",""doc"":""Copied from originating command. Carries the BC-specific correlation hint (e.g., 'invoice-delivered-{InvoiceId}-{Attempt}')."",""type"":""string""},{""name"":""SentAtUtc"",""doc"":""When IEmailGateway returned success."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}},{""name"":""OccurredOnUtc"",""doc"":""Domain event occurrence time."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Recipient user id, copied from the originating command.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Template id from the originating command; consumers filter by prefix (e.g., 'invoicing.*').
		/// </summary>
		private string _TemplateId;
		/// <summary>
		/// Copied from originating command. Carries the BC-specific correlation hint (e.g., 'invoice-delivered-{InvoiceId}-{Attempt}').
		/// </summary>
		private string _IdempotencyKey;
		/// <summary>
		/// When IEmailGateway returned success.
		/// </summary>
		private System.DateTime _SentAtUtc;
		/// <summary>
		/// Domain event occurrence time.
		/// </summary>
		private System.DateTime _OccurredOnUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return EmailNotificationSentEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Recipient user id, copied from the originating command.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Template id from the originating command; consumers filter by prefix (e.g., 'invoicing.*').
		/// </summary>
		public string TemplateId
		{
			get
			{
				return this._TemplateId;
			}
			set
			{
				this._TemplateId = value;
			}
		}
		/// <summary>
		/// Copied from originating command. Carries the BC-specific correlation hint (e.g., 'invoice-delivered-{InvoiceId}-{Attempt}').
		/// </summary>
		public string IdempotencyKey
		{
			get
			{
				return this._IdempotencyKey;
			}
			set
			{
				this._IdempotencyKey = value;
			}
		}
		/// <summary>
		/// When IEmailGateway returned success.
		/// </summary>
		public System.DateTime SentAtUtc
		{
			get
			{
				return this._SentAtUtc;
			}
			set
			{
				this._SentAtUtc = value;
			}
		}
		/// <summary>
		/// Domain event occurrence time.
		/// </summary>
		public System.DateTime OccurredOnUtc
		{
			get
			{
				return this._OccurredOnUtc;
			}
			set
			{
				this._OccurredOnUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.UserId;
			case 1: return this.TemplateId;
			case 2: return this.IdempotencyKey;
			case 3: return this.SentAtUtc;
			case 4: return this.OccurredOnUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.UserId = (System.Guid)fieldValue; break;
			case 1: this.TemplateId = (System.String)fieldValue; break;
			case 2: this.IdempotencyKey = (System.String)fieldValue; break;
			case 3: this.SentAtUtc = (System.DateTime)fieldValue; break;
			case 4: this.OccurredOnUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
