// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Finance.Payments
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Command sent by Payment Saga to request payment authorization from the Payment Service.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class AuthorizePaymentCommand : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""AuthorizePaymentCommand"",""doc"":""Command sent by Payment Saga to request payment authorization from the Payment Service."",""namespace"":""Finance.Payments"",""fields"":[{""name"":""CorrelationId"",""doc"":""Correlation ID for tracking the workflow."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""UserId"",""doc"":""User to authorize payment for."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""PaymentMethodId"",""doc"":""ID of the saved payment method to use."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Amount"",""doc"":""Amount to authorize."",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":19,""scale"":4}},{""name"":""Currency"",""doc"":""ISO 4217 currency code."",""type"":""string""},{""name"":""IdempotencyKey"",""doc"":""Idempotency key to prevent duplicate authorizations."",""type"":""string""},{""name"":""RequestedAtUtc"",""doc"":""UTC timestamp when authorization was requested."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Correlation ID for tracking the workflow.
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// User to authorize payment for.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// ID of the saved payment method to use.
		/// </summary>
		private System.Guid _PaymentMethodId;
		/// <summary>
		/// Amount to authorize.
		/// </summary>
		private Avro.AvroDecimal _Amount;
		/// <summary>
		/// ISO 4217 currency code.
		/// </summary>
		private string _Currency;
		/// <summary>
		/// Idempotency key to prevent duplicate authorizations.
		/// </summary>
		private string _IdempotencyKey;
		/// <summary>
		/// UTC timestamp when authorization was requested.
		/// </summary>
		private System.DateTime _RequestedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AuthorizePaymentCommand._SCHEMA;
			}
		}
		/// <summary>
		/// Correlation ID for tracking the workflow.
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// User to authorize payment for.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// ID of the saved payment method to use.
		/// </summary>
		public System.Guid PaymentMethodId
		{
			get
			{
				return this._PaymentMethodId;
			}
			set
			{
				this._PaymentMethodId = value;
			}
		}
		/// <summary>
		/// Amount to authorize.
		/// </summary>
		public Avro.AvroDecimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				this._Amount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code.
		/// </summary>
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		/// <summary>
		/// Idempotency key to prevent duplicate authorizations.
		/// </summary>
		public string IdempotencyKey
		{
			get
			{
				return this._IdempotencyKey;
			}
			set
			{
				this._IdempotencyKey = value;
			}
		}
		/// <summary>
		/// UTC timestamp when authorization was requested.
		/// </summary>
		public System.DateTime RequestedAtUtc
		{
			get
			{
				return this._RequestedAtUtc;
			}
			set
			{
				this._RequestedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CorrelationId;
			case 1: return this.UserId;
			case 2: return this.PaymentMethodId;
			case 3: return this.Amount;
			case 4: return this.Currency;
			case 5: return this.IdempotencyKey;
			case 6: return this.RequestedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CorrelationId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.PaymentMethodId = (System.Guid)fieldValue; break;
			case 3: this.Amount = (Avro.AvroDecimal)fieldValue; break;
			case 4: this.Currency = (System.String)fieldValue; break;
			case 5: this.IdempotencyKey = (System.String)fieldValue; break;
			case 6: this.RequestedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
