// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Finance.Payments
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted when payment authorization fails. No funds were reserved.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class PaymentAuthorizationFailedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PaymentAuthorizationFailedEvent"",""doc"":""Event emitted when payment authorization fails. No funds were reserved."",""namespace"":""Finance.Payments"",""fields"":[{""name"":""CorrelationId"",""doc"":""Correlation ID for tracking the payment workflow."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""UserId"",""doc"":""User whose payment authorization failed."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""ErrorCode"",""doc"":""Error code from the payment provider (e.g., 'INSUFFICIENT_FUNDS', 'CARD_DECLINED', 'FRAUD_SUSPECTED')."",""type"":""string""},{""name"":""ErrorMessage"",""doc"":""Human-readable error message."",""type"":""string""},{""name"":""IsRetryable"",""doc"":""Indicates whether this failure is retryable (e.g., temporary network issue vs. hard decline)."",""type"":""boolean""},{""name"":""FailedAtUtc"",""doc"":""UTC timestamp when authorization failed."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Correlation ID for tracking the payment workflow.
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// User whose payment authorization failed.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Error code from the payment provider (e.g., 'INSUFFICIENT_FUNDS', 'CARD_DECLINED', 'FRAUD_SUSPECTED').
		/// </summary>
		private string _ErrorCode;
		/// <summary>
		/// Human-readable error message.
		/// </summary>
		private string _ErrorMessage;
		/// <summary>
		/// Indicates whether this failure is retryable (e.g., temporary network issue vs. hard decline).
		/// </summary>
		private bool _IsRetryable;
		/// <summary>
		/// UTC timestamp when authorization failed.
		/// </summary>
		private System.DateTime _FailedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PaymentAuthorizationFailedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Correlation ID for tracking the payment workflow.
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// User whose payment authorization failed.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Error code from the payment provider (e.g., 'INSUFFICIENT_FUNDS', 'CARD_DECLINED', 'FRAUD_SUSPECTED').
		/// </summary>
		public string ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				this._ErrorCode = value;
			}
		}
		/// <summary>
		/// Human-readable error message.
		/// </summary>
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				this._ErrorMessage = value;
			}
		}
		/// <summary>
		/// Indicates whether this failure is retryable (e.g., temporary network issue vs. hard decline).
		/// </summary>
		public bool IsRetryable
		{
			get
			{
				return this._IsRetryable;
			}
			set
			{
				this._IsRetryable = value;
			}
		}
		/// <summary>
		/// UTC timestamp when authorization failed.
		/// </summary>
		public System.DateTime FailedAtUtc
		{
			get
			{
				return this._FailedAtUtc;
			}
			set
			{
				this._FailedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CorrelationId;
			case 1: return this.UserId;
			case 2: return this.ErrorCode;
			case 3: return this.ErrorMessage;
			case 4: return this.IsRetryable;
			case 5: return this.FailedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CorrelationId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.ErrorCode = (System.String)fieldValue; break;
			case 3: this.ErrorMessage = (System.String)fieldValue; break;
			case 4: this.IsRetryable = (System.Boolean)fieldValue; break;
			case 5: this.FailedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
