// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Finance.Payments
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted when a payment has been successfully captured. The funds have been transferred.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class PaymentCapturedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PaymentCapturedEvent"",""doc"":""Event emitted when a payment has been successfully captured. The funds have been transferred."",""namespace"":""Finance.Payments"",""fields"":[{""name"":""CorrelationId"",""doc"":""Correlation ID for tracking the payment workflow."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""UserId"",""doc"":""User whose payment was captured."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""PaymentTransactionId"",""doc"":""Payment transaction ID for the captured funds. Used for refunds if needed."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""AuthorizationId"",""doc"":""Authorization ID that was captured."",""type"":""string""},{""name"":""Amount"",""doc"":""Captured payment amount."",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":10,""scale"":2}},{""name"":""Currency"",""doc"":""ISO 4217 currency code."",""type"":""string""},{""name"":""CapturedAtUtc"",""doc"":""UTC timestamp when capture was completed."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Correlation ID for tracking the payment workflow.
		/// </summary>
		private System.Guid _CorrelationId;
		/// <summary>
		/// User whose payment was captured.
		/// </summary>
		private System.Guid _UserId;
		/// <summary>
		/// Payment transaction ID for the captured funds. Used for refunds if needed.
		/// </summary>
		private System.Guid _PaymentTransactionId;
		/// <summary>
		/// Authorization ID that was captured.
		/// </summary>
		private string _AuthorizationId;
		/// <summary>
		/// Captured payment amount.
		/// </summary>
		private Avro.AvroDecimal _Amount;
		/// <summary>
		/// ISO 4217 currency code.
		/// </summary>
		private string _Currency;
		/// <summary>
		/// UTC timestamp when capture was completed.
		/// </summary>
		private System.DateTime _CapturedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PaymentCapturedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Correlation ID for tracking the payment workflow.
		/// </summary>
		public System.Guid CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// User whose payment was captured.
		/// </summary>
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		/// <summary>
		/// Payment transaction ID for the captured funds. Used for refunds if needed.
		/// </summary>
		public System.Guid PaymentTransactionId
		{
			get
			{
				return this._PaymentTransactionId;
			}
			set
			{
				this._PaymentTransactionId = value;
			}
		}
		/// <summary>
		/// Authorization ID that was captured.
		/// </summary>
		public string AuthorizationId
		{
			get
			{
				return this._AuthorizationId;
			}
			set
			{
				this._AuthorizationId = value;
			}
		}
		/// <summary>
		/// Captured payment amount.
		/// </summary>
		public Avro.AvroDecimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				this._Amount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code.
		/// </summary>
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		/// <summary>
		/// UTC timestamp when capture was completed.
		/// </summary>
		public System.DateTime CapturedAtUtc
		{
			get
			{
				return this._CapturedAtUtc;
			}
			set
			{
				this._CapturedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CorrelationId;
			case 1: return this.UserId;
			case 2: return this.PaymentTransactionId;
			case 3: return this.AuthorizationId;
			case 4: return this.Amount;
			case 5: return this.Currency;
			case 6: return this.CapturedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CorrelationId = (System.Guid)fieldValue; break;
			case 1: this.UserId = (System.Guid)fieldValue; break;
			case 2: this.PaymentTransactionId = (System.Guid)fieldValue; break;
			case 3: this.AuthorizationId = (System.String)fieldValue; break;
			case 4: this.Amount = (Avro.AvroDecimal)fieldValue; break;
			case 5: this.Currency = (System.String)fieldValue; break;
			case 6: this.CapturedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
