name: CI (PR)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  validate-pr-title:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/pr-conventional-commit-validation.yml

  run-ci:
    needs: [validate-pr-title]
    permissions:
      contents: write
      pages: write
      packages: write
      id-token: write
      attestations: write
    uses: ./.github/workflows/ci-main.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

