name: Reusable - Determine GitVersion

on:
  workflow_call:
    outputs:
      semVer:
        value: ${{ jobs.determine.outputs.semVer }}
      assemblySemVer:
        value: ${{ jobs.determine.outputs.assemblySemVer }}
      assemblySemFileVer:
        value: ${{ jobs.determine.outputs.assemblySemFileVer }}
      informationalVersion:
        value: ${{ jobs.determine.outputs.informationalVersion }}

jobs:
  determine:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    permissions:
      contents: read
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      assemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}
      assemblySemFileVer: ${{ steps.gitversion.outputs.assemblySemFileVer }}
      informationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup .NET SDK (10.0.100-rc.1.25451.107)
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.100-rc.1.25451.107"
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      - run: dotnet restore --locked-mode
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@b82e662a7199df56ac962118e506d9efb9830f82 #v4.1.0
        with:
          versionSpec: '6.3.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@b82e662a7199df56ac962118e506d9efb9830f82 #v4.1.0
