name: Reusable - Enforce Format

on:
  workflow_call:
  workflow_dispatch:

jobs:
  enforce-format:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup .NET SDK (10.0.100-rc.1.25451.107)
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
        with:
          dotnet-version: "10.0.100-rc.1.25451.107"
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: Verify format
        id: verify
        continue-on-error: true
        run: |
          dotnet format --verify-no-changes --verbosity diagnostic

      - name: Auto-fix formatting with new commit
        if: steps.verify.outcome == 'failure'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Apply formatting changes
          dotnet format --verbosity minimal || true
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(format): Apply dotnet format"
          git push -u origin HEAD
