name: CI (PR)

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches-ignore:
      - "**/graphite-base/**"
permissions:
  contents: read

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  validate-pr-title:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/pr-conventional-commit-validation.yml

  enforce-format:
    needs: [validate-pr-title]
    permissions:
      contents: write
    uses: ./.github/workflows/pr-enforce-format.yml

  run-ci:
    needs: [enforce-format]
    permissions:
      contents: write
      pages: write
      packages: write
      id-token: write
      attestations: write
      actions: write
    uses: ./.github/workflows/main-ci.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

