name: Reusable - Test with Coverage

on:
  workflow_call:
    inputs:
      configuration:
        required: false
        type: string
        default: Release

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup .NET SDK (10.0.100-rc.1.25451.107)
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.100-rc.1.25451.107"
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      - name: Restore
        run: dotnet restore --locked-mode
      - name: Build (for tests)
        env:
          CONFIGURATION: ${{ inputs.configuration }}
        run: dotnet build -c "$CONFIGURATION" --no-restore
      - name: Test with coverage
        env:
          CONFIGURATION: ${{ inputs.configuration }}
        run: |
          dotnet test \
            --no-build \
            -c "$CONFIGURATION" \
            --settings test/coverlet.runsettings \
            --collect "XPlat Code Coverage" \
            --logger "trx;LogFileName=test_results.trx"
      - name: Upload Test Result Files
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/**/TestResults/**/*
          retention-days: 30
      - name: Upload raw coverage XMLs
        uses: actions/upload-artifact@v4
        with:
          name: raw-coverage
          path: ${{ github.workspace }}/**/*.cobertura.xml
          retention-days: 7
