name: Reusable - Test with Coverage

on:
  workflow_call:
    inputs:
      configuration:
        required: false
        type: string
        default: Release

jobs:
  test-with-coverage:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup .NET SDK (10.0.100-rc.1.25451.107)
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
        with:
          dotnet-version: "10.0.100-rc.1.25451.107"
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      - name: Restore
        run: dotnet restore --locked-mode
      - name: Build (for tests)
        env:
          CONFIGURATION: ${{ inputs.configuration }}
        run: dotnet build -c "$CONFIGURATION" --no-restore
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        continue-on-error: true
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('test/DotNetAtlas.Test.Framework/**/*Container.cs') }}
      - name: Test with coverage
        env:
          CONFIGURATION: ${{ inputs.configuration }}
        run: |
          dotnet test \
            --no-build \
            -c "$CONFIGURATION" \
            --settings test/coverlet.runsettings \
            --collect "XPlat Code Coverage" \
            --logger "trx;LogFileName=test_results.trx"
      - name: Upload Test Result Files
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: test-results
          path: ${{ github.workspace }}/**/TestResults/**/*
          retention-days: 30
      - name: Upload raw coverage XMLs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: raw-coverage
          path: ${{ github.workspace }}/**/*.cobertura.xml
          retention-days: 7
