// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Catalog.Products
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted when a product is moved to the Discontinued status. Downstream services should stop offering this product for new purchases.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class ProductDiscontinuedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ProductDiscontinuedEvent"",""doc"":""Event emitted when a product is moved to the Discontinued status. Downstream services should stop offering this product for new purchases."",""namespace"":""Catalog.Products"",""fields"":[{""name"":""ProductId"",""doc"":""Unique identifier of the product that was discontinued."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Sku"",""doc"":""Business key of the product (denormalized for consumer convenience)."",""type"":""string""},{""name"":""Reason"",""doc"":""Free-text reason supplied by the operator (non-empty). Informational only."",""type"":""string""},{""name"":""DiscontinuedAtUtc"",""doc"":""UTC timestamp when the product was discontinued."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Unique identifier of the product that was discontinued.
		/// </summary>
		private System.Guid _ProductId;
		/// <summary>
		/// Business key of the product (denormalized for consumer convenience).
		/// </summary>
		private string _Sku;
		/// <summary>
		/// Free-text reason supplied by the operator (non-empty). Informational only.
		/// </summary>
		private string _Reason;
		/// <summary>
		/// UTC timestamp when the product was discontinued.
		/// </summary>
		private System.DateTime _DiscontinuedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ProductDiscontinuedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the product that was discontinued.
		/// </summary>
		public System.Guid ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				this._ProductId = value;
			}
		}
		/// <summary>
		/// Business key of the product (denormalized for consumer convenience).
		/// </summary>
		public string Sku
		{
			get
			{
				return this._Sku;
			}
			set
			{
				this._Sku = value;
			}
		}
		/// <summary>
		/// Free-text reason supplied by the operator (non-empty). Informational only.
		/// </summary>
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				this._Reason = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the product was discontinued.
		/// </summary>
		public System.DateTime DiscontinuedAtUtc
		{
			get
			{
				return this._DiscontinuedAtUtc;
			}
			set
			{
				this._DiscontinuedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ProductId;
			case 1: return this.Sku;
			case 2: return this.Reason;
			case 3: return this.DiscontinuedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ProductId = (System.Guid)fieldValue; break;
			case 1: this.Sku = (System.String)fieldValue; break;
			case 2: this.Reason = (System.String)fieldValue; break;
			case 3: this.DiscontinuedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
