// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Catalog.Products
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted when a product's price is changed. Carries both old and new price so downstream consumers can detect magnitude of change without a prior snapshot.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class ProductPriceChangedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ProductPriceChangedEvent"",""doc"":""Event emitted when a product's price is changed. Carries both old and new price so downstream consumers can detect magnitude of change without a prior snapshot."",""namespace"":""Catalog.Products"",""fields"":[{""name"":""ProductId"",""doc"":""Unique identifier of the product whose price changed."",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""Sku"",""doc"":""Business key of the product (denormalized for consumer convenience)."",""type"":""string""},{""name"":""OldPriceAmount"",""doc"":""Price amount before the change."",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":19,""scale"":4}},{""name"":""NewPriceAmount"",""doc"":""Price amount after the change."",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":19,""scale"":4}},{""name"":""Currency"",""doc"":""ISO 4217 currency code. Same for old and new (Catalog does not support currency swap on a product)."",""type"":""string""},{""name"":""ChangedAtUtc"",""doc"":""UTC timestamp when the price change was recorded."",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		/// <summary>
		/// Unique identifier of the product whose price changed.
		/// </summary>
		private System.Guid _ProductId;
		/// <summary>
		/// Business key of the product (denormalized for consumer convenience).
		/// </summary>
		private string _Sku;
		/// <summary>
		/// Price amount before the change.
		/// </summary>
		private Avro.AvroDecimal _OldPriceAmount;
		/// <summary>
		/// Price amount after the change.
		/// </summary>
		private Avro.AvroDecimal _NewPriceAmount;
		/// <summary>
		/// ISO 4217 currency code. Same for old and new (Catalog does not support currency swap on a product).
		/// </summary>
		private string _Currency;
		/// <summary>
		/// UTC timestamp when the price change was recorded.
		/// </summary>
		private System.DateTime _ChangedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ProductPriceChangedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the product whose price changed.
		/// </summary>
		public System.Guid ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				this._ProductId = value;
			}
		}
		/// <summary>
		/// Business key of the product (denormalized for consumer convenience).
		/// </summary>
		public string Sku
		{
			get
			{
				return this._Sku;
			}
			set
			{
				this._Sku = value;
			}
		}
		/// <summary>
		/// Price amount before the change.
		/// </summary>
		public Avro.AvroDecimal OldPriceAmount
		{
			get
			{
				return this._OldPriceAmount;
			}
			set
			{
				this._OldPriceAmount = value;
			}
		}
		/// <summary>
		/// Price amount after the change.
		/// </summary>
		public Avro.AvroDecimal NewPriceAmount
		{
			get
			{
				return this._NewPriceAmount;
			}
			set
			{
				this._NewPriceAmount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code. Same for old and new (Catalog does not support currency swap on a product).
		/// </summary>
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				this._Currency = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the price change was recorded.
		/// </summary>
		public System.DateTime ChangedAtUtc
		{
			get
			{
				return this._ChangedAtUtc;
			}
			set
			{
				this._ChangedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ProductId;
			case 1: return this.Sku;
			case 2: return this.OldPriceAmount;
			case 3: return this.NewPriceAmount;
			case 4: return this.Currency;
			case 5: return this.ChangedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ProductId = (System.Guid)fieldValue; break;
			case 1: this.Sku = (System.String)fieldValue; break;
			case 2: this.OldPriceAmount = (Avro.AvroDecimal)fieldValue; break;
			case 3: this.NewPriceAmount = (Avro.AvroDecimal)fieldValue; break;
			case 4: this.Currency = (System.String)fieldValue; break;
			case 5: this.ChangedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
