// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Catalog.Products
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted when a new product is created in the Catalog. Enriched summary carrying all information downstream services need to initialize their own projections without calling back into Catalog.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class ProductCreatedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ProductCreatedEvent\",\"doc\":\"Event emitted when a new pro" +
				"duct is created in the Catalog. Enriched summary carrying all information downst" +
				"ream services need to initialize their own projections without calling back into" +
				" Catalog.\",\"namespace\":\"Catalog.Products\",\"fields\":[{\"name\":\"ProductId\",\"doc\":\"U" +
				"nique identifier of the product aggregate.\",\"type\":{\"type\":\"string\",\"logicalType" +
				"\":\"uuid\"}},{\"name\":\"Sku\",\"doc\":\"Business key for the product (1-32 chars, alphan" +
				"umeric + dashes, uppercase).\",\"type\":\"string\"},{\"name\":\"Name\",\"doc\":\"Product dis" +
				"play name (max 200 chars).\",\"type\":\"string\"},{\"name\":\"Description\",\"doc\":\"Produc" +
				"t description truncated to 1000 chars for transport. Consumers requiring full te" +
				"xt must fetch via Catalog query API.\",\"type\":\"string\"},{\"name\":\"CategoryId\",\"doc" +
				"\":\"Identifier of the category to which the product is assigned.\",\"type\":{\"type\":" +
				"\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"CategoryPath\",\"doc\":\"Materialized categ" +
				"ory path (e.g., \'/electronics/computers/laptops\'). Enables prefix filtering down" +
				"stream without a Catalog lookup.\",\"type\":\"string\"},{\"name\":\"BrandName\",\"doc\":\"Br" +
				"and name (max 100 chars).\",\"type\":\"string\"},{\"name\":\"PriceAmount\",\"doc\":\"Product" +
				" price amount.\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":19,\"s" +
				"cale\":4}},{\"name\":\"PriceCurrency\",\"doc\":\"ISO 4217 currency code (e.g., \'USD\', \'E" +
				"UR\').\",\"type\":\"string\"},{\"name\":\"Status\",\"doc\":\"Product lifecycle status at the " +
				"time of the event.\",\"type\":{\"type\":\"enum\",\"name\":\"ProductStatus\",\"namespace\":\"Ca" +
				"talog.Products\",\"symbols\":[\"Active\",\"Discontinued\"]}},{\"name\":\"CreatedAtUtc\",\"do" +
				"c\":\"UTC timestamp when the product was created.\",\"type\":{\"type\":\"long\",\"logicalT" +
				"ype\":\"timestamp-millis\"}}]}");
		/// <summary>
		/// Unique identifier of the product aggregate.
		/// </summary>
		private System.Guid _ProductId;
		/// <summary>
		/// Business key for the product (1-32 chars, alphanumeric + dashes, uppercase).
		/// </summary>
		private string _Sku;
		/// <summary>
		/// Product display name (max 200 chars).
		/// </summary>
		private string _Name;
		/// <summary>
		/// Product description truncated to 1000 chars for transport. Consumers requiring full text must fetch via Catalog query API.
		/// </summary>
		private string _Description;
		/// <summary>
		/// Identifier of the category to which the product is assigned.
		/// </summary>
		private System.Guid _CategoryId;
		/// <summary>
		/// Materialized category path (e.g., '/electronics/computers/laptops'). Enables prefix filtering downstream without a Catalog lookup.
		/// </summary>
		private string _CategoryPath;
		/// <summary>
		/// Brand name (max 100 chars).
		/// </summary>
		private string _BrandName;
		/// <summary>
		/// Product price amount.
		/// </summary>
		private Avro.AvroDecimal _PriceAmount;
		/// <summary>
		/// ISO 4217 currency code (e.g., 'USD', 'EUR').
		/// </summary>
		private string _PriceCurrency;
		/// <summary>
		/// Product lifecycle status at the time of the event.
		/// </summary>
		private Catalog.Products.ProductStatus _Status;
		/// <summary>
		/// UTC timestamp when the product was created.
		/// </summary>
		private System.DateTime _CreatedAtUtc;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ProductCreatedEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the product aggregate.
		/// </summary>
		public System.Guid ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				this._ProductId = value;
			}
		}
		/// <summary>
		/// Business key for the product (1-32 chars, alphanumeric + dashes, uppercase).
		/// </summary>
		public string Sku
		{
			get
			{
				return this._Sku;
			}
			set
			{
				this._Sku = value;
			}
		}
		/// <summary>
		/// Product display name (max 200 chars).
		/// </summary>
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		/// <summary>
		/// Product description truncated to 1000 chars for transport. Consumers requiring full text must fetch via Catalog query API.
		/// </summary>
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				this._Description = value;
			}
		}
		/// <summary>
		/// Identifier of the category to which the product is assigned.
		/// </summary>
		public System.Guid CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				this._CategoryId = value;
			}
		}
		/// <summary>
		/// Materialized category path (e.g., '/electronics/computers/laptops'). Enables prefix filtering downstream without a Catalog lookup.
		/// </summary>
		public string CategoryPath
		{
			get
			{
				return this._CategoryPath;
			}
			set
			{
				this._CategoryPath = value;
			}
		}
		/// <summary>
		/// Brand name (max 100 chars).
		/// </summary>
		public string BrandName
		{
			get
			{
				return this._BrandName;
			}
			set
			{
				this._BrandName = value;
			}
		}
		/// <summary>
		/// Product price amount.
		/// </summary>
		public Avro.AvroDecimal PriceAmount
		{
			get
			{
				return this._PriceAmount;
			}
			set
			{
				this._PriceAmount = value;
			}
		}
		/// <summary>
		/// ISO 4217 currency code (e.g., 'USD', 'EUR').
		/// </summary>
		public string PriceCurrency
		{
			get
			{
				return this._PriceCurrency;
			}
			set
			{
				this._PriceCurrency = value;
			}
		}
		/// <summary>
		/// Product lifecycle status at the time of the event.
		/// </summary>
		public Catalog.Products.ProductStatus Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				this._Status = value;
			}
		}
		/// <summary>
		/// UTC timestamp when the product was created.
		/// </summary>
		public System.DateTime CreatedAtUtc
		{
			get
			{
				return this._CreatedAtUtc;
			}
			set
			{
				this._CreatedAtUtc = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ProductId;
			case 1: return this.Sku;
			case 2: return this.Name;
			case 3: return this.Description;
			case 4: return this.CategoryId;
			case 5: return this.CategoryPath;
			case 6: return this.BrandName;
			case 7: return this.PriceAmount;
			case 8: return this.PriceCurrency;
			case 9: return this.Status;
			case 10: return this.CreatedAtUtc;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ProductId = (System.Guid)fieldValue; break;
			case 1: this.Sku = (System.String)fieldValue; break;
			case 2: this.Name = (System.String)fieldValue; break;
			case 3: this.Description = (System.String)fieldValue; break;
			case 4: this.CategoryId = (System.Guid)fieldValue; break;
			case 5: this.CategoryPath = (System.String)fieldValue; break;
			case 6: this.BrandName = (System.String)fieldValue; break;
			case 7: this.PriceAmount = (Avro.AvroDecimal)fieldValue; break;
			case 8: this.PriceCurrency = (System.String)fieldValue; break;
			case 9: this.Status = (Catalog.Products.ProductStatus)fieldValue; break;
			case 10: this.CreatedAtUtc = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
